= Spring Cloud Azure Service Bus JMS Code Sample

This code sample demonstrates how to use Spring JMS for Azure Service Bus.

Running this sample will be charged by Azure. You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

== Connection string based usage

1. Create Azure Service Bus namespace, queue and topic. Please see https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal[how to create]. 

2. Update link:src/main/resources/application.properties[application.properties]

+
....
# Fill service bus namespace connection string copied from portal
spring.cloud.azure.servicebus.jms.connection-string=[servicebus-namespace-connection-string]

# Client ID is required if using service bus topic
spring.cloud.azure.servicebus.jms.client-id=[client-id]

# Idle Timeout will be set to a default value of 3600000 if you don't set it
spring.cloud.azure.servicebus.jms.idle-timeout=[idle-timeout]
....


== How to run

3. Update queue name in link:src/main/java/com/example/QueueSendController.java#L20[QueueSendController] and link:src/main/java/com/example/QueueReceiveController.java#L17[QueueReceiveController],
topic name in link:src/main/java/com/example/TopicSendController.java#L20[TopicSendController] and link:src/main/java/com/example/TopicReceiveController.java#L17[TopicReceiveController],
and subscription in link:src/main/java/com/example/TopicReceiveController.java#L19[TopicReceiveController].

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5. Send a POST request to service bus queue
+
....
$ curl -X POST localhost:8080/queue?message=hello
....

6. Verify in your app's logs that a similar message was posted:
+
....
Sending message
Received message from queue: hello
....

7.  Send a POST request to service bus topic
+
....
$ curl -X POST localhost:8080/topic?message=hello
....

8. Verify in your app's logs that a similar message was posted:
+
....
Sending message
Received message from topic: hello
....

9. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid extra charges.
