= Spring Cloud Azure Storage Queue Integration Code Sample

This code sample demonstrates how to use Spring Integration for Azure Storage Queue.

Running this sample will be charged by Azure. You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

== How to run

1.  Create Azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how
to create credential file]
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put auth file under `src/main/resources/`.

3. Update link:src/main/resources/application.properties[application.properties] file
+
....
# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file-path]
spring.cloud.azure.resource-group=[resource-group]
spring.cloud.azure.region=[region]

#Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
spring.cloud.azure.storage.account=[account-name]
....
+
All azure resources will be created if missing. Alternatively, you can manually create
https://docs.microsoft.com/en-us/azure/storage/common/storage-create-storage-account[Azure Storage Account].

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5.  Send a POST request
+
....
$ curl -X POST localhost:8080/messages?message=hello
....

6. Verify in your app's logs that a similar message was posted:
+
`message received: hello`

7. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid unexpected charges.