spring:
  thymeleaf:
    cache: false
  cloud:
    azure:
      appconfiguration:
        watch:
          enabled: True
          delay: 5s
config:
  message: Hi
feature-management:
  featureSet:
    FeatureManagement:
      Beta:
        id: Beta
        enabled: true
        enabledFor:
          -
            name: Random
            parameters:
              chance: "50"
          -
            name: ClientFilter
            parameters:
              clientIp: 10.0.0.1