
=== How to use the Spring Boot Starter for Azure Service Bus JMS

This article demonstrates how to use Spring Boot Starter for Azure Service Bus JMS to send messages to and receive messages from Service Bus `queues` and `topics`.

Azure provides an asynchronous messaging platform called link:/azure/service-bus-messaging/service-bus-messaging-overview[Azure Service Bus] ("Service Bus") that is based on the http://www.amqp.org/[Advanced Message Queueing Protocol 1.0] ("AMQP 1.0") standard. Service Bus can be used across the range of supported Azure platforms.

The Spring Boot Starter for Azure Service Bus JMS provides Spring JMS integration with Service Bus.

The following video describes how to integrate Spring JMS applications with Azure Service Bus using JMS 2.0.

video::https://www.youtube.com/embed/9O3CALyoZHE?list=PLPeZXlCR7ew8LlhnSH63KcM0XhMKxT1k_[]

==== Prerequisites

The following prerequisites are required for this article:

. If you don't have an link:https://docs.microsoft.com/azure/guides/developer/azure-developer-guide#understanding-accounts-subscriptions-and-billing[Azure subscription], create a link:https://azure.microsoft.com/free/?ref=microsoft.com&utm_source=microsoft.com&utm_medium=docs&utm_campaign=visualstudio[free account] before you begin.

. A supported Java Development Kit (JDK). For more information, see Java support on link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Azure and Azure Stack].

. link:https://maven.apache.org/[Apache Maven], version 3.0 or later.

. If you already have a configured Service Bus queue or topic, ensure that the Service Bus namespace meets the following requirements:

.. Allows access from all networks
.. Is Premium (or higher)
.. Has an access policy with read/write access for your queue and topic

. If you don't have a configured Service Bus queue or topic, use the Azure portal to link:/azure/service-bus-messaging/service-bus-quickstart-portal[create a Service Bus queue] or link:/azure/service-bus-messaging/service-bus-quickstart-topics-subscriptions-portal[create a Service Bus topic]. Ensure that the namespace meets the requirements specified in the previous step. Also, make note of the connection string in the namespace as you need it for this tutorial's test app.

. If you don't have a Spring Boot application, create a *Maven* project with the https://start.spring.io/[Spring Initializr]. Remember to select *Maven Project* and, under *Dependencies*, add the *Web* dependency, select *8* or *11* Java version.

NOTE: Spring Boot version 2.5 or 2.6 is required to complete the steps in this article.

==== Use the Azure Service Bus JMS starter

. Locate the _pom.xml_ file in the parent directory of your app; for example: `C:\SpringBoot\servicebus\pom.xml`.

. Open the _pom.xml_ file in a text editor.

. Add the Spring Boot Azure Service Bus JMS starter to the list of `&lt;dependencies&gt;`:

+
[source,xml]
----
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>spring-cloud-azure-starter-servicebus-jms</artifactId>
      <version>4.0.0</version>
    </dependency>
----
+

. Save and close the *pom.xml* file.

==== Configure the app for your service bus

In this section, you see how to configure your app to use either a Service Bus queue or topic.

===== Use a Service Bus queue

. Locate the *application.properties* in the *resources* directory of your app; for example:
.. C:\SpringBoot\servicebus\application.properties
.. /users/example/home/servicebus/application.properties

. Open the *application.properties* file in a text editor.

. Append the following code to the end of the *application.properties* file. Replace the placeholder values with the appropriate values for your service bus, and do not put quotes around the values.

+
[source,text]
----
spring.jms.servicebus.connection-string=<ServiceBusNamespaceConnectionString>
spring.jms.servicebus.idle-timeout=<IdleTimeout>
spring.jms.servicebus.pricing-tier=<ServiceBusPricingTier>
----
+

Field descriptions

.. `spring.jms.servicebus.connection-string`: Specify the connection string you obtained in your Service Bus namespace from the Azure portal.
.. `spring.jms.servicebus.idle-timeout`: Specify the duration for idle.
.. `spring.jms.servicebus.pricing-tier`: Specify the pricing tier of your service bus. Supported values are *premium*, *standard*, and *basic*. Premium uses Java Message Service (JMS) 2.0, while standard and basic use JMS 1.0 to interact with Azure Service Bus.

. Save and close the *application.properties* file.

===== Use Service Bus topic

. Locate the *application.properties* in the *resources* directory of your app; for example:
.. C:\SpringBoot\servicebus\application.properties
.. /users/example/home/servicebus/application.properties

. Open the *application.properties* file in a text editor.

. Append the following code to the end of the *application.properties* file. Replace the placeholder values with the appropriate values for your service bus, and do not put quotes around the values.

+
[source,text]
----
spring.jms.servicebus.connection-string=<ServiceBusNamespaceConnectionString>
spring.jms.servicebus.topic-client-id=<ServiceBusSubscriptionID>
spring.jms.servicebus.idle-timeout=<IdleTimeout>
spring.jms.servicebus.pricing-tier=<ServiceBusPricingTier>
----
+

Field descriptions

.. `spring.jms.servicebus.connection-string`: Specify the connection string you obtained in your Service Bus namespace from the Azure portal.
.. `spring.jms.servicebus.topic-client-id`: Specify the JMS client ID, which is your Service Bus Subscription ID in the Azure portal.
.. `spring.jms.servicebus.idle-timeout`: Specify the duration for idle.
.. `spring.jms.servicebus.pricing-tier`: Specify the pricing tier of your service bus. Supported values are *premium*, *standard*, and *basic*. Premium uses Java Message Service (JMS) 2.0, while standard and basic use JMS 1.0 to interact with Azure Service Bus.

. Save and close the *application.properties* file.

==== Implement basic Service Bus functionality

In this section, you create the necessary Java classes for sending messages to your Service Bus queue or topic and receive messages from your corresponding queue or topic subscription.

===== Modify the main application class

. Locate the main application Java file in the package directory of your app; for example:
.. C:\SpringBoot\servicebus\src\main\java\com\wingtiptoys\servicebus\ServiceBusJmsStarterApplication.java
.. /users/example/home/servicebus/src/main/java/com/wingtiptoys/servicebus/ServiceBusJmsStarterApplication.java

. Open the main application Java file in a text editor.

. Add the following code to the file:

+
[source,java]
----
package com.wingtiptoys.servicebus;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ServiceBusJmsStarterApplication {

    public static void main(String[] args) {
        SpringApplication.run(ServiceBusJmsStarterApplication.class, args);
    }
}
----

. Save and close the file.

===== Define a test Java class

. Using a text editor, create a Java file named *User.java* in the package directory of your app.

. Define a generic user class that stores and retrieves user's name:

+
[source,java]
----
package com.wingtiptoys.servicebus;

import java.io.Serializable;

// Define a generic User class.
public class User implements Serializable {

    private static final long serialVersionUID = -295422703255886286L;

    private String name;

    public User() {
    }

    public User(String name) {
        setName(name);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
----
+

`Serializable` is implemented to use the `send` method in `JmsTemplate` in the Spring framework. Otherwise, a customized `MessageConverter` bean should be defined to serialize the content to json in text format. For more information about `MessageConverter`, see the official [Spring JMS starter project](https://spring.io/guides/gs/messaging-jms/).

. Save and close the *User.java* file.

===== Create a new class for the message send controller

. Using a text editor, create a Java file named *SendController.java* in the package directory of your app

. Add the following code to the new file:

+
[source,java]
----
package com.wingtiptoys.servicebus;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class SendController {

    private static final String DESTINATION_NAME = "<DestinationName>";

    private static final Logger logger = LoggerFactory.getLogger(SendController.class);

    @Autowired
    private JmsTemplate jmsTemplate;

    @PostMapping("/messages")
    public String postMessage(@RequestParam String message) {
        logger.info("Sending message");
        jmsTemplate.convertAndSend(DESTINATION_NAME, new User(message));
        return message;
    }
}
----
+

NOTE: Replace `<DestinationName>` with your own queue name or topic name configured in your Service Bus namespace.

. Save and close the *SendController.java*.

===== Create a class for the message receive controller

====== Receive messages from a Service Bus queue

. Use a text editor to create a Java file named *QueueReceiveController.java* in the package directory of your app

. Add the following code to the new file:

+
[source,java]
----
    package com.wingtiptoys.servicebus;

    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;
    import org.springframework.jms.annotation.JmsListener;
    import org.springframework.stereotype.Component;

    @Component
    public class QueueReceiveController {

        private static final String QUEUE_NAME = "<ServiceBusQueueName>";

        private final Logger logger = LoggerFactory.getLogger(QueueReceiveController.class);

        @JmsListener(destination = QUEUE_NAME, containerFactory = "jmsListenerContainerFactory")
        public void receiveMessage(User user) {
            logger.info("Received message: {}", user.getName());
        }
    }
----
+

NOTE: Replace `<ServiceBusQueueName>` with your own queue name configured in your Service Bus namespace.

. Save and close the *QueueReceiveController.java* file.

====== Receive messages from a Service Bus subscription

. Using a text editor, create a Java file named *TopicReceiveController.java* in the package directory of your app.

. Add the following code to the new file. Replace the `<ServiceBusTopicName>` placeholder with your own topic name configured in your Service Bus namespace. Replace the `<ServiceBusSubscriptionName>` placeholder with your own subscription name for your Service Bus topic.

+
[source,java]
----
package com.wingtiptoys.servicebus;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jms.annotation.JmsListener;
import org.springframework.stereotype.Component;

@Component
public class TopicReceiveController {

    private static final String TOPIC_NAME = "<ServiceBusTopicName>";

    private static final String SUBSCRIPTION_NAME = "<ServiceBusSubscriptionName>";

    private final Logger logger = LoggerFactory.getLogger(TopicReceiveController.class);

    @JmsListener(destination = TOPIC_NAME, containerFactory = "topicJmsListenerContainerFactory",
            subscription = SUBSCRIPTION_NAME)
    public void receiveMessage(User user) {
        logger.info("Received message: {}", user.getName());
    }
}
----

. Save and close the *TopicReceiveController.java* file.

==== Optional Service Bus Functionality

You can use a customized `MessageConverter` bean to convert between Java objects and JMS messages.

===== Set the content-type of messages

The following code example sets the `BytesMessage` content-type to `application/json`. For more information, see [Messages, payloads, and serialization](/azure/service-bus-messaging/service-bus-messages-payloads).

[source,java]
----
package com.wingtiptoys.servicebus;

import com.fasterxml.jackson.databind.ObjectWriter;
import org.apache.qpid.jms.message.JmsBytesMessage;
import org.apache.qpid.jms.provider.amqp.message.AmqpJmsMessageFacade;
import org.apache.qpid.proton.amqp.Symbol;
import org.springframework.jms.support.converter.MappingJackson2MessageConverter;
import org.springframework.jms.support.converter.MessageType;
import org.springframework.stereotype.Component;

import javax.jms.BytesMessage;
import javax.jms.JMSException;
import javax.jms.Session;
import java.io.IOException;

@Component
public class CustomMessageConverter extends MappingJackson2MessageConverter {

    private static final String TYPE_ID_PROPERTY = "_type";
    private static final Symbol CONTENT_TYPE = Symbol.valueOf("application/json");

    public CustomMessageConverter() {
        this.setTargetType(MessageType.BYTES);
        this.setTypeIdPropertyName(TYPE_ID_PROPERTY);
    }

    @Override
    protected BytesMessage mapToBytesMessage(Object object, Session session, ObjectWriter objectWriter)
        throws JMSException, IOException {
        final BytesMessage bytesMessage = super.mapToBytesMessage(object, session, objectWriter);
        JmsBytesMessage jmsBytesMessage = (JmsBytesMessage) bytesMessage;
        AmqpJmsMessageFacade facade = (AmqpJmsMessageFacade) jmsBytesMessage.getFacade();
        facade.setContentType(CONTENT_TYPE);
        return jmsBytesMessage;
    }
}
----

For more information about `MessageConverter`, see the official link:https://spring.io/guides/gs/messaging-jms/[Spring JMS guide].

===== Set session-id in JmsTemplate

Entities that have session support enabled, such as a session-enabled Service Bus queue, can only receive messages that have the `SessionId` set to a valid value. To send messages to such entities, use the `JmsTemplate.convertAndSend` method to set the string property "JMSXGroupID", which is mapped to the `SessionId` property, as shown in the following example:

[source,java]
----
@RestController
public class QueueSendController {

    private static final String QUEUE_NAME = "<DestinationName>";
    private static final Logger LOGGER = LoggerFactory.getLogger(QueueSendController.class);

    @Autowired
    private JmsTemplate jmsTemplate;

    @PostMapping("/queue")
    public String postMessage(@RequestParam String message) {

        LOGGER.info("Sending message");

        jmsTemplate.convertAndSend(QUEUE_NAME, new User(message), jmsMessage -> {
            jmsMessage.setStringProperty("JMSXGroupID", "xxxeee");
            return jmsMessage;
        });
        return message;
    }
}
----

==== Build and test your application

. Open a command prompt and change directory to the location of your _pom.xml_; for example:

+
[source,bash]
----
cd C:\SpringBoot\servicebus 
----
+

. Build your Spring Boot application with Maven and run it:

+
[source,bash]
----
mvn clean spring-boot:run
----
+

. Once your application is running, you can use _curl_ to test your application:

+
[source,bash]
----
curl -X POST localhost:8080/messages?message=hello
----


==== Clean up resources

When no longer needed, use the https://portal.azure.com/[Azure portal] to delete the resources created in this article to avoid unexpected charges.
