= Spring Cloud Azure Config Sample

This sample describes how to use spring-cloud-starter-azure-config to load configuration properties from Azure Configuration Service to Spring Environment.

For better readability of the bootstrap configuration file, in this sample, yaml format is used, but using .properties format will also work, i.e., rename bootstrap.yaml to bootstrap.properties and change the property names accordingly.

== Prerequisite
	- Java 8
	- Maven 3

== How to run

=== Prepare data

1. Create a Configuration Store if not exist.

2. Import the data file src/main/resources/data/sample-data.json into the Configuration Store created above. Keep the default options as-is when importing json data file.

=== Configure the bootstrap.yaml

Change the connection-string value with the Access Key value of the Configuration Store created above.

=== Run the application

Start the application and access http://localhost:8080 to check the returned value. Different commands for different scenarios are listed below.

1. Load properties similar with from application.properties, i.e., keys starting with /application/
+
....
$ mvn spring-boot:run
....

2. Load properties similar with from application_dev.properties, i.e., keys starting with /application_dev
+
....
$ mvn -Dspring.profiles.active=dev spring-boot:run
....

3. Load properties similar with from foo.properties, i.e., keys starting with /foo/
+
....
$ mvn -Dspring.application.name=foo spring-boot:run
....

4. Load properties similar with from foo_dev.properties, i.e., keys starting with /foo_dev/
+
....
$ mvn -Dspring.application.name=foo -Dspring.profiles.active=dev spring-boot:run
....

== Advanced usage

=== Load from multiple configuration stores
If the application needs to load configuration properties from multiple stores, following configuration sample describes how the bootstrap.yaml(or .properties) can be configured.
....
spring:
  cloud:
    azure:
      config:
        stores:
          - connection-string: {first-store-connection-string}
            prefix: {my-prefix}
            label: {my-label}
          - connection-string: {second-store-connection-string}
....
If duplicate keys exists for multiple stores, the last configuration store has the highest priority.

=== Load from multiple labels
If the application needs to load property values from multiple labels in the same configuration store, following configuration can be used:
....
spring:
  cloud:
    azure:
      config:
        stores:
          - connection-string: {first-store-connection-string}
            prefix: {my-prefix}
            label: {my-label1}, {my-label2}
....
Multiple labels can be separated with comma, if duplicate keys exists for multiple labels, the last label has highest priority.

=== Watch configuration change
Watch feature allows the application to load the latest property value from configuration store automatically, without restarting the application.

By default, the watch feature is enabled. It can be disabled with below configuration:
....
spring:
  cloud:
    azure:
      config:
        watch:
          enabled: false
....

Change the value of current used property key in the configuration store, e.g., /application/config.message, log similar with below will be printed on the console.
....
INFO 17496 --- [TaskScheduler-1] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [config.message]
....
Refresh http://localhost:8080 should get the updated value.

=== Failfast
Failfast feature decides whether throw RuntimeException or not when exception happens. By default, failfast is enabled, it can be disabled with below configuration:
....
spring:
  cloud:
    azure:
      config:
        fail-fast: false
....

=== Use Azure Managed Identity to load the connection string
A https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview[managed service identity] allows application to access https://azure.microsoft.com/en-us/services/active-directory/[Azure Active Directory] protected resource on https://azure.microsoft.com/en-us/[Azure].

In this library, managed service identity is used to retrieve the connection string of the configuration store, the connection string is not required if running the Spring Boot application on Azure with managed service identity enabled.

Follow below steps to enabled managed service identity feature:

1. https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#how-can-i-use-managed-identities-for-azure-resources[Enable managed identities service] for virtual machine or App Service, on which the application will be deployed

2. Configure bootstrap.yaml(or .properties) in the Spring Boot application as following:
....
spring:
  cloud:
    azure:
      config:
        msi-enabled: true
        stores:
          - name: {msi-enabled-store-name}
....
The configuration store name must be configured when msi-enabled is true, the connection string will be loaded automatically.