= Spring Cloud Azure Storage Starter Sample

This code sample demonstrates how to read and write files with the Spring Resource abstraction for Azure Storage using
the
link:../../spring-cloud-azure-starters/spring-cloud-azure-starter-storage[Spring Cloud Azure Storage Starter].

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-starter-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'com.microsoft.azure', name: 'spring-cloud-azure-starter-storage'
}
----

= Running the example

1. Create azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how to create credential file].
+
....
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoding with UTF-8.

2. Put auth file under `src/main/resources/`.

3. Edit the `src/main/java/com/example/WebController.java` file, replace `{containerName}` and `{blobName}` into correct value
4. Update link:src/main/resources/application.properties[application.properties]
+
....
spring.cloud.azure.credentialFilePath=[credential-file-path]
spring.cloud.azure.resourceGroup=[resource-group]
spring.cloud.azure.region=[region]

# Auto create storage account if not existed
spring.cloud.azure.storage.account=[account-name]
....

+
All azure resources will be created if missing. Alternatively, you can manually create
https://docs.microsoft.com/en-us/azure/storage/[Azure Storage].

5. Start the `StorageApplication` Spring Boot app.
+
```
$ mvn spring-boot:run
```

6. Send a POST request to update file contents:
+
```
$ curl -d 'new message' -H 'Content-Type: text/plain' localhost:8080
```
+
Verify by sending a GET request
+
```
$ curl -XGET http://localhost:8080/
```

