= Spring Cloud Azure Storage Starter Sample

This code sample demonstrates how to read and write files with the Spring Resource abstraction for Azure Storage using
the
link:../../spring-cloud-azure-starters/spring-starter-azure-storage[Spring Cloud Azure Storage Starter].Running this sample will be charged by Azure. You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

Running this sample will be charged by Azure. You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-starter-azure-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'com.microsoft.azure', name: 'spring-starter-azure-storage'
}
----

== How to run

1. Create azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how to create credential file].
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put credential file under `src/main/resources/`.

3. You can manually create https://docs.microsoft.com/en-us/azure/storage/[Azure Storage]. Or enable auto create
resources feature in link:src/main/resources/application.properties[application.properties]:
+
....
spring.cloud.azure.auto-create-resources=true

# Default region is US. Provide your own if in another region
# Example region is China, US
# spring.cloud.azure.region=[region]
# Example location is westUS, northchina
spring.cloud.azure.location=[location]
....

5. Update link:src/main/resources/application.properties[application.properties]
+
....

# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file-path]

spring.cloud.azure.resource-group=[resource-group]

spring.cloud.azure.storage.account=[account-name]

# Change into your containerName and blobName
blob=blob://containerName/blobName
....

6. Start the `StorageApplication` Spring Boot app.
+
```
$ mvn spring-boot:run
```

7. Send a POST request to update file contents:
+
```
$ curl -d 'new message' -H 'Content-Type: text/plain' localhost:8080
```
+
Verify by sending a GET request
+
```
$ curl -XGET http://localhost:8080/
```

8. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid unexpected charges.