= Spring Cloud Azure Stream Binder for Event Hub Code Sample

This code sample demonstrates how to use the Spring Cloud Stream binder for Azure Event Hub.
The sample app exposes a rest api to receive string message. Then message is sent through Azure
Event Hub to a `sink` which simply logs the message.

== How to run

1.  Create Azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how
to create credential file]
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put auth file under `src/main/resources/`.

3. Update link:src/main/resources/application.properties[application.properties] file
+
....
# Put 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credentialFilePath=[credential-file-path]

spring.cloud.azure.resourceGroup=[resource-group]
spring.cloud.azure.region=[region]

spring.cloud.azure.eventhub.namespace=[eventhub-namespace]

spring.cloud.stream.eventhub.checkpointStorageAccount=[checkpoint-storage-account]

spring.cloud.stream.bindings.input.destination=[eventhub-name]
spring.cloud.stream.bindings.input.group=[consumer-group]
spring.cloud.stream.bindings.output.destination=[eventhub-name]
....
+
All azure resources will be created if missing. Alternatively, you can manually create
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-create[Azure Event Hubs].

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5.  Send a POST request
+
....
$ curl -X POST -H "Content-Type: text/plain" -d "hello" http://localhost:8080/messages
....

6. Verify in your app's logs that a similar message was posted:
+
`New message received: hello`
