
[#migration-guide-for-6-0]
== Migration Guide for 6.0

[#migration-guide-introduction]
=== Introduction

This guide assists in the migration to *Spring Cloud Azure 6.0* from legacy Azure Spring libraries.

This guide will call libraries whose version matching `6.x` the *modern* libraries,
and those with version `4.x` the *legacy* ones.

This guide will focus the side-by-side comparisons for similar configurations between the modern and legacy libraries.

For those new to the Spring Cloud Azure 6.0 libraries, please refer to the link:index.html[Spring Cloud Azure 6.0 Reference Doc] rather than this guide.

[#migration-guide-benefits]
=== Migration Benefits

A natural question to ask when considering whether to adopt a new version or library is its benefits. As Azure has
matured and been embraced by a more diverse group of developers, we've been focused on learning the patterns and
practices to best support developer productivity and to understand the gaps that the Spring Cloud Azure libraries have.

The *Spring Cloud Azure 6.0* will benefit from the below aspects:

* Java 17 language features.
* Lots of dependencies upgrades, like Jakarta EE 9.
* Initial AOT support since Spring Framework 6.

=== Overview

This migration guide will consist following sections:

* Artifact changes: renamed / added / deleted
* Dependency changes
* Library changes

=== Artifact Changes: Renamed / Added / Deleted

In order to launch the first version to support Spring Boot 3, the Spring Cloud Azure 6.0 excluded some components that are not ready to support.

.Deleted artifact Id
[cols="<,<,<", options="header"]
|===
|Legacy Artifact ID |Modern Artifact ID |Description
|spring-cloud-azure-trace-sleuth |N/A |Deleted this artifact because Spring Cloud Sleuth does not have the latest compatible version based on Spring Boot 3, Spring Boot started to move towards Micrometer support.
|spring-cloud-azure-native-configuration |N/A |Deleted this artifact because the Spring Native support will use the new API based on Spring Framework 6, the adaptation work has not been completed.
|spring-cloud-azure-starter-data-cosmos |N/A |Deleted this artifact because the Spring Data 3 adaptation has not been completed.
|===

=== API Breaking Changes

For API breaking changes in each library, please refer to the below links for details.

- <<api-spring-cloud-azure-starter-active-directory, From spring-cloud-azure-starter-active-directory>>

=== Dependency Changes

The modern Spring Cloud Azure 6.0 libraries are based on Jakarta EE 9, which uses a new top-level jakarta package, it's required to replace EE 8’s javax top-level package.
Please make sure to correct the `javax` package to `jakarta` package in your application.

Libraries that have dependency changes include:

- <<dependency-spring-cloud-azure-starter-active-directory, spring-cloud-azure-starter-active-directory>>
- <<dependency-spring-cloud-azure-starter-active-directory-b2c, spring-cloud-azure-starter-active-directory-b2c>>
- <<dependency-spring-cloud-azure-starter-servicebus-jms, spring-cloud-azure-starter-servicebus-jms>>

=== Library Changes

Breaking changes in each library are introduced as follows.

==== spring-cloud-azure-starter-active-directory

* Please refer to <<migration-guide-introduction, introduction>> and <<migration-guide-benefits, migration benefits>> to get a whole picture of the changes in 6.0.

[#dependency-spring-cloud-azure-starter-active-directory]
===== Dependency Changes

.Dependency Changes
[cols="<,<,<", options="header"]
|===
|Legacy dependency |Modern dependency |Description
|javax.servlet:javax.servlet-api
|jakarta.servlet:jakarta.servlet-api
|Required.
|===

[#api-spring-cloud-azure-starter-active-directory]
===== API Changes

.Class mapping for spring-cloud-azure-starter-active-directory
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class

|com.azure.spring.cloud.autoconfigure.aad.AadWebSecurityConfigurerAdapter
|com.azure.spring.cloud.autoconfigure.aad.AadWebApplicationHttpSecurityConfigurer

|com.azure.spring.cloud.autoconfigure.aad.AadResourceServerWebSecurityConfigurerAdapter
|com.azure.spring.cloud.autoconfigure.aad.AadResourceServerHttpSecurityConfigurer
|===

This section lists the removed classes for spring-cloud-azure-starter-active-directory +

.Removed legacy class
* com.azure.spring.cloud.autoconfigure.aad.implementation.oauth2.AadOAuth2AuthenticatedPrincipal
* com.azure.spring.cloud.autoconfigure.aad.implementation.webapi.AadOboOAuth2AuthorizedClientProvider
* com.azure.spring.cloud.autoconfigure.aad.properties.AadAuthorizationGrantType
* com.azure.spring.cloud.autoconfigure.aad.AadJwtBearerTokenAuthenticationConverter


====== Sample Code Snippet

1.`AadWebSecurityConfigurerAdapter` sample code:

Legacy code:

[source,java]
----
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class AadWebApplicationConfig extends AadWebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        // @formatter:off
        http.authorizeRequests()
            .antMatchers("/login").permitAll()
            .anyRequest().authenticated();
        // @formatter:on
    }

    /**
     * This method is only used for AAD conditional access support and can be removed if this feature is not used.
     * @return the conditional access filter
     */
    @Override
    protected Filter conditionalAccessFilter() {
        return new AadConditionalAccessFilter();
    }
}
----

Modern code:

[source,java]
----
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class AadWebApplicationConfig {

    @Bean
    SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        // @formatter:off
        http
            .apply(AadWebApplicationHttpSecurityConfigurer.aadWebApplication())
                .conditionalAccessFilter(new AadConditionalAccessFilter())
                .and()
            .authorizeHttpRequests()
                .requestMatchers("/login").permitAll()
                .anyRequest().authenticated();
        // @formatter:on
        return http.build();
    }
}
----

2.`AadResourceServerWebSecurityConfigurerAdapter` sample code:

Legacy code:

[source,java]
----
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public static class ApiWebSecurityConfigurationAdapter extends AadResourceServerWebSecurityConfigurerAdapter {
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http.antMatcher("/api/**")
            .authorizeRequests().anyRequest().authenticated();
    }
}
----

Modern code:

[source,java]
----
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public static class ApiHttpSecurityConfigurationAdapter {
    @Bean
    public SecurityFilterChain apiFilterChain(HttpSecurity http) throws Exception {
        http
            .apply(aadResourceServer())
                .and()
            .securityMatcher("/api/**")
            .authorizeHttpRequests()
                .anyRequest().authenticated();
        return http.build();
    }
}
----

==== spring-cloud-azure-starter-active-directory-b2c

* Please refer to <<migration-guide-introduction, introduction>> and <<migration-guide-benefits, migration benefits>> to get a whole picture of the changes in 6.0.

[#dependency-spring-cloud-azure-starter-active-directory-b2c]
===== Dependency Changes

.Dependency Changes
[cols="<,<,<", options="header"]
|===
|Legacy dependency |Modern dependency |Description
|javax.servlet:javax.servlet-api
|jakarta.servlet:jakarta.servlet-api
|Required.
|===

====== Sample Code Snippet

1.`AadWebSecurityConfigurerAdapter` sample code:

Legacy code:

[source,java]
----
@EnableWebSecurity
public class AadB2cWebSecurityConfiguration extends WebSecurityConfigurerAdapter {

    private final AadB2cOidcLoginConfigurer configurer;

    public WebSecurityConfiguration(AadB2cOidcLoginConfigurer configurer) {
        this.configurer = configurer;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http.authorizeHttpRequests()
                .anyRequest().authenticated()
                .and()
            .apply(configurer);
        // @formatter:on
    }
}
----

Modern code:

[source,java]
----
@Configuration
@EnableWebSecurity
public class AadB2cWebSecurityConfiguration {

    private final AadB2cOidcLoginConfigurer configurer;

    public WebSecurityConfiguration(AadB2cOidcLoginConfigurer configurer) {
        this.configurer = configurer;
    }

    @Bean
    SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        // @formatter:off
        http.authorizeHttpRequests()
                .anyRequest().authenticated()
                .and()
            .apply(configurer);
        // @formatter:on
        return http.build();
    }
}
----

==== spring-cloud-azure-starter-servicebus-jms

* Please refer to <<migration-guide-introduction, introduction>> and <<migration-guide-benefits, migration benefits>> to get a whole picture of the changes in 6.0.

[#dependency-spring-cloud-azure-starter-servicebus-jms]
===== Dependency Changes

.Dependency Changes
[cols="<,<,<", options="header"]
|===
|Legacy dependency |Modern dependency |Description
|org.apache.geronimo.specs:geronimo-jms_2.0_spec
|jakarta.jms:jakarta.jms-api
|Since Spring Boot 3.0, `qpid-jms-client` and `pooled-jms` have changed dependency from `geronimo-jms_2.0_spec` to `jakarta.jms-api`, so we should update `imports` in our code.

|===

