
[#migration-guide-for-4-0]
== Migration Guide for 4.0

This guide assists in the migration to *Spring Cloud Azure 4.0* from legacy Azure Spring libraries.

We will call libraries whose group id and artifact id following pattern `com.azure.spring:spring-cloud-azure-\*` the **modern** libraries,
and those with pattern `com.azure.spring:azure-spring-boot-*`, `com.azure.spring:azure-spring-cloud-\*` ,
or `com.azure.spring:azure-spring-integration-*` the *legacy* ones.

This guide will focus the side-by-side comparisons for similar configurations between the modern and legacy libraries.

Familiarity with `com.azure.spring:azure-spring-boot-\*`, `com.azure.spring:azure-spring-cloud-*`
or `com.azure.spring:azure-spring-integration-*` package is assumed.

For those new to the Spring Cloud Azure 4.0 libraries, please refer to the link:index.html[Spring Cloud Azure 4.0 Reference Doc] rather than this guide.

=== Migration benefits

A natural question to ask when considering whether to adopt a new version or library is its benefits. As Azure has
matured and been embraced by a more diverse group of developers, we have been focused on learning the patterns and
practices to best support developer productivity and to understand the gaps that the Spring Cloud Azure libraries have.

There were several areas of consistent feedback expressed across the Spring Cloud Azure libraries. The most important is
that the libraries for different Azure services have not enabled the complete set of configurations. Additionally, the
inconsistency of project naming, artifact ids, versions, configurations made the learning curve steep.

To improve the development experience across Spring Cloud Azure libraries, a set of design guidelines was introduced to
ensure that Spring Cloud Azure libraries have a natural and idiomatic feel with respect to the Spring ecosystem. Further
details are available in the https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-4.0-design[design doc] for those interested.

The *Spring Cloud Azure 4.0* provides the shared experience across libraries integrating with different Spring
projects, for example Spring Boot, Spring Integration, Spring Cloud Stream, etc. The shared experience includes:

* A unified BOM to include all Spring Cloud Azure 4.0 libraries.
* A consistent naming convention for artifacts.
* A unified way to configure credential, proxy, retry, cloud environment, and transport layer settings.
* Supporting all the authenticating methods an Azure Service or Azure Service SDK supports.

=== Overview

This migration guide will be consisted of following sections:

* Naming changes for Spring Cloud Azure 4.0
* Artifact changes: renamed / added / deleted
* Dependency changes
* Authentication changes
* Configuration properties
* API breaking changes

=== Naming changes

There has never been a consistent or official name to call all the Spring Cloud Azure libraries, some of them were
called `Azure Spring Boot` and some of them `Spring on Azure` , and all these names will make developer confused. Since
4.0, we began to use the project name `Spring Cloud Azure` to represent all the Azure Spring libraries.

=== BOM

We used to ship two BOMs for our libraries, the `azure-spring-boot-bom` and `azure-spring-cloud-dependencies`, but we
combined these two BOMs into one BOM since 4.0, the `spring-cloud-azure-dependencies`. Please add an entry in the
dependencyManagement of your project to benefit from the dependency management.

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-dependencies</artifactId>
            <version>version</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

The version for spring-cloud-azure-dependencies is {project-version}.

=== Artifact changes: renamed / added / deleted

Group ids are the same for modern and legacy Spring Cloud Azure libraries, they are all `com.azure.spring`. Artifact ids
for the modern Spring Cloud Azure libraries have changed. And according to which Spring project it belongs, Spring Boot,
Spring Integration or Spring Cloud Stream, the artifact ids pattern could be `spring-cloud-azure-starter-[service]`
, `spring-integration-azure-[service]` and `spring-cloud-azure-stream-binder-[service]`. The legacy starters each has an
artifact id following the pattern `azure-spring-*`. This provides a quick and accessible means to help understand, at a
glance, whether you are using modern or legacy starters.

In the process of developing Spring Cloud Azure 4.0, we renamed some artifacts to make them follow the new naming
conventions, deleted some artifacts for its functionality could be put in a more appropriate artifact, and added some
new artifacts to better serve some scenarios.

.Mapping of legacy artifact id and modern artifact id
[cols="<,<,<", options="header"]
|===
|Legacy Artifact ID |Modern Artifact ID |Description
|azure-spring-boot-starter |spring-cloud-azure-starter |This artifact has been deleted with all functionality be merged into the new `spring-cloud-azure-starter` artifact.
|azure-spring-boot-starter-active-directory |spring-cloud-azure-starter-active-directory | Renamed the artifact.
|azure-spring-boot-starter-active-directory-b2c |spring-cloud-azure-starter-active-directory-b2c | Renamed the artifact.
|azure-spring-boot-starter-cosmos |spring-cloud-azure-starter-data-cosmos | Renamed the artifact to add `data`, indicating using Spring Data Cosmos DB.
|azure-spring-boot-starter-keyvault-certificates |N/A |Not included in this release, but will be supported in later version. 
|azure-spring-boot-starter-keyvault-secrets |spring-cloud-azure-starter-keyvault-secrets | Renamed the artifact.
|azure-spring-boot-starter-servicebus-jms |spring-cloud-azure-starter-servicebus-jms | Renamed the artifact.
|azure-spring-boot-starter-storage |spring-cloud-azure-starter-storage-blob +
spring-cloud-azure-starter-storage-file-share |The legacy artifact contains the functionality of both Storage Blob and File Share, it's been split into two separate artifacts in 4.0, spring-cloud-azure-starter-storage-blob and spring-cloud-azure-starter-storage-file-share.
|azure-spring-boot |N/A |This artifact has been deleted with all functionality be merged into the new `spring-cloud-azure-autoconfigure` artifact. 
|azure-spring-cloud-autoconfigure |N/A |This artifact has been deleted with all functionality be merged into the new `spring-cloud-azure-autoconfigure` artifact. 
|azure-spring-cloud-context |N/A |This artifact has been deleted with all functionality be merged into the new `spring-cloud-azure-autoconfigure` and `spring-cloud-azure-resourcemanager` artifacts. 
|azure-spring-cloud-messaging |spring-messaging-azure | The messaging listener annotation has been dropped.
|azure-spring-cloud-starter-cache |N/A |This artifact has been deleted, for using redis, just add spring-boot-starter-data-redis, spring-boot-starter-cache, spring-cloud-azure-resourcemanager and spring-cloud-azure-starter. Please see <<redis-support.adoc#redis-support, Redis Support>> for more information about usage.
|azure-spring-cloud-starter-eventhubs-kafka |N/A |This artifact has been deleted, for using kafka, just add spring kafka, spring-cloud-azure-resourcemanager and spring-cloud-azure-starter. Please see <<kafka-support.adoc#kafka-support, Kafka Support>> for more information about usage.
|azure-spring-cloud-starter-eventhubs |spring-cloud-azure-starter-integration-eventhubs |Renamed the artifact to add `integration`, indicating using Spring Integration with Event Hubs.
|azure-spring-cloud-starter-servicebus |spring-cloud-azure-starter-integration-servicebus |Renamed the artifact to add `integration`, indicating using Spring Integration with Service Bus.
|azure-spring-cloud-starter-storage-queue |spring-cloud-azure-starter-integration-storage-queue |Renamed the artifact to add `integration`, indicating using Spring Integration with Storage Queue.
|azure-spring-cloud-storage |N/A |This artifact has been deleted with all functionalities merged into the new `spring-cloud-azure-autoconfigure` artifact. 
|azure-spring-cloud-stream-binder-eventhubs |spring-cloud-azure-stream-binder-eventhubs |This artifact has been refactored using new redesign, mainly `spring-cloud-azure-stream-binder-eventhubs` and `spring-cloud-azure-stream-binder-eventhubs-core`.
|azure-spring-cloud-stream-binder-service-core |spring-cloud-azure-stream-binder-servicebus-core | Renamed the artifact.
|azure-spring-cloud-stream-binder-servicebus-queue |spring-cloud-azure-stream-binder-servicebus |This artifact has been deleted with all functionality be merged into the `spring-cloud-azure-stream-binder` artifact.
|azure-spring-cloud-stream-binder-servicebus-topic |spring-cloud-azure-stream-binder-servicebus |This artifact has been deleted with all functionality be merged into the `spring-cloud-azure-stream-binder` artifact.
|azure-spring-integration-core |spring-integration-azure-core | Renamed the artifact.
|azure-spring-integration-eventhubs |spring-integration-azure-eventhubs |  Rename the artifact.
|azure-spring-integration-servicebus |spring-integration-azure-servicebus |  Rename the artifact.
|azure-spring-integration-storage-queue |spring-integration-azure-storage-queue |  Rename the artifact.
|N/A |spring-cloud-azure-actuator |The newly added Spring Cloud Azure Actuator artifact. 
|N/A |spring-cloud-azure-actuator-autoconfigure |The newly added Spring Cloud Azure Actuator AutoConfigure artifact, including autoconfiguration for actuator. 
|N/A |spring-cloud-azure-autoconfigure |Newly added Spring Cloud Azure AutoConfigure artifact, including all auto-configuration for SDK clients, Spring Security support, Spring Data support and Spring Integration support.
|N/A |spring-cloud-azure-core | Newly added Spring Cloud Azure Core artifact, including all core functionality.
|N/A |spring-cloud-azure-resourcemanager |Newly added Resource Manager artifact. It's the Core library using Azure Resource Manager to read metadata and create resources. 
|N/A |spring-cloud-azure-service | Newly added Spring Cloud Azure Service artifact, including abstractions for Azure services.
|N/A |spring-cloud-azure-starter |Newly added Core Spring Cloud Azure starter, including auto-configuration support. 
|N/A |spring-cloud-azure-starter-appconfiguration |Newly added starter for using Azure App Configuration SDK client. 
|N/A |spring-cloud-azure-starter-cosmos |Newly added starter for using Azure Cosmos  SDK client.
|N/A |spring-cloud-azure-starter-eventhubs |Newly added starter for using Azure Event Hubs  SDK client. 
|N/A |spring-cloud-azure-starter-servicebus |Newly added starter for using Azure Service Bus  SDK client. 
|N/A |spring-cloud-azure-starter-storage-blob |Newly added starter for using Azure Storage Blob  SDK client. 
|N/A |spring-cloud-azure-starter-storage-file-share |Newly added starter for using Azure Storage File Share  SDK client. 
|N/A |spring-cloud-azure-starter-storage-queue |Newly added starter for using Azure Storage Queue  SDK client. 
|N/A |spring-cloud-azure-starter-stream-eventhubs |Newly added starter for using Azure Event Hubs Spring Cloud Stream Binder.
|N/A |spring-cloud-azure-starter-stream-servicebus |Newly added starter for using Azure Service Bus Spring Cloud Stream Binder 
|N/A |spring-cloud-azure-stream-binder-eventhubs-core | Newly added Spring Cloud Stream core artifact for Event Hubs.
|===

=== Dependencies changes

Some unnecessary dependencies were included in the legacy artifacts, which we have removed in the modern Spring Cloud
Azure 4.0 libraries. Please make sure add the removed dependencies manually to your project to prevent unintentionally
crash.

==== spring-cloud-azure-starter

.Removed dependencies of spring-cloud-starter
[cols="<30,<~", options="header"]
|===
|Removed dependencies |Description
|org.springframework.boot:spring-boot-starter-validation | Please include the validation starter if you want to use Hibernate Validator.
|===

==== spring-cloud-azure-starter-active-directory

.Removed dependencies of spring-cloud-azure-starter-active-directory
[cols="<30,<~", options="header"]
|===
|Removed dependencies |Description
|org.springframework.boot:spring-boot-starter-validation |Please include the validation starter if you want to use Hibernate Validator.
|===

==== spring-cloud-azure-starter-active-directory-b2c

.Removed dependencies of spring-cloud-azure-starter-active-directory-b2c
[cols="<30,<~", options="header"]
|===
|Removed dependencies |Description
|org.springframework.boot:spring-boot-starter-validation |Please include the validation starter if you want to use Hibernate Validator.
|===

=== Authentication

Spring Cloud Azure 4.0 supports all the authentication methods each Azure Service SDK supports. It allows configuring a
global token credential as well as providing the token credential at each service level. But credential is not required
to configure in Spring Cloud Azure 4.0, it can leverage the credential stored in a local developing environment, or
managed identity in Azure Services, just make sure the principal has been granted sufficient permission to access the
target Azure resources.

NOTE: When assign roles to the security principals to interact with Azure messaging services, the `Data` related roles are required to conduct messaging operations. For Azure Spring Cloud Stream Event Hubs / Service Bus Binder libraries, `Contributor` role is required when the function of auto creating resources is needed. See link:https://docs.microsoft.com/azure/role-based-access-control/built-in-roles[Azure built-in roles] for more details.

A chained credential, the https://docs.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#defaultazurecredential[DefaultAzureCredential] bean is auto-configured by default and will be used by all components if no more authentication information is specified.

IMPORTANT: There could be some `ERROR` logs be printed out while the `DefaultAzureCredential` running the chain and trying to find the first available credential. It doesn't mean the `DefaultAzureCredential` is broken or unavailable. Meanwhile, we'll keep improving this logging experience.

=== Configuration properties

==== Properties Migration 
We've created an `additional-spring-configuration-metadata.json` file to smooth the property migration when using with `spring-boot-properties-migrator`. Before doing so, let’s add the property migrator to your application

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-properties-migrator</artifactId>
    <scope>runtime</scope>
</dependency>
----
Or, if you’re using Gradle:

[source,groovy]
----
runtime("org.springframework.boot:spring-boot-properties-migrator")
----

If you run the app, it will identify the properties that are no longer managed by Spring Cloud Azure. If there is a replacement it will temporarily remap the property for you with a warning. If there isn’t a replacement, an error report will give you more information. Either way, the configuration has to be updated and the dependency removed once you have updated the configuration.

Before you move on, it is a good idea to use the search feature of your IDE to double-check that you are not using one of the properties you’ve migrated in an integration test.

IMPORTANT: We've changed many configuration properties in this change, with using the `spring-boot-properties-migrator` will help smooth your migration.


==== Global configurations

The modern `spring-cloud-azure-starter` allows developers to define properties that apply to all Azure SDKs in the
namespace `spring.cloud.azure`. It was not supported in the legacy `azure-spring-boot-starter`. The global
configurations can be divided into five categories:

.Global configurations
[cols="<30,<~", options="header"]
|===
|Prefix |Description
|*spring.cloud.azure*.client |To configure the transport clients underneath each Azure SDK.
|*spring.cloud.azure*.credential |To configure how to authenticate with Azure Active Directory.
|*spring.cloud.azure*.profile |To configure the Azure cloud environment.
|*spring.cloud.azure*.proxy |To configure the proxy options apply to all Azure SDK clients.
|*spring.cloud.azure*.retry |To configure the retry options apply to all Azure SDK clients.
|===

Check link:appendix.html[here] for a full list of configurations.

==== Each SDK configurations


===== From azure-spring-boot-starter-active-directory to spring-cloud-azure-starter-active-directory

. All configuration property names changed the prefix from `azure.activedirectory` to `spring.cloud.azure.active-directory`.
. New property `spring.cloud.azure.active-directory.enabled=true` is necessary to enable related features.

IMPORTANT: If you're using the new `spring-cloud-azure-starter-active-directory`, you have to specify the `spring.cloud.azure.active-directory.enabled` to true, even if the starter is included in classpath.

.Property mapping from azure-spring-boot-starter-active-directory to spring-cloud-azure-starter-active-directory
[cols="<30,<~", options="header"]
|===
| Legacy properties                                                                        | Morden properties
| azure.activedirectory.app-id-uri                                                         | spring.cloud.azure.active-directory.app-id-uri
| azure.activedirectory.application-type                                                   | spring.cloud.azure.active-directory.application-type
| azure.activedirectory.authorization-clients                                              | spring.cloud.azure.active-directory.authorization-clients
| azure.activedirectory.authorization-clients.AZURE_CLIENT_NAME.authorization-grant-type   | spring.cloud.azure.active-directory.authorization-clients.AZURE_CLIENT_NAME.authorization-grant-type
| azure.activedirectory.authorization-clients.AZURE_CLIENT_NAME.on-demand                  | spring.cloud.azure.active-directory.authorization-clients.AZURE_CLIENT_NAME.on-demand
| azure.activedirectory.authorization-clients.AZURE_CLIENT_NAME.scopes                     | spring.cloud.azure.active-directory.authorization-clients.AZURE_CLIENT_NAME.scopes
| azure.activedirectory.base-uri                                                           | spring.cloud.azure.active-directory.profile.environment.active-directory-endpoint
| azure.activedirectory.client-id                                                          | spring.cloud.azure.active-directory.credential.client-id
| azure.activedirectory.client-secret                                                      | spring.cloud.azure.active-directory.credential.client-secret
| azure.activedirectory.graph-membership-uri                                               | Please check the following table for more information.
| azure.activedirectory.post-logout-redirect-uri                                           | spring.cloud.azure.active-directory.post-logout-redirect-uri
| azure.activedirectory.resource-server.claim-to-authority-prefix-map                      | spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map
| azure.activedirectory.resource-server.principal-claim-name                               | spring.cloud.azure.active-directory.resource-server.principal-claim-name
| azure.activedirectory.tenant-id                                                          | spring.cloud.azure.active-directory.profile.tenant-id
| azure.activedirectory.user-group.allowed-group-ids                                       | spring.cloud.azure.active-directory.user-group.allowed-group-ids
| azure.activedirectory.user-group.allowed-group-names                                     | spring.cloud.azure.active-directory.user-group.allowed-group-names
| azure.activedirectory.user-name-attribute                                                | spring.cloud.azure.active-directory.user-name-attribute
|===

NOTE: `azure.activedirectory.graph-membership-uri` has been replaced by 2 properties: `spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint` and `spring.cloud.azure.active-directory.user-group.use-transitive-members`. The first property used to specify the host name, and the second property used to specify the url path: `v1.0/me/memberOf` or `v1.0/me/transitiveMemberOf`. Here are some examples:

.Examples of replacing `azure.activedirectory.graph-membership-uri`
[cols="<30,<~", options="header"]
|===
| Example value of azure.activedirectory.graph-membership-uri | Morden configuration
| https://graph.microsoft.com/v1.0/me/memberOf              | spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint=`https://graph.microsoft.com/`, spring.cloud.azure.active-directory.user-group.use-transitive-members=`false`
| https://graph.microsoft.com/v1.0/me/transitiveMemberOf    | spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint=`https://graph.microsoft.com/`, spring.cloud.azure.active-directory.user-group.use-transitive-members=`true`
| https://microsoftgraph.chinacloudapi.cn/v1.0/me/memberOf  | spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint=`https://microsoftgraph.chinacloudapi.cn/`,  spring.cloud.azure.active-directory.user-group.use-transitive-members=`false`
| https://microsoftgraph.chinacloudapi.cn/v1.0/me/transitiveMemberOf | spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint=`https://microsoftgraph.chinacloudapi.cn/`, spring.cloud.azure.active-directory.user-group.use-transitive-members=`true`
|===


===== From azure-spring-boot-starter-active-directory-b2c to spring-cloud-azure-starter-active-directory-b2c

. All configuration property names changed the prefix from `azure.activedirectory.b2c` to `spring.cloud.azure.active-directory.b2c`.
. New property `spring.cloud.azure.active-directory.b2c.enabled=true` is necessary to enable related features.

IMPORTANT: If you're using the new `spring-cloud-azure-starter-active-directory-b2c`, you have to specify the `spring.cloud.azure.active-directory.b2c.enabled` to true, even if the starter is included in classpath.

.Property mapping from azure-spring-boot-starter-active-directory-b2c to spring-cloud-azure-starter-active-directory-b2c
[cols="<30,<~", options="header"]
|===
| Legacy properties                                      | Morden properties
| *azure.activedirectory.b2c*.base-uri                   | *spring.cloud.azure.active-directory.b2c*.base-uri
| *azure.activedirectory.b2c*.client-id                  | *spring.cloud.azure.active-directory.b2c*.credential.client-id
| *azure.activedirectory.b2c*.client-secret              | *spring.cloud.azure.active-directory.b2c*.credential.client-secret
| *azure.activedirectory.b2c*.authorization-clients      | *spring.cloud.azure.active-directory.b2c*.authorization-clients
| *azure.activedirectory.b2c*.login-flow                 | *spring.cloud.azure.active-directory.b2c*.login-flow
| *azure.activedirectory.b2c*.tenant-id                  | *spring.cloud.azure.active-directory.b2c*.profile.tenant-id
| *azure.activedirectory.b2c*.user-flows                 | *spring.cloud.azure.active-directory.b2c*.user-flows
| *azure.activedirectory.b2c*.user-name-attribute-name    | *spring.cloud.azure.active-directory.b2c*.user-name-attribute-name
|===

NOTE: For properties like `credential.client-id`, `credential.client-secret`, `profile.tenant-id`, if `spring.cloud.azure.active-directory.b2c.PROPERTY` is not configured, `spring.cloud.azure.PROPERTY` will be used.

===== From azure-spring-boot-starter-keyvault-secrets to spring-cloud-azure-starter-keyvault-secrets

IMPORTANT: If you're using the new `spring-cloud-azure-starter-keyvault-secrets`, you have to set `spring.cloud.azure.keyvault.secret.property-source-enabled=true` to enable property source.

.Property mapping from azure-spring-boot-starter-keyvault-secrets to spring-cloud-azure-starter-keyvault-secrets
[cols="<30,<~", options="header"]
|===
| Legacy properties                      | Morden properties
| *azure.keyvault*.allow-telemetry         | Not supported anymore.
| *azure.keyvault*.case-sensitive-keys     | *spring.cloud.azure.keyvault.secret*.property-source[n].case-sensitive
| *azure.keyvault*.certificate-password    | *spring.cloud.azure.keyvault.secret*.property-source[n].credential.client-certificate-password
| *azure.keyvault*.certificate-path        | *spring.cloud.azure.keyvault.secret*.property-source[n].credential.client-certificate-path
| *azure.keyvault*.client-id               | *spring.cloud.azure.keyvault.secret*.property-source[n].credential.client-id
| *azure.keyvault*.client-key              | *spring.cloud.azure.keyvault.secret*.property-source[n].credential.client-secret
| *azure.keyvault*.enabled                 | *spring.cloud.azure.keyvault.secret*.enabled and *spring.cloud.azure.keyvault.secret*.property-source-enabled and *spring.cloud.azure.keyvault.secret*.property-source[n].enabled
| *azure.keyvault*.order                   | Not supported anymore. Use the order in property-source[n] instead.
| *azure.keyvault*.refresh-interval        | *spring.cloud.azure.keyvault.secret*.property-source[n].refresh-interval
| *azure.keyvault*.secret-keys             | *spring.cloud.azure.keyvault.secret*.property-source[n].secret-keys
| *azure.keyvault*.tenant-id               | *spring.cloud.azure.keyvault.secret*.property-source[n].profile.tenant-id
| *azure.keyvault*.uri                     | *spring.cloud.azure.keyvault.secret*.property-source[n].endpoint
| -                                      | *spring.cloud.azure.keyvault.secret*.property-source[n].service-version
| -                                      | *spring.cloud.azure.keyvault.secret*.property-source[n].client
| -                                      | *spring.cloud.azure.keyvault.secret*.property-source[n].proxy
| -                                      | *spring.cloud.azure.keyvault.secret*.property-source[n].retry
| -                                      | *spring.cloud.azure.keyvault.secret*.property-source[n].resource
|===

. All configuration property names changed the prefix from `azure.keyvault` to `spring.cloud.azure.keyvault.secret`.
. `spring.cloud.azure.keyvault.secret.enabled` is used to enable all Key Vault Secret features, include configure Key Vault secret client beans(like `SecretClient` and `SecretAsyncClient`) and add `KeyVaultPropertySource` in `ConfigurableEnvironment`.
. `spring.cloud.azure.keyvault.secret.property-source-enabled` is used to enable all `KeyVaultPropertySource`. It will take effect only when `spring.cloud.azure.keyvault.secret.enabled=true`.
. `spring.cloud.azure.keyvault.secret.property-source[n].enabled` is used to enable specific `KeyVaultPropertySource`. It will take effect only when `spring.cloud.azure.keyvault.secret.enabled=true` and `spring.cloud.azure.keyvault.secret.property-source-enabled=true`
. For Azure common properties(like `client`, `proxy`, `retry`, `credential`, `profile`) and Key Vault properties(like `endpoint`, `service-version`). If `spring.cloud.azure.keyvault.secret.property-source[n].PROPERTY_NAME` is not configured, `spring.cloud.azure.keyvault.secret.PROPERTY_NAME` will be used.
. `spring.cloud.azure.keyvault.secret.property-source[n].resource` is specific to a unique Azure resource, so if it's not configured, it will not get value from other places.

===== From azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-blob

. All configuration property names changed the prefix from `azure.storage` to `spring.cloud.azure.storage.blob`.

.Property mapping from azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-blob
[cols="<30,<~", options="header"]
|===
|Legacy properties |Morden properties
|*azure.storage*.account-name |*spring.cloud.azure.storage.blob*.account-name
|*azure.storage*.account-key |*spring.cloud.azure.storage.blob*.account-key
|*azure.storage*.blob-endpoint |*spring.cloud.azure.storage.blob*.endpoint
|===

===== From azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-file-share

All configuration property names changed the prefix from `azure.storage` to `spring.cloud.azure.storage.fileshare`.

.Property mapping from azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-file-share
[cols="<30,<~", options="header"]
|===
|Legacy properties |Morden properties
|*azure.storage*.account-name |*spring.cloud.azure.storage.fileshare*.account-name
|*azure.storage*.account-key |*spring.cloud.azure.storage.fileshare*.account-key
|*azure.storage*.file-endpoint |*spring.cloud.azure.storage.fileshare*.endpoint
|===

===== From azure-spring-cloud-starter-eventhubs to spring-cloud-azure-starter-integration-eventhubs

IMPORTANT: Configuration prefix has been changed from `spring.cloud.azure.eventhub` to `spring.cloud.azure.eventhubs.`

Changes for the child entries for this prefix, please refer the following tables:

.Property mapping from azure-spring-cloud-starter-eventhubs to spring-cloud-azure-starter-integration-eventhubs
[cols="<30,<~", options="header"]
|===
|Legacy properties | Morden properties
|*spring.cloud.azure.eventhub*.checkpoint-storage-account|*spring.cloud.azure.eventhubs.processor*.checkpoint-store.account-name
|*spring.cloud.azure.eventhub*.checkpoint-access-key|*spring.cloud.azure.eventhubs.processor*.checkpoint-store.account-key
|*spring.cloud.azure.eventhub*.checkpoint-container|*spring.cloud.azure.eventhubs.processor*.checkpoint-store.container-name
|===

For example, change from:

[source,yaml]
----
spring:
  cloud:
    azure:
      eventhub:
        connection-string: [eventhub-namespace-connection-string]
        checkpoint-storage-account: [checkpoint-storage-account]
        checkpoint-access-key: [checkpoint-access-key]
        checkpoint-container: [checkpoint-container]
----

to:

[source,yaml]
----
spring:
  cloud:
    azure:
      eventhubs:
        connection-string: [eventhub-namespace-connection-string]
        processor:
          checkpoint-store:
            container-name: [checkpoint-container]
            account-name: [checkpoint-storage-account]
            account-key: [checkpoint-access-key]
----

===== From azure-spring-cloud-starter-servicebus to spring-cloud-azure-starter-integration-servicebus

For all configuration options supported in spring-cloud-azure-starter-integration-servicebus and spring-integration-azure-servicebus libraries,
the prefix remains to be as `spring.cloud.azure.servicebus`.

.Property mapping from azure-spring-cloud-starter-servicebus to spring-cloud-azure-starter-integration-servicebus
[cols="<,<,<", options="header"]
|===
|Legacy properties suffix value |Current properties suffix value |Current type
|transport-type |client.transport-type |AmqpTransportType
|retry-options.max-retries |retry.max-attempts |Integer
|retry-options.delay |retry.delay |Duration
|retry-options.max-delay |retry.max-delay |Duration
|retry-options.try-timeout |retry.timeout |Duration
|retry-options.retry-mode |Dropped, will be configured according to retry.backoff.multiplier |NA
|===

===== From azure-spring-cloud-starter-storage-queue to spring-cloud-azure-starter-integration-storage-queue

All configuration property names changed the prefix from `spring.cloud.azure.storage` to `spring.cloud.azure.storage.queue`.

.Property mapping from azure-spring-cloud-starter-storage-queue to spring-cloud-azure-starter-integration-storage-queue
[cols="<30,<~", options="header"]
|===
|Legacy properties |Morden properties
|*spring.cloud.azure.storage*.account |*spring.cloud.azure.storage.queue*.account-name
|*spring.cloud.azure.storage*.access-key |*spring.cloud.azure.storage.queue*.account-key
|*spring.cloud.azure.storage*.resource-group |*spring.cloud.azure.storage.queue*.resource.resource-group
|===

===== From azure-spring-cloud-stream-binder-eventhubs to spring-cloud-azure-stream-binder-eventhubs

* As per prefix of `spring.cloud.azure.eventhub`, prefix is re-defined as
`spring.cloud.azure.eventhubs`

* As per prefix of `spring.cloud.stream.binders.&lt;eventhub-name&gt;.environment.spring.cloud.azure`: +
prefix change from: +
`spring.cloud.stream.binders.&lt;eventhub-name&gt;.environment.spring.cloud.azure.eventhub`
to: +
`spring.cloud.stream.binders.&lt;eventhub-name&gt;.environment.spring.cloud.azure.eventhubs`

* As per prefix of `spring.cloud.stream.eventhub`: +
prefix changed from +
`spring.cloud.stream.eventhub.bindings.&lt;binding-name&gt;.` +
to +
`spring.cloud.stream.eventhubs.bindings.&lt;binding-name&gt;.`

Changes for the child entries for following prefix, please refer the following table:

.Property mapping from azure-spring-cloud-stream-binder-eventhubs to spring-cloud-azure-stream-binder-eventhubs
[cols="<30,<~", options="header"]
|===
|Legacy properties |Modern properties
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.max-batch-size |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.batch.max-size
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.max-wait-time |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.batch.max-wait-time
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.checkpoint-mode |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.checkpoint.mode
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.checkpoint-count |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.checkpoint.count
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.checkpoint-interval |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.checkpoint.interval
|*spring.cloud.stream.eventhub.bindings.<binding-name>.consumer*.start-position |*spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer*.initial-partition-event-position
|===

NOTE: The value type of the start position configuration is also changed. It is changed from an enum of `com.azure.spring.integration.core.api.StartPosition` to a `map` of `StartPositionProperties` for each partition. Thus, the key is the partition id, and the value is of `com.azure.spring.cloud.service.eventhubs.properties.StartPositionProperties` which includes properties of offset, sequence number, enqueued date time and whether inclusive.

For example, you should change from:

[source,yaml]
----
spring:
  cloud:
    stream:
      eventhub:
        bindings:
            <binding-name>:
                consumer:
                  max-batch-size: [max-batch-size]
                  max-wait-time: [max-wait-time]
                  checkpoint-mode: [check-point-mode]
                  checkpoint-count: [checkpoint-count]
                  checkpoint-interval: [checkpoint-interval]
                  start-position: EARLIEST

----

to:

[source,yaml]
----
spring:
  cloud:
    stream:
      eventhubs:
        bindings:
            <binding-name>:
                consumer:
                  batch:
                    max-size: [max-batch-size]
                    max-wait-time: [max-wait-time]
                  checkpoint:
                    mode: [check-point-mode]
                    count: [checkpoint-count]
                    interval: [checkpoint-interval]
                  initial-partition-event-position:
                    0:
                      offset: earliest
                    1:
                      sequence-number: 100
                    2:
                      enqueued-date-time: 2022-01-12T13:32:47.650005Z
                    4:
                      inclusive: false
----

===== From azure-spring-cloud-stream-binder-servicebus-* to spring-cloud-azure-stream-binder-servicebus

IMPORTANT: Legacy binder libaries are `azure-spring-cloud-stream-binder-servicebus-queue` and `azure-spring-cloud-stream-binder-servicebus-topic`, and now they are merged into one `spring-cloud-azure-stream-binder-servicebus`.

We have merged these two libraries into one, which supports both topic and queue. And the binder type is combined as `servicebus`.

.New configuration properties of spring-cloud-azure-stream-binder-servicebus
[cols="<30,<~", options="header"]
|===
|Modern properties |description
|spring.cloud.stream.servicebus.bindings.CHANNEL.producer.entity-type |If you use the sending function, you need to set the entity-type, which can be set to topic or queue.
|===

.Property mapping from azure-spring-cloud-stream-binder-servicebus-* to spring-cloud-azure-stream-binder-servicebus
[cols="<30,<~", options="header"]
|===
|Legacy properties |Modern properties
|*spring.cloud.stream.servicebus*.queue.bindings.* |*spring.cloud.stream.servicebus.bindings*.*
|*spring.cloud.stream.servicebus*.topic.bindings.* |*spring.cloud.stream.servicebus.bindings*.*
|===

IMPORTANT: The binder type is renamed from: servicebus-queue/servicebus-topic to `servicebus`.

.Property mapping from azure-spring-cloud-stream-binder-servicebus to spring-cloud-azure-stream-binder-servicebus
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.concurrency | spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.maxConcurrentSessions/maxConcurrentCalls
|===

IMPORTANT: replaced with maxConcurrentSessions when sessionsEnabled is `true` and maxConcurrentCalls when sessionsEnabled is `false`

* If you use the Spring Cloud Stream binder for Azure Service Bus queue/topic，now your property configuration should be changed to:
[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${AZURE_SERVICEBUS_BINDER_CONNECTION_STRING}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${AZURE_SERVICEBUS_QUEUE_OR_TOPIC_NAME}
        supply-out-0:
          destination: ${AZURE_SERVICEBUS_QUEUE_OR_TOPIC_NAME}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply-out-0:
            producer:
              entity-type: queue#topic
      poller:
        fixed-delay: 1000
        initial-delay: 0

----

* If you use the Spring Cloud Stream Binder for multiple Azure Service Bus namespaces,now your property configuration should be changed to:
[source,yaml]
----
spring:
  cloud:
    stream:
      function:
        definition: consume1;supply1;consume2;supply2
      bindings:
        consume1-in-0:
          destination: ${AZURE_SERVICEBUS_TOPIC_NAME}
          group: ${AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME}
        supply1-out-0:
          destination: ${AZURE_SERVICEBUS_TOPIC_NAME}
        consume2-in-0:
          binder: servicebus-2
          destination: ${AZURE_SERVICEBUS_QUEUE_NAME}
        supply2-out-0:
          binder: servicebus-2
          destination: ${AZURE_SERVICEBUS_QUEUE_NAME}
      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: ${SERVICEBUS_BINDER_CONNECTION_STRING_1}
        servicebus-2:
          type: servicebus
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: ${SERVICEBUS_BINDER_CONNECTION_STRING_2}
      servicebus:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply1-out-0:
            producer:
              entity-type: topic
          consume2-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply2-out-0:
            producer:
              entity-type: queue
      poller:
        initial-delay: 0
        fixed-delay: 1000
----


=== API breaking changes

==== From azure-spring-boot-starter-active-directory to spring-cloud-azure-starter-active-directory

.Class mapping from azure-spring-boot-starter-active-directory to spring-cloud-azure-starter-active-directory
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.aad.webapi.AADResourceServerWebSecurityConfigurerAdapter | com.azure.spring.cloud.autoconfigure.aad.AadResourceServerWebSecurityConfigurerAdapter
|com.azure.spring.aad.webapp.AADWebSecurityConfigurerAdapter | com.azure.spring.cloud.autoconfigure.aad.AadWebSecurityConfigurerAdapter
|com.azure.spring.autoconfigure.aad.AADAppRoleStatelessAuthenticationFilter | com.azure.spring.cloud.autoconfigure.aad.filter.AadAppRoleStatelessAuthenticationFilter
|com.azure.spring.autoconfigure.aad.AADAuthenticationFilter | com.azure.spring.cloud.autoconfigure.aad.filter.filter.AadAuthenticationFilter
|com.azure.spring.autoconfigure.aad.AADAuthenticationProperties | com.azure.spring.cloud.autoconfigure.aad.properties.AadAuthenticationProperties
|com.azure.spring.autoconfigure.aad.UserPrincipal | com.azure.spring.cloud.autoconfigure.aad.filter.UserPrincipal
|===

==== From azure-spring-boot-starter-active-directory-b2c to spring-cloud-azure-starter-active-directory-b2c

.Class mapping from azure-spring-boot-starter-active-directory-b2c to spring-cloud-azure-starter-active-directory-b2c
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.autoconfigure.b2c.AADB2CJwtBearerTokenAuthenticationConverter | com.azure.spring.cloud.autoconfigure.aadb2c.AadB2cJwtBearerTokenAuthenticationConverter
|com.azure.spring.autoconfigure.b2c.AADB2COidcLoginConfigurer | com.azure.spring.cloud.autoconfigure.aadb2c.AadB2cOidcLoginConfigurer
|===


==== From azure-spring-cloud-starter-eventhubs to spring-cloud-azure-starter-integration-eventhubs

* Annotation of `@AzureMessageListeners`, `@AzureMessageListener` and `@EnableAzureMessaging` are dropped.
* Drop `EventHubOperation`, and move its `subscribe` API to class of `EventHubsProcessorContainer`.
* Rename `EventHubInboundChannelAdapter` as `EventHubsInboundChannelAdapter` to keep consistent with the service of Azure
Event Hubs, and change constructor signature as well.
* Change `CheckpointConfig` instantiation style to simple constructor instead of build style.

===== Sample code snippet

1.EventHubsInboundChannelAdapter sample code:

Legacy code:

[source,java]
----
public class Demo {
    @Bean
    public EventHubInboundChannelAdapter messageChannelAdapter(
        @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel, EventHubOperation eventhubOperation) {
        eventhubOperation.setCheckpointConfig(CheckpointConfig.builder().checkpointMode(CheckpointMode.MANUAL).build());
        EventHubInboundChannelAdapter adapter = new EventHubInboundChannelAdapter(EVENTHUB_NAME,
            eventhubOperation, CONSUMER_GROUP);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
}
----

Modern code:

[source,java]
----
public class Demo {
    @Bean
    public EventHubsInboundChannelAdapter messageChannelAdapter(
        @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel,
        EventHubsProcessorContainer processorContainer) {
        CheckpointConfig config = new CheckpointConfig(CheckpointMode.MANUAL);

        EventHubsInboundChannelAdapter adapter =
                new EventHubsInboundChannelAdapter(processorContainer, EVENTHUB_NAME,
              CONSUMER_GROUP, config);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
}
----

2.DefaultMessageHandler sample code:

Legacy code:

[source,java]
----
public class Demo {
    @Bean
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler messageSender(EventHubOperation queueOperation) {
        DefaultMessageHandler handler = new DefaultMessageHandler(EVENTHUB_NAME, queueOperation);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.error("There was an error sending the message.", ex);
            }
        });
        return handler;
    }
}
----

Modern code:

[source,java]
----
public class Demo {
    @Bean
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler messageSender(EventHubsTemplate queueOperation) {
        DefaultMessageHandler handler = new DefaultMessageHandler(EVENTHUB_NAME, queueOperation);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.error("There was an error sending the message.", ex);
            }
        });

        return handler;
    }
}
----

.Class mapping from azure-spring-cloud-starter-eventhubs to spring-cloud-azure-starter-integration-eventhubs
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.integration.core.EventHubsHeaders |com.azure.spring.eventhubs.support.EventHubsHeaders
|com.azure.spring.integration.core.AzureHeaders |com.azure.spring.messaging.AzureHeaders
|com.azure.spring.integration.core.api.reactor.Checkpointer |com.azure.spring.messaging.checkpoint.Checkpointer
|com.azure.spring.integration.core.api.CheckpointConfig |com.azure.spring.messaging.checkpoint.CheckpointConfig
|com.azure.spring.integration.core.api.CheckpointMode |com.azure.spring.messaging.checkpoint.CheckpointMode
|com.azure.spring.integration.core.api.reactor.DefaultMessageHandler |com.azure.spring.integration.handler.DefaultMessageHandler
|com.azure.spring.integration.eventhub.inbound.EventHubInboundChannelAdapter |com.azure.spring.integration.eventhubs.inbound.EventHubsInboundChannelAdapter
|com.azure.spring.integration.eventhub.api.EventHubOperation |com.azure.spring.eventhubs.core.EventHubsTemplate
|NONE |com.azure.spring.eventhubs.core.EventHubsProcessorContainer
|===

==== From azure-spring-cloud-starter-servicebus to spring-cloud-azure-starter-integration-servicebus

- Annotation of `@AzureMessageListeners`, `@AzureMessageListener` and `@EnableAzureMessaging` are dropped.
- Combine the original `ServiceBusQueueTemplate#sendAsync` and `ServiceBusTopicTemplate#sendAsync` as `ServiceBusTemplate#sendAsync`
and drop class of `ServiceBusQueueTemplate` and `ServiceBusTopicTemplate`.
- Drop RxJava and CompletableFuture support of `ServiceBusTemplate` and support Reactor instead.
- Drop interface of `ServiceBusQueueOperation` and `ServiceBusTopicOperation`.
- Drop API of `ServiceBusQueueOperation#abandon` and `ServiceBusQueueOperation#deadletter`.
- Combine the original `ServiceBusQueueTemplate#subscribe` and `ServiceBusTopicTemplate#subscribe` as `ServiceBusProcessorClient#subscribe`.
- Deprecate the interface of `SubscribeOperation`.
- Add new API of `setDefaultEntityType` for `ServiceBusTemplate`, the default entity type of ServiceBusTemplate is required when no bean of `PropertiesSupplier&lt;String, ProducerProperties&gt;` is provided
for the `ProducerProperties#entityType`.
- Drop class of `ServiceBusQueueInboundChannelAdapter` and `ServiceBusTopicInboundChannelAdapter` and combine them as `ServiceBusInboundChannelAdapter`.

===== Sample code snippet

* EventHubsInboundChannelAdapter sample code:

Legacy code:

[source,java]
----
public class Demo {
    @Bean
    public ServiceBusQueueInboundChannelAdapter queueMessageChannelAdapter(
        @Qualifier("INPUT_CHANNEL_NAME") MessageChannel inputChannel, ServiceBusQueueOperation queueOperation) {
        queueOperation.setCheckpointConfig(CheckpointConfig.builder().checkpointMode(CheckpointMode.MANUAL).build());
        ServiceBusQueueInboundChannelAdapter adapter = new ServiceBusQueueInboundChannelAdapter("QUEUE_NAME",
            queueOperation);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }

    @Bean
    public ServiceBusTopicInboundChannelAdapter topicMessageChannelAdapter(
        @Qualifier("INPUT_CHANNEL_NAME") MessageChannel inputChannel, ServiceBusTopicOperation topicOperation) {
        topicOperation.setCheckpointConfig(CheckpointConfig.builder().checkpointMode(CheckpointMode.MANUAL).build());
        ServiceBusTopicInboundChannelAdapter adapter = new ServiceBusTopicInboundChannelAdapter("TOPIC_NAME",
            topicOperation, "SUBSCRIPTION_NAME");
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }

    @Bean
    @ServiceActivator(inputChannel = "OUTPUT_CHANNEL_NAME")
    public MessageHandler queueMessageSender(ServiceBusQueueOperation queueOperation) {
        DefaultMessageHandler handler = new DefaultMessageHandler("QUEUE_NAME", queueOperation);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }
            @Override
            public void onFailure(Throwable ex) {
                LOGGER.info("There was an error sending the message.");
            }
        });
        return handler;
    }
}
----

* Modern code:

====
[source,java]
----
public class Demo {
    public ServiceBusInboundChannelAdapter queueMessageChannelAdapter(
        @Qualifier("INPUT_CHANNEL_NAME") MessageChannel inputChannel, ServiceBusProcessorContainer processorContainer) {
        ServiceBusInboundChannelAdapter adapter = new ServiceBusInboundChannelAdapter(processorContainer, "QUEUE_NAME",
            new CheckpointConfig(CheckpointMode.MANUAL));
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }

    @Bean
    @ServiceActivator(inputChannel = "OUTPUT_CHANNEL_NAME")
    public MessageHandler queueMessageSender(ServiceBusTemplate serviceBusTemplate) {
        serviceBusTemplate.setDefaultEntityType(ServiceBusEntityType.QUEUE);
        DefaultMessageHandler handler = new DefaultMessageHandler("QUEUE_NAME", serviceBusTemplate);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully for {}.", "QUEUE_NAME");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.info("There was an error sending the message.");
            }
        });

        return handler;
    }
}
----
====

==== From azure-spring-cloud-starter-storage-queue to spring-cloud-azure-starter-integration-storage-queue

.Class mapping from azure-spring-cloud-starter-storage-queue to spring-cloud-azure-starter-integration-storage-queue
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.integration.core.api.CheckpointMode |com.azure.spring.messaging.checkpoint.CheckpointMode
|com.azure.spring.integration.core.api.reactor.Checkpointer |com.azure.spring.messaging.checkpoint.Checkpointer
|com.azure.spring.integration.core.api.reactor.DefaultMessageHandler |com.azure.spring.integration.handler.DefaultMessageHandler
|com.azure.spring.integration.storage.queue.inbound.StorageQueueMessageSource |com.azure.spring.integration.storage.queue.inbound.StorageQueueMessageSource
|com.azure.spring.integration.core.AzureHeaders |com.azure.spring.messaging.AzureHeaders
|com.azure.spring.integration.storage.queue.StorageQueueOperation |com.azure.spring.storage.queue.core.StorageQueueOperation
|com.azure.spring.integration.storage.queue.StorageQueueTemplate |com.azure.spring.storage.queue.core.StorageQueueTemplate
|com.azure.spring.integration.core.DefaultMessageHandler |com.azure.spring.integration.handler.DefaultMessageHandler
|com.azure.spring.integration.servicebus.ServiceBusTemplate |com.azure.spring.servicebus.core.ServiceBusTemplate
|com.azure.spring.integration.servicebus.inbound.ServiceBusQueueInboundChannelAdapter |com.azure.spring.integration.servicebus.inbound.ServiceBusInboundChannelAdapter
|com.azure.spring.integration.servicebus.inbound.ServiceBusTopicInboundChannelAdapter |com.azure.spring.integration.servicebus.inbound.ServiceBusInboundChannelAdapter
|===

==== From azure-spring-cloud-stream-binder-eventhubs to spring-cloud-azure-stream-binder-eventhubs

.Class mapping from azure-spring-cloud-stream-binder-eventhubs to spring-cloud-azure-stream-binder-eventhubs
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.integration.core.api.Checkpointer |com.azure.spring.messaging.checkpoint.Checkpointer
|com.azure.spring.integration.core.AzureHeaders |com.azure.spring.messaging.AzureHeaders
|com.azure.spring.integration.core.EventHubHeaders |com.azure.spring.eventhubs.support.EventHubsHeaders
|===


==== From azure-spring-cloud-stream-binder-servicebus to spring-cloud-azure-stream-binder-servicebus

.Class mapping from azure-spring-cloud-stream-binder-servicebus to spring-cloud-azure-stream-binder-servicebus
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.integration.core.api.Checkpointer |com.azure.spring.messaging.checkpoint.Checkpointer
|com.azure.spring.integration.core.AzureHeaders |com.azure.spring.messaging.AzureHeaders
|com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders |com.azure.spring.servicebus.support.ServiceBusMessageHeaders
|===

==== From azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-blob

.Class mapping from azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-blob
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.autoconfigure.storage.resource.AzureStorageProtocolResolver |com.azure.spring.core.resource.AzureStorageBlobProtocolResolver
|com.azure.spring.autoconfigure.storage.resource.BlobStorageResource|com.azure.spring.core.resource.StorageBlobResource
|com.azure.spring.autoconfigure.storage.resource.AzureStorageResourcePatternResolver|com.azure.spring.core.resource.AzureStorageBlobProtocolResolver
|===

==== From azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-file-share

.Class mapping from azure-spring-boot-starter-storage to spring-cloud-azure-starter-storage-file-share
[cols="<~,<~", options="header"]
|===
|Legacy class |Modern class
|com.azure.spring.autoconfigure.storage.resource.AzureStorageProtocolResolver |com.azure.spring.core.resource.AzureStorageFileProtocolResolver
|com.azure.spring.autoconfigure.storage.resource.FileStorageResource|com.azure.spring.core.resource.StorageFileResource
|com.azure.spring.autoconfigure.storage.resource.AzureStorageResourcePatternResolver|com.azure.spring.core.resource.AzureStorageFileProtocolResolver
|===

==== From azure-spring-boot-starter-servicebus-jms to spring-cloud-azure-starter-servicebus-jms

Configuration type for `spring.jms.servicebus.idle-timeout` changed from `long`(milliseconds) to `Duration` pattern for readability.

