== Authentication

The client library supports all forms of Identity supported by the link:https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity[Azure Identity Library]. Authentication can be done through configuration for Connection Strings and Managed Identity. All other forms of Identity can be done by using the `TokenCredentialProvider`.

=== Connection String

Authentication through connection string is the simplest form to setup. You can access a stores connection strings using:

[source,azurecli,indent=0]
----
az appconfig credential list --name <name-of-your-store>
----

The connection string can be then set to the property `spring.cloud.azure.appconfiguration.stores[0].connection-string`. It is highly recommended that the connection string in the local configuration file should be a placeholder value, which should map to an Environment Variable to avoid having it added to source control.

=== Spring Cloud Azure configuration

https://learn.microsoft.com/azure/developer/java/spring-framework/configuration[Spring Cloud Azure configuration] can be used to configure the client library. The following properties can be used to configure the client library:

[source,properties,indent=0]
----
spring.cloud.azure.appconfiguration.stores[0].endpoint= <URI of your Configuration Store>
----

When only the endpoint is set, the client library will use the https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity#credential-classes[`DefaultAzureCredential`] to authenticate. The `DefaultAzureCredential` will use the following methods to authenticate:

* Environment Credential
* Managed Identity Credential
* Azure Developer CLI Credential
* IntelliJ Credential
* Azure CLI Credential
* Azure Powershell Credential

You will then need to assign the System Assigned Identity to read configurations.

[source,azurecli,indent=0]
----
az role assignment  create --role "App Configuration Data Reader" --assignee <your client id> --scope /subscriptions/<your subscription>/resourceGroups/<your stores resource group>/providers/Microsoft.AppConfiguration/configurationStores/<name of your Configuration Store>
----

Note: Only 1 authentication method can be defined per endpoint; Connection String, User Assigned Identity, Token Credential. If you need to mix and match you can have use `ConfigurationClientCustomizer` to modify stores that use a different method.
