== Production Ready

Spring Cloud Azure 4.0 supports health indicators for App Configuration, Event Hubs, Cosmos, Key Vault, Storage Blob, Storage Queue, and Storage File Share. It also provides integrations with Spring Cloud Sleuth for all HTTP-based Azure SDKs. As an example, you now can prob if storage blob is up or down via Spring Boot actuator endpoint, as well as track dependencies and latencies going from your application to Key Vault.

=== Enable Health Indicator

Add the Spring Cloud Azure Actuator Starter dependency. This dependency will also include the `spring-boot-starter-actuator`. 

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-actuator</artifactId>
</dependency>
----

.Configurable properties to enable or disable health indicators for each Azure service
[cols="<30,<70", options="header"]
|===
|Azure Service  |Property
|App Configuration |management.health.*azure-appconfiguration*.enabled
|Cosmos DB |management.health.*azure-cosmos*.enabled
|Event Hubs |management.health.*azure-eventhubs*.enabled
|Key Vault Certificate |management.health.*azure-keyvault-certificate*.enabled
|Key Vault Secret |management.health.*azure-keyvault-secret*.enabled
|Storage Blob |management.health.*azure-storage-blob*.enabled
|Storage File Share|management.health.*azure-storage-fileshare*.enabled
|Storage Queue |management.health.*azure-storage-queue*.enabled
|===

IMPORTANT: Calling the health endpoint of Azure services may cause extra charges. For example, calling `http://HOST_NAME:{port}/actuator/health/cosmos` to get the Cosmos DB health info, it will calculate https://docs.microsoft.com/azure/cosmos-db/request-units[RUs].

=== Enable Sleuth

Add the Spring Cloud Azure Trace Sleuth dependency when you want to trace Azure SDK activities with using Spring Cloud Sleuth.

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-trace-sleuth</artifactId>
</dependency>
----

NOTE: Only HTTP-based Azure SDK clients are supported now, for example, Eventhub and ServiceBus with AMQP transport are currently not supported, we recommend using https://docs.microsoft.com/azure/azure-monitor/app/app-insights-overview[Azure Application Insights] for such requirements.


