== Production Ready

We’ve added health indicators for App Configuration, Event Hubs, Cosmos, Key Vault, Storage Blob, Storage Queue, Storage File, as well as Spring Cloud Sleuth support for all HTTP-based Azure SDKs. As an example, you now can prob if storage blob is up or down via Spring Boot actuator endpoint, as well as track dependencies and latencies going from your application to Key Vault.

=== Enable Health Indicator

Add the Spring Cloud Azure Actuator Starter dependency. This dependency will also include the `spring-boot-starter-actuator`. 

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-actuator</artifactId>
</dependency>
----

Below properties could be used to enable or disable health indicators for each Azure services.
|===
|Azure Service  |Propropety
|App Configuration |management.health.azure-appconfiguration.enabled
|Cosmos DB |management.health.azure-cosmos.enabled
|Event Hubs |management.health.azure-eventhubs.enabled
|Key Vault |management.health.azure-keyvault.enabled
|Storage|management.health.azure-storage.enabled
|===

NOTE: Calling the health endpoint of Azure servcies could cause extra charge. For example, calling `http://{hostname}:{port}/actuator/health/cosmos` to get the Cosmos DB health info, it will calculate https://docs.microsoft.com/azure/cosmos-db/request-units[RUs].

=== Enable Sleuth

Add the Spring Cloud Azure Trace Sleuth dependency when you want to trace Azure SDK activities with using Spring Cloud Sleuth.

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-trace-sleuth</artifactId>
</dependency>
----

NOTE: Only HTTP-based Azure SDK clients are supported now.


