== Configuration Refresh

You are able to dynamically update configurations to there latest values from your Azure App Configuration store(s), without restarting the application.

To enable refresh, monitoring needs to be enabled and a watch key with an optional label needs to be set.

[,properties,indent=0]
----
spring.cloud.azure.appconfiguration.stores[0].monitoring.enabled=true
spring.cloud.azure.appconfiguration.stores[0].monitoring.triggers[0].key=[my-watched-key]
spring.cloud.azure.appconfiguration.stores[0].monitoring.triggers[0].label=[my-watched-label]
----

Changing a property key in your configuration store, e.g. `/application/config.message`, will create a log similar to the one below in the logs.

[,console,indent=0]
----
INFO 17496 --- [TaskScheduler-1] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [config.message]
----

The application will refresh all `@Bean`++'++s in the refresh scope. By default, `@ConfiugrationProperties` annotated beans will be included in this scope.

=== Pull Based Refresh

The library supports the ability to periodically check on a refresh interval for change made to the monitoring triggers. By default the refresh-interval is set to 30 seconds. Once the refresh interval has passed all triggers will be checked in the given store for changes. Any update to the value will cause a refresh to trigger. Because the libraries integrate with the Spring refresh system any refresh will reload configurations from all stores.

==== Automated

When using the `azure-spring-cloud-appconfiguration-config-web` library, the application will check for refresh whenever a servlet request occurs, specifically `ServletRequestHandledEvent`. The most common way this event is sent is by connections to endpoints in a `@RestController`.

==== Manuel

In application that just use `azure-spring-cloud-appconfiguration-config`, such as console applications refresh can be manually triggered by calling `AppConfigurationRefresh`'s refreshConfiguration method. `AppConfigurationRefresh` is a `@Bean` that can be injected into any `@Component`.

Also, because the library uses Spring's configuration system triggering a refresh of that will also cause a refresh of your Azure App Configuration configurations.

=== Push Based Refresh

The `azure-spring-cloud-appconfiguration-config-web` library can be setup to receive notifications to refresh from your Azure App Configuration store. This is done via an Azure Event Grid Web Hook, that can be configured to send notifications of given keys being modified. By adding the Spring Actuator library as a dependency you can expose App Configuration's refresh endpoint(s). There are two different endpoints `appconfiguration-refresh` and `appconfiguration-refresh-bus` these endpoints work sort of similarly to there counterparts `refresh` and `refresh-bus`, but not exactly.

`appconfiguration-refresh` expires the refresh interval, so the remaining refresh interval isn't waited on before the next refresh check. `appconfiguration-refresh-bus` will send a notification to a connected messing service, such as Azure Service Bus to notify all instances of an application to refresh. In both cases it doesn't completely expire the refresh interval, but almost does by a random amount. This makes sure not every instance of your application doesn't try to refresh at the same time.

[,properties,indent=0]
----
management.endpoints.web.exposure.include= appconfiguration-refresh, appconfiguration-refresh-bus
----

In addition to exposing the refresh endpoints a required query parameter has been added for security. No token name or value is set by default, but setting one is required in order to use the endpoints.

[,properties,indent=0]
----
spring.cloud.appconfiguration.stores[0].monitoring.push-notification.primary-token.name=[primary-token-name]
spring.cloud.appconfiguration.stores[0].monitoring.push-notification.primary-token.secret=[primary-token-secret]
spring.cloud.appconfiguration.stores[0].monitoring.push-notification.secondary-token.name=[secondary-token-name]
spring.cloud.appconfiguration.stores[0].monitoring.push-notification.secondary-token.secret=[secondary-token-secret]
----

==== Setting Up Web Hooks

To setup a Web Hok open your Azure App Configuration store and select the events tab. Select "+ Event Subscription". Set the name of your Event and select the Endpoint type of Web Hook. Selecting Web Hook will cause an Endpoint option to appear, Select "Select an endpoint". Your endpoint will look like the following:

----
https://www.myaplication.com/actuator/appconfiguration-refresh?myTokenName=mySecret
----

In order to "Confirm Selection" will send a setup notification to the given URI and it expects a response. If no response is returned it will fail. The `azure-spring-cloud-appconfiguration-web` library if setup for endpoints will return the correct response if the Azure App Configuration store is configured for the application. This confirmation can be sent in other ways see https://docs.microsoft.com/azure/event-grid/webhook-event-delivery[Event Grid Web Hook Delivery] for more information on Web Hook validation.

NOTE: This validation only happens on the creation/modification of the endpoint.

It is highly recommended that filters are sutp as otherwise a refresh will be triggered after every key creation and modification.