
==== Remove credentials from Spring Kafka applications

===== Overview

You can use the Event Hubs Kafka endpoint in your Spring Kafka application. From Spring Cloud Azure 4.3.0, you can configure and run your application without credentials.

This article is a migration guide for removing credentials from Spring Kafka applications.

===== Update dependencies

====== Add spring-cloud-azure-dependencies BOM

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>spring-cloud-azure-dependencies</artifactId>
      <version>${version.spring.cloud.azure}</version><!--	The version for spring-cloud-azure-dependencies is 4.3.0+.-->
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

====== Add Spring Cloud Azure starter

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter</artifactId>
  </dependency>
</dependencies>
----

===== Update configuration

====== If using Spring Kafka

Remove the following options if you have customzied values::

- `spring.kafka.security.protocol`
- `spring.kafka.security.properties.sasl.mechanism`
- `spring.kafka.security.properties.sasl.jaas.config`

For example, the final configuration should look like the following:

[source,properties]
----
spring.kafka.bootstrap-servers=<NAMESPACENAME>.servicebus.windows.net:9093
----

====== If using Spring Cloud Stream Binder Kafka

Remove the following options if you have customzied values::

- `spring.kafka.security.protocol`
- `spring.kafka.security.properties.sasl.mechanism`
- `spring.kafka.security.properties.sasl.jaas.config`
- `spring.cloud.stream.kafka.configuration.security.protocol`
- `spring.cloud.stream.kafka.configuration.sasl.mechanism`
- `spring.cloud.stream.kafka.configuration.sasl.jaas.config`

Add the following option:

- `spring.cloud.stream.binders.kafka.environment.spring.main.sources`

For example, the final configuration should look like the following:

[source,properties]
----
spring.cloud.stream.kafka.binder.brokers=<NAMESPACENAME>.servicebus.windows.net:9093
spring.cloud.stream.binders.kafka.environment.spring.main.sources=com.azure.spring.cloud.autoconfigure.kafka.AzureKafkaSpringCloudStreamConfiguration
----


NOTE: That `spring.cloud.stream.binders.kafka.environment.spring.main.sources` option is used to specify the additional configuraion of `KafkaBinderConfigurationPropertiesBeanPostProcessor` specifying the OAuth security parameters for the particular binder.

===== Run locally

====== Grant permissions

With Azure AD, you can use Azure role-based access control (Azure RBAC) to grant permissions to a security principal, which may be a user, or an application service principal.

As Azure Event Hubs support Azure role-based access control, you need to assign the corresponding data plane roles to the security principal you use when you want to read or write data to it. In this document, we will use Azure CLI credential to connect to Azure Event Hubs, you need to assign roles to Azure CLI account.

For details about assigning access roles, see link:https://docs.microsoft.com/azure/event-hubs/authorize-access-azure-active-directory[Authorize access to Event Hubs resources using Azure Active Directory].

NOTE: For data access, the data plane access role should be set, for example: Azure Event Hubs Data Sender and Azure Event Hubs Data Receiver.

====== Sign in to your Azure account

To use the Azure CLI credential, you should do the following:

Login via Azure CLI before running:

[source,shell script]
----
az login
----

Build and test your application after login.

NOTE: If you want to use other local environment credentials, for example with  IntelliJ, see link:index.html#authentication[Authentication] for details.

===== Deploy to Azure Spring Apps

As above, we describe how to run the application locally, however, in production, we can deploy the application to Azure hosting environments like `Azure Spring Apps`.

Azure Spring Apps is an Azure host with Managed Identity enabled and the application can be deployed to it for production.

====== Create and configure managed identity

To connect with managed identities, you should enable the managed identity on Azure Spring Apps and grant the access permissions.

For information on how to enable managed identity, see link:create-and-configure-managed-identity.html[How to create and configure a managed identity on Azure hosting services].

For information on how to assign roles to the managed identity, refer to link:https://docs.microsoft.com/azure/role-based-access-control/role-assignments-portal[Assign Azure roles using the Azure portal].

NOTE: For data access, the data plane access role should be set, for example: Azure Event Hubs Data Sender and Azure Event Hubs Data Receiver.

====== Deploy to Azure Spring Apps

Refer to link:deploy-applications-to-azure-hosting-environments.html[Deploy application to Azure hosting services].
