== Resource Manager

Azure Resource Manager (ARM) is the deployment and management service for Azure. It provides a management layer that enables you to create, update, and delete resources in your Azure account. Spring Cloud Azure Resourcemanger can help provision resources or retrieve resource metadata. 

=== Dependency Setup

[source,xml]
----
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-resourcemanager</artifactId>
</dependency>
----

=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-resourcemanager
[cols="2*", options="header"]
|===
|Property |Description
|*spring.cloud.azure.resource-manager*.enabled |Whether the Resource Manager is enabled. Default is true.
|*spring.cloud.azure.credential*.client-id |Client id to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.client-secret |Client secret to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.client-certificate-path |Path of a PEM certificate file to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.client-certificate-password |Password of the certificate file.
|*spring.cloud.azure.credential*.username |Username to use when performing username/password authentication with Azure.
|*spring.cloud.azure.credential*.password |Password to use when performing username/password authentication.
|*spring.cloud.azure.credential*.managed-identity-enabled |Whether to enable managed identity.
|*spring.cloud.azure.profile*.cloud-type |Name of the Azure cloud to connect to.
|*spring.cloud.azure.profile*.environment.active-directory-endpoint |The Azure Active Directory endpoint to connect to for authentication.
|*spring.cloud.azure.profile*.subscription-id |Subscription id to use when connecting to Azure resources.
|*spring.cloud.azure.profile*.tenant-id |Tenant id for Azure resources.
|===

=== Basic Usage

Spring Cloud Azure Resourcemanger can work together with specific Spring Cloud Azure starters to retrieve connection information, such as connection strings, to connect to Azure services. It can also together with `spring-cloud-azure-starter` and third-party libraries to retrieve metadata like username/password, to complete authentication, such as: <<Kafka Support>>, <<Redis Support>>.

=== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}[azure-spring-boot-samples] for more details.

