== Resource Handling

Connect to Azure Storage using Spring Resource abstraction and Azure Storage libraries.

|===
|Starter | Service | Description
|spring-cloud-azure-starter-storage-blob|Azure Blobs|Allows unstructured data to be stored and accessed at a massive scale in block blobs.
|spring-cloud-azure-starter-storage-file-share|Azure Files|Offers fully managed cloud file shares that you can access from anywhere via the industry standard Server Message Block (SMB) protocol.
|===

=== Dependency Setup


[source,xml]
----
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-storage-blob</artifactId>
</dependency>

<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-storage-file-share</artifactId>
</dependency>

----

=== Configuration

This `spring-cloud-azure-starter-storage-blob` provides the following properties:

|===
|Name | Default | Description
|spring.cloud.azure.storage.blob.enabled | `true` | Whether an Azure Blob Storage Service is enabled
|spring.cloud.azure.storage.blob.endpoint |  | Uri to connect Azure Blob Storage
|spring.cloud.azure.storage.blob.account-key |  | Privatekey to connect Azure Blob Storage
|spring.cloud.azure.storage.blob.account-name |  | Azure Storage Account Name
|===

This `spring-cloud-azure-starter-storage-file-share` provides the following properties:

|===
|Name | Default | Description
|spring.cloud.azure.storage.fileshare.enabled | `true` | Whether Azure File Storage Service is enabled
|spring.cloud.azure.storage.fileshare.endpoint |  | Uri to connect Azure File Storage
|spring.cloud.azure.storage.fileshare.account-key |  | Privatekey to connect Azure File Storage
|spring.cloud.azure.storage.fileshare.account-name |  | Azure Storage Account Name
|===


=== Basic Usage

Provide the properties below in your configuration file.

[source,yaml]
----
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${STORAGE-ACCOUNT-NAME}
          account-key: ${STORAGE-ACCOUNT-PRIVATE-KEY}
          endpoint: ${STORAGE-BLOB-ENDPOINT}
        fileshare:
          account-name: ${STORAGE-ACCOUNT-NAME}
          account-key: ${STORAGE-ACCOUNT-PRIVATE-KEY}
          endpoint:  ${STORAGE-FILESHARE-ENDPOINT}
----


=== Samples

A link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/storage/spring-cloud-azure-starter-storage-blob/storage-blob-sample[storage-blob-sample] and link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/storage/spring-cloud-azure-starter-storage-file-share/storage-file-sample[storage-file-sample] are provided to show how to use the `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-storage-file-share`.
