== Resource Handling

The project provides  Spring Boot Starters `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-storage-file-share`  to auto-configure Azure Storage Blob and Azure Storage File Share in your Spring projects. It implements Spring Resource abstraction for Azure Storage service which allows you to interact with Azure storage Blob and File Share using Spring programming model.


.Azure Storage related libraries.
[cols="2,1,5", options="header"]
|===
|Starter 
|Service 
|Description

|spring-cloud-azure-starter-storage-blob
|Azure Blobs
|Allows unstructured data to be stored and accessed at a massive scale in block blobs.

|spring-cloud-azure-starter-storage-file-share
|Azure Files
|Offers fully managed cloud file shares that you can access from anywhere via the industry standard Server Message Block (SMB) protocol.
|===

=== Dependency Setup

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>spring-cloud-azure-starter-storage-blob</artifactId> # <1>
    </dependency>
    <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>spring-cloud-azure-starter-storage-file-share</artifactId> # <2>
    </dependency>
</dependencies>
----
<1> Only required when you're using Azure Storage Blob.
<2> Only required when you're using Azure Storage File Share.

=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-starter-storage-blob
[cols="3,1,5", options="header"]
|===
|Property  |Default | Description

|*spring.cloud.azure.storage.blob*.enabled
|true
|Whether an Azure Blob Storage Service is enabled

|*spring.cloud.azure.storage.blob*.endpoint
|  
|Uri to connect Azure Blob Storage

|*spring.cloud.azure.storage.blob*.account-key
|  
|Private key to connect Azure Blob Storage

|*spring.cloud.azure.storage.blob*.account-name
|  
|Azure Storage Account Name
|===

.Configurable properties of spring-cloud-azure-starter-storage-file-share
[cols="3,1,5", options="header"]
|===
|Property  | Default | Description

|*spring.cloud.azure.storage.fileshare*.enabled
|true 
|Whether Azure File Storage Service is enabled

|*spring.cloud.azure.storage.fileshare*.endpoint
|  
|Uri to connect Azure File Storage

|*spring.cloud.azure.storage.fileshare*.account-key
|  
|Private key to connect Azure File Storage

|*spring.cloud.azure.storage.fileshare*.account-name
|  
|Azure Storage Account Name
|===


=== Basic Usage

Please use this link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/storage[sample] as a reference for how to use Azure Spring Boot Storage Starter in your projects.


Provide the properties below in your configuration file.

[source,yaml]
----
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${STORAGE_ACCOUNT_NAME}
          account-key: ${STORAGE_ACCOUNT_PRIVATE_KEY}
          endpoint: ${STORAGE_BLOB_ENDPOINT}
        fileshare:
          account-name: ${STORAGE_ACCOUNT_NAME}
          account-key: ${STORAGE_ACCOUNT_PRIVATE_KEY}
          endpoint:  ${STORAGE_FILESHARE_ENDPOINT}
----

==== Autowire a resource
You can use the annotation of `@Value("azure-blob://[your-container-name]/[your-blob-name]")` to autowire a blob Resource.
----
@Value("azure-blob://[your-container-name]/[your-blob-name]")
private Resource storageResource;
----

You can use the annotation of @Value("azure-file://[your-fileshare-name]/[your-file-name]") to autowire a file Resource.

----
@Value("azure-file://[your-fileshare-name]/[your-file-name]")
private Resource storageResource;
----

==== Read and write to a resource

You can read a resource from Azure Blob storage with `getInputStream()` method.

----
 this.storageResource.getInputStream();
----

You can write to a resource in Azure Blob storage by casting the Spring `Resource` to `WritableResource`.

----
 ((WritableResource) this.azureBlobResource).getOutputStream();
----

==== Other operations 
The Spring Resource abstraction for Azure Storage also supports link:https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#resources[other operations] defined in Spring's `Resource` and `WritableResource` interface. 

==== Autowire the BlobServiceClientBuilder
You can autowire the `BlobServiceClientBuilder` and create a client using:
----
@Autowire
private BlobServiceClientBuilder blobServiceClientBuilder;

private final BlobServiceAsyncClient blobServiceAsyncClient = blobServiceClientBuilder.buildAsyncClient();

----

==== Search for resources
You can use implementation class `AzureStorageBlobProtocolResolver` of `ResourcePatternResolver` to search `blob` resource, and `AzureStorageFileProtocolResolver` of `ResourcePatternResolver` to search `file` resource

* Pattern search, the **searchPattern** should start with `azure-blob://` or `azure-file://`. Such as `azure-blob://*/*`, it means list all blobs in all containers; `azure-blob://demo-container/**`, it means list all blobs in the demo-container container, including any sub-folder.
* Location search, the **searchLocation** should start with `azure-blob://` or `azure-file://`, the remaining file path should exist, otherwise an exception will be thrown.

----
@Autowire
 ResourcePatternResolver storageResourcePatternResolver;

Resource[] resources = storageResourcePatternResolver.getResources(searchPattern);
Resource resource = storageResourcePatternResolver.getResource(searchLocation);
----

#### Multipart upload
Files larger than 4 MiB will be uploaded to Azure Storage in parallel.



=== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/storage[azure-spring-boot-samples] for more details.
