== Resource Manager

Connect to Azure Resources for All Azure SDKs service, which Spring Cloud used.
Construct `TokenCredential` by using various credential information, and then construct `AzureResourceManager` to help Azure SDKs Client to authenticate and authorize.

=== Dependency Setup

[source,xml]
----
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-resourcemanager</artifactId>
</dependency>
----

=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-resourcemanager
[cols="2*", options="header"]
|===
|Property |Description
|*spring.cloud.azure.resource-manager*.enabled |Whether the Resource Manager is enabled. Default is true.
|*spring.cloud.azure.credential*.client-certificate-password |Password of the certificate file.
|*spring.cloud.azure.credential*.client-certificate-path |Path of a PEM certificate file to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.client-id |Client id to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.client-secret |Client secret to use when performing service principal authentication with Azure.
|*spring.cloud.azure.credential*.managed-identity-client-id |Client id to use when using managed identity to authenticate with Azure.
|*spring.cloud.azure.credential*.username |Username to use when performing username/password authentication with Azure.
|*spring.cloud.azure.credential*.password |Password to use when performing username/password authentication.
|*spring.cloud.azure.profile*.cloud |Name of the Azure cloud to connect to.
|*spring.cloud.azure.profile*.environment.active-directory-endpoint |The Azure Active Directory endpoint to connect to for authentication.
|*spring.cloud.azure.profile*.subscription-id |Subscription id to use when connecting to Azure resources.
|*spring.cloud.azure.profile*.tenant-id |Tenant id for Azure resources.
|===

=== Basic Usage

Azure Resource Manger helps the Azure SDK client to complete authentication and authorization. It can be integrated into a specific Spring Cloud Azure Starter and work together, or it can be used with Spring Cloud Azure auto-configuration modules and third-party libraries to complete authentication, such as: <<Kafka Support>>, <<Redis Support>>.

=== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0[azure-spring-boot-samples] for more details.

