

== Secret Management

spring-cloud-azure-starter-keyvault-secrets adds Azure Key Vault as one of the Spring PropertySource, so secrets stored in Azure Key Vault could be easily used and conveniently accessed like other externalized configuration property, e.g. properties in files.

=== Dependency Setup

[source,xml]
----
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
</dependency>
----

=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-starter-keyvault-secrets
[cols="2*", options="header"]
|===
|Property |Description
| *spring.cloud.azure.keyvault.secret*.endpoint                                            | Key Vault uri
| *spring.cloud.azure.keyvault.secret*.service-version                                     | Service version
| *spring.cloud.azure.keyvault.secret*.property-source-enabled                             | Enable this property source
| *spring.cloud.azure.keyvault.secret*.property-sources                                    | Multiple property source
| *spring.cloud.azure.keyvault.secret*.property-sources[].name                             | Name of this property source
| *spring.cloud.azure.keyvault.secret*.property-sources[].endpoint                         | Key Vault uri
| *spring.cloud.azure.keyvault.secret*.property-sources[].service-version                  | Service version
| *spring.cloud.azure.keyvault.secret*.property-sources[].case-sensitive                   | Whether the secret name is case-sensitive
| *spring.cloud.azure.keyvault.secret*.property-sources[].secret-keys                      | The supported secret names. If not configured, it will retrieve all secret names.
| *spring.cloud.azure.keyvault.secret*.property-sources[].refresh-interval                 | Refresh interval
|===

=== Basic Usage

==== One Property Source

===== Property Configuration
If you want to authenticate by `client-id` and `client-secret`, the following properties are required:

[source,yml]
----
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - name: key-vault
              endpoint: ${ENDPOINT}
----

If your application is authenticated by other methods like Managed Identity or Azure CLI, properties like `tenant-id`, `client-id`, `client-secret` are not necessary. But if these properties are configured, then these properties have higher priority. Please refer to link:authentication.html[Authentication section] to get more information.

===== Java Code

[source,java]
----
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {

    @Value("${sampleProperty}")
    private String sampleProperty;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @Override
    public void run(String... args) {
        System.out.println("sampleProperty: " + sampleProperty);
    }
}
----

==== Multiple Property Source

===== Property Configuration

[source,yml]
----
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
          -
            name: key-vault-1
            endpoint: ${ENDPOINT_1}
            profile:
              tenant-id: ${AZURE_TENANT_ID_1}
            credential:
              client-id: ${AZURE_CLIENT_ID_1}
              client-secret: ${AZURE_CLIENT_SECRET_1}
          -
            name: key-vault-2
            endpoint: ${ENDPOINT_2}
            profile:
              tenant-id: ${AZURE_TENANT_ID_2}
            credential:
              client-id: ${AZURE_CLIENT_ID_2}
              client-secret: ${AZURE_CLIENT_SECRET_2}

----
Same as above, properties like `tenant-id`, `client-id`, `client-secret` are not necessary if authenticate by other methods.

===== Java Code

[source,java]
----
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {

    @Value("${sampleProperty1}")
    private String sampleProperty1;
    @Value("${sampleProperty2}")
    private String sampleProperty2;
    @Value("${samplePropertyInMultipleKeyVault}")
    private String samplePropertyInMultipleKeyVault;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    public void run(String[] args) {
        System.out.println("sampleProperty1: " + sampleProperty1);
        System.out.println("sampleProperty2: " + sampleProperty2);
        System.out.println("samplePropertyInMultipleKeyVault: " + samplePropertyInMultipleKeyVault);
    }

}
----

=== Advanced Usage

==== Special Characters in Property Name
Key Vault secret name only support characters in `[0-9a-zA-Z-]`. Refs: link:https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#vault-name-and-object-name[Vault-name and Object-name]. If your property name contains other characters, you can use these workarounds:

===== Use `-` Instead of `.` In Secret Name

`.` is not supported in secret name. If your application have property name which contain `.`, like `spring.datasource.url`, just replace `.` to `-` when save secret in Azure Key Vault. For example: Save `spring-datasource-url` in Azure Key Vault. In your application, you can still use `spring.datasource.url` to retrieve property value.

NOTE: This method can not satisfy requirement like `spring.datasource-url`. When you save `spring-datasource-url` in Key Vault, only `spring.datasource.url` and `spring-datasource-url` is supported to retrieve property value, `spring.datasource-url` is not supported. To handle this case, please refer to the following section: Use property placeholders.

===== Use Property Placeholders

For example: setting this property in your application.properties:
[source,properties]
----
property.with.special.character__=${propertyWithoutSpecialCharacter}
----

The application will get  `propertyWithoutSpecialCharacter` key name and assign its value to `property.with.special.character__`.

==== Case Sensitive

To enable case-sensitive mode, you can set the following property:

[source,properties]
----
spring.cloud.azure.keyvault.secret.property-sources[].case-sensitive=true
----


=== Samples


Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}/keyvault/spring-cloud-azure-starter-keyvault-secrets[spring-cloud-azure-starter-keyvault-secrets samples] for more details.

