

== Secret Management

spring-cloud-azure-starter-keyvault-secrets adds Azure Key Vault as one of the Spring PropertySource, so secrets stored in Azure Key Vault could be easily used and conveniently accessed like other externalized configuration property, e.g. properties in files.

=== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
</dependency>
----

=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-starter-keyvault-secrets
[cols="2*", options="header"]
|===
|Property |Description
| *spring.cloud.azure.keyvault.secret*.endpoint                                            | Key Vault uri
| *spring.cloud.azure.keyvault.secret*.service-version                                     | Service version
| *spring.cloud.azure.keyvault.secret*.property-source-enabled                             | Enable this property source
| *spring.cloud.azure.keyvault.secret*.property-sources                                    | Multiple property source
| *spring.cloud.azure.keyvault.secret*.property-sources[].name                             | Name of this property source
| *spring.cloud.azure.keyvault.secret*.property-sources[].endpoint                         | Key Vault uri
| *spring.cloud.azure.keyvault.secret*.property-sources[].service-version                  | Service version
| *spring.cloud.azure.keyvault.secret*.property-sources[].case-sensitive                   | Whether the secret name is case-sensitive
| *spring.cloud.azure.keyvault.secret*.property-sources[].secret-keys                      | The supported secret names. If not configured, it will retrieve all secret names.
| *spring.cloud.azure.keyvault.secret*.property-sources[].refresh-interval                 | Refresh interval
|===

=== Basic Usage

==== One property source

===== Property configuration

[source,yml]
----
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${AZURE_KEYVAULT_ENDPOINT}
----

===== Java code

[source,java]
----
@SpringBootApplication
public class KeyVaultSample implements CommandLineRunner {

    @Value("${your-property-name}")
    private String mySecretProperty;

    public static void main(String[] args) {
        SpringApplication.run(KeyVaultSample.class, args);
    }

    @Override
    public void run(String... args) {
        System.out.println("property your-property-name value is: " + mySecretProperty);
    }
}
----

==== Multiple property source

===== Property configuration

[source,yml]
----
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            -
              name: key-vault-1
              endpoint: ${ENDPOINT_1}
              profile:
                tenant-id: ${AZURE_TENANT_ID_1}
              credential:
                client-id: ${AZURE_CLIENT_ID_1}
                client-secret: ${AZURE_CLIENT_SECRET_1}
            -
              name: key-vault-2
              endpoint: ${ENDPOINT_2}
              profile:
                tenant-id: ${AZURE_TENANT_ID_2}
              credential:
                client-id: ${AZURE_CLIENT_ID_2}
                client-secret: ${AZURE_CLIENT_SECRET_2}

----

===== Java code

[source,java]
----
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {

    @Value("${secret-name-in-key-vault-1}")
    private String secretNameInKeyVault1;
    @Value("${secret-name-in-key-vault-2}")
    private String secretNameInKeyVault2;
    @Value("${secret-name-in-key-vault-both}")
    private String secretNameInKeyVaultBoth;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    public void run(String[] args) {
        System.out.println("secretNameInKeyVault1: " + secretNameInKeyVault1);
        System.out.println("secretNameInKeyVault2: " + secretNameInKeyVault2);
        System.out.println("secretNameInKeyVaultBoth: " + secretNameInKeyVaultBoth);
    }

}
----

=== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0[azure-spring-boot-samples] for more details.

