

== Secret Management

Spring Cloud Azure construct link:https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-property-source-abstraction[PropertySource] which holds secrets stored in Azure Key Vault Secrets.

=== Dependency Setup

[source,xml]
----
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
</dependency>
----

=== Basic Usage

If you want to authenticate by `client-id` and `client-secret`, the following properties are required:

==== Configuration Properties
[source,yml]
----
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - name: key-vault-property-souece-1
              endpoint: ${ENDPOINT_1}
            - name: key-vault-property-souece-2
              endpoint: ${ENDPOINT_2}
----

==== Java Code
[source,java]
----
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {

    @Value("${sampleProperty1}")
    private String sampleProperty1;
    @Value("${sampleProperty2}")
    private String sampleProperty2;
    @Value("${samplePropertyInMultipleKeyVault}")
    private String samplePropertyInMultipleKeyVault;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    public void run(String[] args) {
        System.out.println("sampleProperty1: " + sampleProperty1);
        System.out.println("sampleProperty2: " + sampleProperty2);
        System.out.println("samplePropertyInMultipleKeyVault: " + samplePropertyInMultipleKeyVault);
    }

}
----

=== Advanced Usage

==== Special Characters in Property Name

Key Vault secret name only support characters in `[0-9a-zA-Z-]`. Refs: link:https://docs.microsoft.com/azure/key-vault/general/about-keys-secrets-certificates#vault-name-and-object-name[Vault-name and Object-name]. If your property name contains other characters, you can use these workarounds:

-  Use `-` instead of `.` in secret name. `.` is not supported in secret name. If your application have property name which contain `.`, like `spring.datasource.url`, just replace `.` to `-` when save secret in Azure Key Vault. For example: Save `spring-datasource-url` in Azure Key Vault. In your application, you can still use `spring.datasource.url` to retrieve property value. **NOTE**: This method can not satisfy requirement like `spring.datasource-url`. When you save `spring-datasource-url` in Key Vault, only `spring.datasource.url` and `spring-datasource-url` is supported to retrieve property value, `spring.datasource-url` is not supported. To handle this case, please refer to the following option: Use property placeholders.

-  Use property placeholders. For example: setting this property in your application.properties: `property.with.special.character_=${propertyWithoutSpecialCharacter}`. The application will get  `propertyWithoutSpecialCharacter` key name and assign its value to `property.with.special.character_`.

==== Case Sensitive

By default, the secret names are case-insensitive. To enable case-sensitive mode, just set the following property: `spring.cloud.azure.keyvault.secret.property-sources[].case-sensitive=true`.

==== Not Retrieve All Secrets In Key Vault

If you stored 1000 secrets in the Key Vault, and you just want to use 3 of them. You can list the 3 secret names by `spring.cloud.azure.keyvault.secret.property-sources[].secret-keys`.

==== Setting Refresh Interval

By default, the secrets in `KeyVaultPropertySource` will refresh every 30 minutes. You can configure the time by `spring.cloud.azure.keyvault.secret.property-sources[].refresh-interval`. For example: `spring.cloud.azure.keyvault.secret.property-sources[].refresh-interval=60m` means refresh every 60 minutes. Set to `0` to disable auto-refresh.

==== PropertySource Priority

If key exists in multiple PropertySources, which will take effect is decided by the priority.

- If there is no `SystemEnvironmentPropertySource` in PropertySource list, then `KeyVaultPropertySource` will take the highest priority.
- If there is `SystemEnvironmentPropertySource` in PropertySource list, then `SystemEnvironmentPropertySource` have higher priority than KeyVaultPropertySource. Which means you can use environment variable to override the Key Vault secret value in your application.
- If there is multiple KeyVaultPropertySource in PropertySource list, then the definition order is the priority order. Take above sample as example, `key-vault-property-souece-1` has higher priority than `key-vault-property-souece-2`.

==== All Configurable Properties

.Configurable properties of Key Vault Secret PropertySource
[cols="<45,<5,<50", options="header"]
|===
| Property                                                                | Default value                    | Description
| *spring.cloud.azure.keyvault.secret*.property-source-enabled            | true                             | Whether to enable the Key Vault property source.
| *spring.cloud.azure.keyvault.secret*.property-sources[].name            |                                  | Name of this property source.
| *spring.cloud.azure.keyvault.secret*.property-sources[].endpoint        |                                  | Azure Key Vault endpoint.
| *spring.cloud.azure.keyvault.secret*.property-sources[].case-sensitive  | false                            | Whether the secret keys are case-sensitive.
| *spring.cloud.azure.keyvault.secret*.property-sources[].secret-keys     |                                  | The secret keys supported for this property source. All keys be retrieved if this property is not configured.
| *spring.cloud.azure.keyvault.secret*.property-sources[].refresh-interval| 30m                              | Time interval to refresh all Key Vault secrets.
| *spring.cloud.azure.keyvault.secret*.property-sources[].service-version |                                  | Secret service version used when making API requests.
| *spring.cloud.azure.keyvault.secret*.property-sources[].client          |                                  | Client related properties.
| *spring.cloud.azure.keyvault.secret*.property-sources[].credential      |                                  | Credential related properties.
| *spring.cloud.azure.keyvault.secret*.property-sources[].profile         |                                  | Profile related properties.
| *spring.cloud.azure.keyvault.secret*.property-sources[].proxy           |                                  | Proxy related properties.
| *spring.cloud.azure.keyvault.secret*.property-sources[].retry           |                                  | Retry related properties.
|===

- Please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the link:https://docs.microsoft.com/azure/active-directory/develop/app-objects-and-service-principals#service-principal-object[security principal] has been granted the sufficient permission to access the Azure Key Vault Secrets.
- If common properties like `client`, `credential`, `profile`, `proxy`, `retry` are not configured in `spring.cloud.azure.keyvault.secret.property-sources[].xxx`, `spring.cloud.azure.xxx` will be used. Please refer to link:index.html#configuration[Configuration] to get more information about these common properties.
- Please refer to link:appendix.html#_configuration_properties[Configuration Properties] to get more information about nested properties.

=== Samples

Sample project: link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source[property-source].
