

== Secret Management

spring-cloud-azure-starter-keyvault-secrets adds Azure Key Vault as one of the Spring PropertySource, so secrets stored in Azure Key Vault could be easily used and conveniently accessed like other externalized configuration property, e.g. properties in files.

=== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
</dependency>
----

=== Configuration

Configurable items

|===
|Properties |Description
| spring.cloud.azure.keyvault.secret.endpoint                                            | Key Vault uri
| spring.cloud.azure.keyvault.secret.service-version                                     | Service version
| spring.cloud.azure.keyvault.secret.property-source-enabled                             | Enable this property source
| spring.cloud.azure.keyvault.secret.property-sources                                    | Multiple property source
| spring.cloud.azure.keyvault.secret.property-sources[].name                             | Name of this property source
| spring.cloud.azure.keyvault.secret.property-sources[].endpoint                         | Key Vault uri
| spring.cloud.azure.keyvault.secret.property-sources[].service-version                  | Service version
| spring.cloud.azure.keyvault.secret.property-sources[].case-sensitive                   | Whether the secret name is case-sensitive
| spring.cloud.azure.keyvault.secret.property-sources[].secret-keys                      | The supported secret names. If not configured, it will retrieve all secret names.
| spring.cloud.azure.keyvault.secret.property-sources[].refresh-interval                 | Refresh interval
|
|===

[source,yml]
----
spring:
  cloud:
    azure:
      profile:
        tenant-id: ${TENANT_ID}
      credential:
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${ENDPOINT}
----

=== Basic Usage


[source,java]
----
@SpringBootApplication
public class KeyVaultSample implements CommandLineRunner {

    @Value("${your-property-name}")
    private String mySecretProperty;

    public static void main(String[] args) {
        SpringApplication.run(KeyVaultSample.class, args);
    }

    @Override
    public void run(String... args) {
        System.out.println("property your-property-name value is: " + mySecretProperty);
    }
}
----



=== Samples
