== Spring Cloud Stream Support

Spring Cloud Stream is a framework for building highly scalable event-driven microservices connected with shared messaging systems.

The framework provides a flexible programming model built on already established and familiar Spring idioms and best practices, including support for persistent pub/sub semantics, consumer groups, and stateful partitions.

Current binder implementations include:

* spring-cloud-azure-stream-binder-eventhubs
* spring-cloud-azure-stream-binder-servicebus

=== Spring Cloud Stream Binder for Azure Event Hubs

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-eventhubs</artifactId>
</dependency>
----
==== Configuration

The binder provides the following 2 parts of configuration options:

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
of which the prefix is changed from *spring.cloud.azure.eventhubs.* to *spring.cloud.azure.*.
|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.enabled | boolean | Whether an Azure Event Hubs is enabled.
|*spring.cloud.azure.eventhubs*.credential.* | NA | Properties used for getting token credential.
|*spring.cloud.azure.eventhubs*.credential.clientId | String | Client id to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientCertificatePassword | String | Password of the certificate file.
|*spring.cloud.azure.eventhubs*.credential.username | String | Username to use when performing username/password authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.password | String | Password to use when performing username/password authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.
|*spring.cloud.azure.eventhubs*.profile.* | String | Properties related to an Azure subscription.
|*spring.cloud.azure.eventhubs*.profile.tenantId | String | Tenant id for Azure resources.
|*spring.cloud.azure.eventhubs*.profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.
|*spring.cloud.azure.eventhubs*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.
|*spring.cloud.azure.eventhubs*.profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.
|*spring.cloud.azure.eventhubs*.profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.
|*spring.cloud.azure.eventhubs*.resource.* | String | Metadata defining an Azure resource.
|*spring.cloud.azure.eventhubs*.resource.resourceGroup | String | Name of the Azure resource group.
|*spring.cloud.azure.eventhubs*.resource.resourceId | String | Id of the Azure resource group.
|*spring.cloud.azure.eventhubs*.resource.region | String | Name of region.
|*spring.cloud.azure.eventhubs*.client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.
|*spring.cloud.azure.eventhubs*.retry.* | NA | Retry properties.
|*spring.cloud.azure.eventhubs*.retry.backoff.* | NA | Backoff properties when a retry fails.
|*spring.cloud.azure.eventhubs*.retry.backoff.delay | Duration | Amount of time to wait between retry attempts.
|*spring.cloud.azure.eventhubs*.retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.
|*spring.cloud.azure.eventhubs*.retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.
|*spring.cloud.azure.eventhubs*.retry.maxAttempts | Integer | The maximum number of attempts.
|*spring.cloud.azure.eventhubs*.retry.timeout | Duration | Amount of time to wait until a timeout.
|*spring.cloud.azure.eventhubs*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.eventhubs*.proxy.type | String | Type of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.hostname | String | The host of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.port | Integer | The port of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.authenticationType | String | Authentication type used against the proxy.
|*spring.cloud.azure.eventhubs*.proxy.username | String | Username used to authenticate with the proxy.
|*spring.cloud.azure.eventhubs*.proxy.password | String | Password used to authenticate with the proxy.
|===
===== Azure Event Hubs Client Configuration Options
Below options are used to configure Azure Event Hubs SDK Client.

|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.connection-string | String | Event Hubs Namespace connection string value.
|*spring.cloud.azure.eventhubs*.namespace | String | Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.domainName | String | Domain name of an Azure Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.eventHubName | String | Name of an Event Hub entity.
|*spring.cloud.azure.eventhubs*.customEndpointAddress | String | Custom Endpoint address.
|*spring.cloud.azure.eventhubs*.isSharedConnection | Boolean | Whether to use the same connection for different Event Hub producer / consumer client.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.* | NA | Blob checkpoint store configuration options.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.createContainerIfNotExists | Boolean | If allowed to create container if not exists.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.customerProvidedKey | String | Base64 encoded string of the encryption key.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.encryptionScope | String | Encryption scope to encrypt blob contents on the server.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.serviceVersion | BlobServiceVersion | The versions of Azure Storage Blob supported by this client library.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.blobName | String | Storage blob name.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.containerName | String | Storage container name.
|===

===== Azure Event Hubs Binding Configuration Options
Below options are used to configure Azure Event Hubs Binding properties.

> For *spring.cloud.stream.eventhubs*.bindings entry's value is type of
Map<String, EventHubsExtendedBindingProperties>, we flattened the details here for clarity.
consumer and producer are correspondingly listed below.
|===
|Properties | Type |Description
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.mode |
CheckpointMode | literal string of `RECORD`, `BATCH`, `MANUAL`, `PARTITION_COUNT`, `TIME`
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.count | Integer | count
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.interval | Duration |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-size | Integer |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-wait-time | Duration |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.update-interval
|Duration| interval time for update
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.strategy |
LoadBalancingStrategy |literal value of BALANCED or GREEDY
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>
.consumer.track-las-enqueued-event-properties |Boolean |as it is
|*spring.cloud.stream.eventhubs*.bindings.<binding-name> .consumer
.partition-ownership-expiration-interval |Boolean | expiration interval time for partition ownership
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer
.sync |boolean | switch flag for sync of producer
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer
.send-timeout |long | timeout value for sending of producer

|===

==== Basic Usage

. Method 1: Connection string based usage

**  Create [Azure Event Hubs][create-event-hubs].
After creating the Azure Event Hub, you can create your own Consumer Group or use the default "$Default" Consumer Group.

**  Create [Azure Storage][create-azure-storage] for checkpoint usage.

**  Update [application.yaml][application.yaml].
[source,yaml]
----
    spring:
      cloud:
        azure:
          eventhubs:
            # Fill event hub namespace connection string copied from portal
            connection-string: [eventhub-namespace-connection-string]
            # Fill checkpoint storage account name, access key and container
            processor:
              checkpoint-store:
                container-name: [checkpoint-container]
                account-name: [checkpoint-storage-account]
                account-key: [checkpoint-access-key]
        stream:
          function:
            definition: consume;supply
          bindings:
            consume-in-0:
              destination: [eventhub-name]
              group: [consumer-group]
            supply-out-0:
              destination: [the-same-eventhub-name-as-above]
----

** Define suppler and consumer
[source,java]
----
 @Bean
    public Consumer<List<String>> consume() {
        return list -> list.forEach(event -> LOGGER.info("New event received: '{}'",event));
    }

    @Bean
    public Supplier<Message<String>> supply() {
        return () -> {
            LOGGER.info("Sending message, sequence " + i);
            return MessageBuilder.withPayload("\"Hello world"+ i++ +"\"").build();
        };
    }
----
==== Samples

Please refer to this https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud
-azure_4.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs[sample project] to learn how to
use Event Hubs Binder.

=== Spring Cloud Stream Binder for Azure Service Bus

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
</dependency>
----

==== Configuration

The binder provides the following configuration options:

===== Spring Cloud Azure Properties

[cols="<,<,<,<"]
|===
|Name |Description |Required |Default

|spring.cloud.azure.auto-create-resources |If enable auto-creation for Azure resources | |false
|spring.cloud.azure.region |Region name of the Azure resource group, e.g. westus |Yes if spring.cloud.azure.auto-create-resources is enabled. 
|spring.cloud.azure.environment |Azure Cloud name for Azure resources, supported values are `azure`, `azurechina`, `azure_germany` and `azureusgovernment` which are case insensitive | |azure 
|spring.cloud.azure.client-id |Client (application) id of a service principal or Managed Service Identity (MSI) |Yes if service principal or MSI is used as credential configuration. 
|spring.cloud.azure.client-secret |Client secret of a service principal |Yes if service principal is used as credential configuration. 
|spring.cloud.azure.msi-enabled |If enable MSI as credential configuration |Yes if MSI is used as credential configuration. |false
|spring.cloud.azure.resource-group |Name of Azure resource group |Yes if service principal or MSI is used as credential configuration. 
|spring.cloud.azure.subscription-id |Subscription id of an MSI |Yes if MSI is used as credential configuration. 
|spring.cloud.azure.tenant-id |Tenant id of a service principal |Yes if service principal is used as credential configuration. 
|spring.cloud.azure.servicebus.connection-string |Service Bus Namespace connection string |Yes if connection string is used as credential configuration 
|spring.cloud.azure.servicebus.namespace |Service Bus Namespace. Auto creating if missing |Yes if service principal or MSI is used as credential configuration. 
|spring.cloud.azure.servicebus.transportType |Service Bus transportType, supported value of `AMQP` and `AMQP_WEB_SOCKETS` |No |`AMQP`
|spring.cloud.azure.servicebus.retry-Options |Service Bus retry options |No |Default value of AmqpRetryOptions
|===

===== Partition configuration

The system will obtain the parameter `PartitionSupply` to send the message.

The following are configuration items related to the producer:

*_partition-count_*

The number of target partitions for the data, if partitioning is enabled.

Default: 1

*_partition-key-extractor-name_*

The name of the bean that implements `PartitionKeyExtractorStrategy`.
The partition handler will first use the `PartitionKeyExtractorStrategy#extractKey` method to obtain the partition key value.

Default: null

*_partition-key-expression_*

A SpEL expression that determines how to partition outbound data.
When interface `PartitionKeyExtractorStrategy` is not implemented, it will be called in the method `PartitionHandler#extractKey`.

Default: null

For more information about setting partition for the producer properties, please refer to the https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_producer_properties[Producer Properties of Spring Cloud Stream].

===== Serivce Bus Queue Producer Properties

It supports the following configurations with the format of `spring.cloud.stream.servicebus.queue.bindings.&lt;channelName&gt;.producer`.

*_sync_*

Whether the producer should act in a synchronous manner with respect to writing messages into a stream. If true, the
producer will wait for a response after a send operation.

Default: `false`

*_send-timeout_*

Effective only if `sync` is set to true. The amount of time to wait for a response after a send operation, in milliseconds.

Default: `10000`

===== Service Bus Queue Consumer Properties

It supports the following configurations with the format of `spring.cloud.stream.servicebus.queue.bindings.&lt;channelName&gt;.consumer`.

*_checkpoint-mode_*

The mode in which checkpoints are updated.

`RECORD`, checkpoints occur after each record successfully processed by user-defined message handler without any exception.

`MANUAL`, checkpoints occur on demand by the user via the `Checkpointer`. You can get `Checkpointer` by `Message.getHeaders.get(AzureHeaders.CHECKPOINTER)`callback.

Default: `RECORD`

*_prefetch-count_*

Prefetch count of underlying service bus client.

Default: `1`

*_maxConcurrentCalls_*

Controls the max concurrent calls of service bus message handler and the size of fixed thread pool that handles user's business logic

Default: `1`

*_maxConcurrentSessions_*

Controls the maximum number of concurrent sessions to process at any given time.

Default: `1`

*_concurrency_*

When `sessionsEnabled` is true, controls the maximum number of concurrent sessions to process at any given time.
When `sessionsEnabled` is false, controls the max concurrent calls of service bus message handler and the size of fixed thread pool that handles user's business logic.

Deprecated, replaced with `maxConcurrentSessions` when `sessionsEnabled` is true and `maxConcurrentCalls` when `sessionsEnabled` is false

Default: `1`

*_sessionsEnabled_*

Controls if is a session aware consumer. Set it to `true` if is a queue with sessions enabled.

Default: `false`

*_requeueRejected_*

Controls if is a message that trigger any exception in consumer will be force to DLQ.
Set it to `true` if a message that trigger any exception in consumer will be force to DLQ.
Set it to `false` if a message that trigger any exception in consumer will be re-queued.

Default: `false`

*_receiveMode_*

The modes for receiving messages.

`PEEK_LOCK`, received message is not deleted from the queue or subscription, instead it is temporarily locked to the receiver, making it invisible to other receivers.

`RECEIVE_AND_DELETE`, received message is removed from the queue or subscription and immediately deleted.

Default: `PEEK_LOCK`

*_enableAutoComplete_*

Enable auto-complete and auto-abandon of received messages.
'enableAutoComplete' is not needed in for RECEIVE_AND_DELETE mode.

Default: `false`

===== Support for Service Bus Message Headers and Properties

The following table illustrates how Spring message headers are mapped to Service Bus message headers and properties.
When create a message, developers can specify the header or property of a Service Bus message by below constants.

For some Service Bus headers that can be mapped to multiple Spring header constants, the priority of different Spring headers is listed.

|===
|Service Bus Message Headers and Properties |Spring Message Header Constants |Type |Priority Number (Descending priority)
|*MessageId* |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.MESSAGE_ID |String |1
|*MessageId* |com.azure.spring.integration.core.AzureHeaders.RAW_ID |String |2
|*MessageId* |org.springframework.messaging.MessageHeaders.ID |UUID |3
|ContentType |org.springframework.messaging.MessageHeaders.CONTENT_TYPE |String |N/A
|ReplyTo |org.springframework.messaging.MessageHeaders.REPLY_CHANNEL |String |N/A
|*ScheduledEnqueueTimeUtc* |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.SCHEDULED_ENQUEUE_TIME |OffsetDateTime |1
|*ScheduledEnqueueTimeUtc* |com.azure.spring.integration.core.AzureHeaders.SCHEDULED_ENQUEUE_MESSAGE |Integer |2
|TimeToLive |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.TIME_TO_LIVE |Duration |N/A
|SessionID |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.SESSION_ID |String |N/A
|CorrelationId |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.CORRELATION_ID |String |N/A
|To |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.TO |String |N/A
|ReplyToSessionId |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.REPLY_TO_SESSION_ID |String |N/A
|*PartitionKey* |com.azure.spring.integration.servicebus.converter.ServiceBusMessageHeaders.PARTITION_KEY |String |1
|*PartitionKey* |com.azure.spring.integration.core.AzureHeaders.PARTITION_KEY |String |2
|===

For full configurations, please check appendix

==== Basic Usage

==== Samples

*Example: Manually set the partition key for the message*

This example demonstrates how to manually set the partition key for the message in the application.

*Approach 1:* Set partition key expression.

This example requires that `spring.cloud.stream.default.producer.partitionKeyExpression` be set `&quot;&#39;partitionKey-&#39; + headers[&lt;message-header-key&gt;]&quot;`.

[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: [servicebus-namespace-connection-string]
    stream:
      default:
        producer:
          partitionKeyExpression:  "'partitionKey-' + headers[<message-header-key>]"
----

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader("<message-header-key>", "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----


NOTE: When using `application.yml` to configure the partition key, its priority will be the lowest.
It will take effect only when the `ServiceBusMessageHeaders.SESSION_ID`, `ServiceBusMessageHeaders.PARTITION_KEY`, `AzureHeaders.PARTITION_KEY` are not configured.

*Approach 2:* Manually add the partition Key in the message header by code.


_Recommended:_ Use `ServiceBusMessageHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

_Not recommended but currently supported:_ `AzureHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(AzureHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When both `ServiceBusMessageHeaders.PARTITION_KEY` and `AzureHeaders.PARTITION_KEY` are set in the message headers,
`ServiceBusMessageHeaders.PARTITION_KEY` is preferred.

*Example: Set the session id for the message*

This example demonstrates how to manually set the session id of a message in the application.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.SESSION_ID, "Customize session id")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When the `ServiceBusMessageHeaders.SESSION_ID` is set in the message headers, and a different `ServiceBusMessageHeaders.PARTITION_KEY` (or `AzureHeaders.PARTITION_KEY`) header is also set,
the value of the session id will eventually be used to overwrite the value of the partition key.
Please use this `sample` as a reference to learn more about how to use this binder in your project.
- https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/azure-spring-cloud-stream-binder-servicebus-queue[Service Bus Queue]



