== Spring Integration Support

Spring Integration Extension for Azure provides Spring Integration adapters for the various services provided by the https://github.com/Azure/azure-sdk-for-java/[Azure SDK for Java]. Below is a list of supported adapters:

* spring-cloud-azure-starter-integration-eventhbus
* spring-cloud-azure-starter-integration-servicebus
* spring-cloud-azure-starter-integration-storage-queue

Provide Spring Integration support for these Azure services: Event Hubs, Service Bus, Storage Queue.

=== Spring Integration with Azure Event Hubs

==== Key concepts
Azure Event Hubs is a big data streaming platform and event ingestion service. It can receive and process millions of events per second. Data sent to an event hub can be transformed and stored by using any real-time analytics provider or batching/storage adapters.

Spring Integration enables lightweight messaging within Spring-based applications and supports integration with external systems via declarative adapters. Those adapters provide a higher-level of abstraction over Spring’s support for remoting, messaging, and scheduling. The *Spring Integration for Event Hubs* extension project provides inbound and outbound channel adapters and gateways for Azure Event Hubs.

NOTE: RxJava support APIs is dropped from version 4.0.0.
Please refer to Javadoc for details.

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-integration-eventhubs</artifactId>
</dependency>

----

==== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

This starter provides the following 2 parts of configuration options:

NOTE: From version 4.0.0, when the property of **spring.cloud.azure.eventhubs.processor.checkpoint-store.create-container-if-not-exists** is not enabled manually, no Storage container will be created automatically with the name from **spring.cloud.azure.eventhubs.event-hub-name**.

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties by changing the prefix from *spring.cloud.azure.eventhubs* to *spring.cloud.azure*.

.Common configurable properties of spring-cloud-azure-starter-integration-eventhubs
[cols="3,1,4", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.eventhubs*.enabled | boolean | Whether Azure Event Hubs service is enabled.
|*spring.cloud.azure.eventhubs*.credential.* | NA | Properties used for getting token credential.

|*spring.cloud.azure.eventhubs*.
credential.clientId | String | Client id to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.
credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.
credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.
credential.clientCertificatePassword | String | Password of the certificate file.

|*spring.cloud.azure.eventhubs*.
credential.username | String | Username to use when performing username/password authentication with Azure.

|*spring.cloud.azure.eventhubs*.
credential.password | String | Password to use when performing username/password authentication with Azure.

|*spring.cloud.azure.eventhubs*.
credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.

|*spring.cloud.azure.eventhubs*.profile.* | String | Properties related to an Azure subscription.
|*spring.cloud.azure.eventhubs*.profile.tenantId | String | Tenant id for Azure resources.

|*spring.cloud.azure.eventhubs*.
profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.

|*spring.cloud.azure.eventhubs*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.

|*spring.cloud.azure.eventhubs*.
profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.

|*spring.cloud.azure.eventhubs*.
profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.

|*spring.cloud.azure.eventhubs*.resource.* | String | Metadata defining an Azure resource.

|*spring.cloud.azure.eventhubs*.
resource.resourceGroup | String | Name of the Azure resource group.

|*spring.cloud.azure.eventhubs*.
resource.resourceId | String | ID of the Azure resource group.

|*spring.cloud.azure.eventhubs*.resource.region | String | Name of region.

|*spring.cloud.azure.eventhubs*.
client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.

|*spring.cloud.azure.eventhubs*.retry.* | NA | Retry properties.

|*spring.cloud.azure.eventhubs*.
retry.backoff.* | NA | Backoff properties when a retry fails.

|*spring.cloud.azure.eventhubs*.
retry.backoff.delay | Duration | Amount of time to wait between retry attempts.

|*spring.cloud.azure.eventhubs*.
retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.

|*spring.cloud.azure.eventhubs*.
retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.

|*spring.cloud.azure.eventhubs*.
retry.maxAttempts | Integer | The maximum number of attempts.

|*spring.cloud.azure.eventhubs*.retry.timeout | Duration | Amount of time to wait until a timeout.
|*spring.cloud.azure.eventhubs*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.eventhubs*.proxy.type | String | Type of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.hostname | String | The host of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.port | Integer | The port of the proxy.

|*spring.cloud.azure.eventhubs*.
proxy.authenticationType | String | Authentication type used against the proxy.

|*spring.cloud.azure.eventhubs*.proxy.username | String | Username used to authenticate with the proxy.
|*spring.cloud.azure.eventhubs*.proxy.password | String | Password used to authenticate with the proxy.
|===

===== Azure Event Hubs Client Configuration Options
Below options are used to configure Azure Event Hubs SDK Client.

.Client configurable properties of spring-cloud-azure-starter-integration-storage-queue
[cols="3*", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.eventhubs*.connection-string | String | Event Hubs Namespace connection string value.
|*spring.cloud.azure.eventhubs*.namespace | String | Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.domainName | String | Domain name of an Azure Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.eventHubName | String | Name of an Event Hub entity.
|*spring.cloud.azure.eventhubs*.customEndpointAddress | String | Custom Endpoint address.
|*spring.cloud.azure.eventhubs*.isSharedConnection | Boolean | Whether to use the same connection for different Event Hub producer / consumer client.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.* | NA | Blob checkpoint store configuration options.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.createContainerIfNotExists | Boolean | If allowed creating container if not exists.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.customerProvidedKey | String | Base64 encoded string of the encryption key.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.encryptionScope | String | Encryption scope to encrypt blob contents on the server.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.serviceVersion | BlobServiceVersion | The versions of Azure Storage Blob supported by this client library.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.blobName | String | Storage blob name.

|*spring.cloud.azure.eventhubs*.
processor.checkpointStore.containerName | String | Storage container name.
|===

==== Basic Usage
===== Send messages to Azure Event Hubs
Step 1. Fill the credential configuration options.

* For credentials as connection string, configure below properties in `application.yml`:
[source,yaml]
----
spring:
  cloud:
    azure:
      eventhubs:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
----

* For credentials as MSI, configure below properties in `application.yml`:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: ${AZURE_CLIENT_ID}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      eventhubs:
        namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----

* For credentials as service principal, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      eventhubs:
        namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----

Step 2. Create `DefaultMessageHandler` with the bean of `EventHubsTemplate` to send messages to Event Hubs.
[source,java]
----
class Demo{
    private static final String OUTPUT_CHANNEL = "output";
    private static final String EVENTHUB_NAME = "eh1";

    @Bean
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler messageSender(EventHubsTemplate queueOperation) {
        DefaultMessageHandler handler = new DefaultMessageHandler(EVENTHUB_NAME, queueOperation);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }
            @Override
            public void onFailure(Throwable ex) {
                LOGGER.error("There was an error sending the message.", ex);
            }
        });
        return handler;
    }
}
----

Step 3. Create a Message gateway binding with the message handler created in the last step via a message channel
[source,java]
----
class Demo{
    @Autowired
    EventHubOutboundGateway messagingGateway;

    @MessagingGateway(defaultRequestChannel = OUTPUT_CHANNEL)
    public interface EventHubOutboundGateway {
        void send(String text);
    }
}
----
Step 4. Send messages using the gateway
[source,java]
----
class Demo{
    public void demo() {
        this.messagingGateway.send(message);
    }
}
----

===== Receive messages from Azure Event Hubs
Step 1. Fill the credential configuration options.

Step 2. Create a bean of message channel as the input channel.
[source,java]
----
class Demo{
    private static final String INPUT_CHANNEL = "input";
    private static final String EVENTHUB_NAME = "eh1";
    private static final String CONSUMER_GROUP = "$Default";

    @Bean
    public MessageChannel input() {
        return new DirectChannel();
    }
}
----

Step 3. Create `EventHubsInboundChannelAdapter` with the bean of `EventHubsProcessorContainer` to receive messages to Event Hubs.
[source,java]
----
@Bean
class Demo{
    public EventHubsInboundChannelAdapter messageChannelAdapter(
            @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel,
            EventHubsProcessorContainer processorContainer) {
        CheckpointConfig config = new CheckpointConfig(CheckpointMode.MANUAL);

        EventHubsInboundChannelAdapter adapter =
                new EventHubsInboundChannelAdapter(processorContainer, EVENTHUB_NAME,
                        CONSUMER_GROUP, config);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
}
----

Step 4. Create a message receiver binding with EventHubsInboundChannelAdapter created in the last step via the message channel we created before.
[source,java]
----
class Demo{
    @ServiceActivator(inputChannel = INPUT_CHANNEL)
    public void messageReceiver(byte[] payload, @Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer) {
        String message = new String(payload);
        LOGGER.info("New message received: '{}'", message);
        checkpointer.success()
                .doOnSuccess(s -> LOGGER.info("Message '{}' successfully checkpointed", message))
                .doOnError(e -> LOGGER.error("Error found", e))
                .subscribe();
    }
}
----

[#si-eh-headers]
===== Event Hubs message headers

The following table illustrates how Event Hubs message properties are mapped to Spring message headers. For Azure Event Hubs, message is called as `event`.

.Mapping between Event Hubs Properties and Spring Headers
[cols="<,<,<,<", options="header"]
|===
|Event Hubs Event Properties | Spring Message Header Constants | Type | Description

|Enqueued time
|com.azure.spring.messaging.eventhubs.support.EventHubsHeaders#ENQUEUED_TIME
|Instant
|The instant, in UTC, of when the event was enqueued in the Event Hub partition.

|Offset
|com.azure.spring.messaging.eventhubs.support.EventHubsHeaders#OFFSET
|Long
|The offset of the event when it was received from the associated Event Hub partition.

|Partition key
|com.azure.spring.messaging.AzureHeaders#PARTITION_KEY
|String
|The partition hashing key if it was set when originally publishing the event.

|Partition id
|com.azure.spring.messaging.AzureHeaders#RAW_PARTITION_ID
|String
|The partition id of the Event Hub.

|Sequence number
|com.azure.spring.messaging.eventhubs.support.EventHubsHeaders#SEQUENCE_NUMBER
|Long
|The sequence number assigned to the event when it was enqueued in the associated Event Hub partition.

|Last enqueued event properties
|com.azure.spring.messaging.eventhubs.support.EventHubsHeaders#LAST_ENQUEUED_EVENT_PROPERTIES
|LastEnqueuedEventProperties
|The properties of the last enqueued event in this partition.

|NA
|com.azure.spring.messaging.AzureHeaders#CHECKPOINTER
|com.azure.spring.messaging.checkpoint.Checkpointer
|The header for checkpoint the specific message.
|===

Users can parse the message headers for the related information of each event. To set a message header for the event, all customized headers will be put as an application property of an event, where the header is set as the property key. When events are received from Event Hubs, all application properties will be converted to the message header.

NOTE: Message headers of partition key, enqueued time, offset and sequence number is not supported to be set manually.

==== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration[azure-spring-boot-samples] for more details.

=== Spring Integration with Azure Service Bus

==== Key concepts
Spring Integration enables lightweight messaging within Spring-based applications and supports integration with external systems via declarative adapters.

The Spring Integration for Azure Service Bus extension project provides inbound and outbound channel adapters for Azure Service Bus.

NOTE: CompletableFuture support APIs have been deprecated from version 2.10.0, and is replaced by Reactor Core from version 4.0.0.
Please refer to Javadoc for details.

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-integration-servicebus</artifactId>
</dependency>
----

==== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties by changing the prefix
from *spring.cloud.azure.servicebus* to *spring.cloud.azure*.

.Common configurable properties of spring-cloud-azure-starter-integration-servicebus
[cols="<,<,<", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.servicebus*.enabled | boolean | Whether an Azure Service Bus is enabled.
|*spring.cloud.azure.servicebus*.credential.* | NA | Properties used for getting token credential.

|*spring.cloud.azure.servicebus*.
credential.clientId | String | Client id to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.
credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.
credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.
credential.clientCertificatePassword | String | Password of the certificate file.

|*spring.cloud.azure.servicebus*.
credential.username | String | Username to use when performing username/password authentication with Azure.

|*spring.cloud.azure.servicebus*.
credential.password | String | Password to use when performing username/password authentication with Azure.

|*spring.cloud.azure.servicebus*.
credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.

|*spring.cloud.azure.servicebus*.profile.* | String | Properties related to an Azure subscription.

|*spring.cloud.azure.servicebus*.
profile.tenantId | String | Tenant id for Azure resources.

|*spring.cloud.azure.servicebus*.
profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.

|*spring.cloud.azure.servicebus*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.

|*spring.cloud.azure.servicebus*.
profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.

|*spring.cloud.azure.servicebus*.
profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.

|*spring.cloud.azure.servicebus*.resource.* | String | Metadata defining an Azure resource.

|*spring.cloud.azure.servicebus*.
resource.resourceGroup | String | Name of the Azure resource group.

|*spring.cloud.azure.servicebus*.
resource.resourceId | String | ID of the Azure resource group.

|*spring.cloud.azure.servicebus*.resource.region | String | Name of region.

|*spring.cloud.azure.servicebus*.
client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.

|*spring.cloud.azure.servicebus*.retry.* | NA | Retry properties.

|*spring.cloud.azure.servicebus*.
retry.backoff.* | NA | Backoff properties when a retry fails.

|*spring.cloud.azure.servicebus*.
retry.backoff.delay | Duration | Amount of time to wait between retry attempts.

|*spring.cloud.azure.servicebus*.
retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.

|*spring.cloud.azure.servicebus*.
retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.

|*spring.cloud.azure.servicebus*.
retry.maxAttempts | Integer | The maximum number of attempts.

|*spring.cloud.azure.servicebus*.retry.timeout | Duration | Amount of time to wait until a timeout.
|*spring.cloud.azure.servicebus*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.servicebus*.proxy.type | String | Type of the proxy.
|*spring.cloud.azure.servicebus*.proxy.hostname | String | The host of the proxy.
|*spring.cloud.azure.servicebus*.proxy.port | Integer | The port of the proxy.

|*spring.cloud.azure.servicebus*.
proxy.authenticationType | String | Authentication type used against the proxy.

|*spring.cloud.azure.servicebus*.proxy.username | String | Username used to authenticate with the proxy.
|*spring.cloud.azure.servicebus*.proxy.password | String | Password used to authenticate with the proxy.
|===

===== Azure Service Bus Client Configuration Options
Below options are used to configure Azure Service Bus SDK Client.

.Client configurable properties of spring-cloud-azure-starter-integration-servicebus
[cols="<,<,<", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.servicebus*.connection-string | String | Service Bus Namespace connection string value.
|*spring.cloud.azure.servicebus*.namespace | String | Service Bus Namespace value.
|*spring.cloud.azure.servicebus*.domainName | String | Domain name of an Azure Service Bus Namespace value.
|*spring.cloud.azure.servicebus*.entityName | String | Entity name of Azure Service Bus queue or topic.
|*spring.cloud.azure.servicebus*.entityType | ServiceBusEntityType | Entity type of Azure Service Bus queue or topic.

|*spring.cloud.azure.servicebus*.
crossEntityTransactions | Boolean | Enable cross entity transaction on the connection to Service bus.
|===

==== Basic Usage
===== Send messages to Azure Service Bus
Step 1. Fill the credential configuration options.

* For credentials as connection string, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
----

* For credentials as MSI, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: ${AZURE_CLIENT_ID}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      servicebus:
        namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----

* For credentials as service principal, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      servicebus:
        namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----

Step 2. Create `DefaultMessageHandler` with the bean of `ServiceBusTemplate` to send messages to Service Bus,
set the entity type for the ServiceBusTemplate.
[source,java]
----
class Demo{
    private static final String OUTPUT_CHANNEL = "queue.output";

    @Bean
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler queueMessageSender(ServiceBusTemplate serviceBusTemplate) {
        serviceBusTemplate.setDefaultEntityType(ServiceBusEntityType.QUEUE);
        DefaultMessageHandler handler = new DefaultMessageHandler(QUEUE_NAME, serviceBusTemplate);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.info("There was an error sending the message.");
            }
        });

        return handler;
    }
}
----

Step 3. Create a Message gateway binding with the message handler created in the last stop via a message channel
[source,java]
----
class Demo{
    @Autowired
    QueueOutboundGateway messagingGateway;

    @MessagingGateway(defaultRequestChannel = OUTPUT_CHANNEL)
    public interface QueueOutboundGateway {
        void send(String text);
    }
}
----

Step 4. Send messages using the gateway
[source,java]
----
class Demo{
    public void demo() {
        this.messagingGateway.send(message);
    }
}
----

===== Receive messages from Azure Service Bus
Step 1. Fill the credential configuration options.

Step 2. Create a bean of message channel as the input channel.
[source,java]
----
class Demo{
    private static final String INPUT_CHANNEL = "input";

    @Bean
    public MessageChannel input() {
        return new DirectChannel();
    }
}
----

Step 3. Create `ServiceBusInboundChannelAdapter` with the bean of `ServiceBusProcessorContainer` to receive messages to Service Bus.
[source,java]
----
class Demo{
    private static final String QUEUE_NAME = "queue1";

    @Bean
    public ServiceBusInboundChannelAdapter queueMessageChannelAdapter(
        @Qualifier(INPUT_CHANNEL) MessageChannel inputChannel, ServiceBusProcessorContainer processorContainer) {
        ServiceBusInboundChannelAdapter adapter = new ServiceBusInboundChannelAdapter(processorContainer, QUEUE_NAME,
            new CheckpointConfig(CheckpointMode.MANUAL));
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
}
----

Step 4. Create a message receiver binding with ServiceBusInboundChannelAdapter created in the last step via the message channel we created before.
[source,java]
----
class Demo{
    @ServiceActivator(inputChannel = INPUT_CHANNEL)
    public void messageReceiver(byte[] payload, @Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer) {
        String message = new String(payload);
        LOGGER.info("New message received: '{}'", message);
        checkpointer.success()
                .doOnSuccess(s -> LOGGER.info("Message '{}' successfully checkpointed", message))
                .doOnError(e -> LOGGER.error("Error found", e))
                .subscribe();
    }
}
----

===== Configure ServiceBusMessageConverter to customize ObjectMapper
`ServiceBusMessageConverter` is made as a configurable bean to allow users to customize ObjectMapper.


[#si-sb-headers]
===== Service Bus message headers
For some Service Bus headers that can be mapped to multiple Spring header constants, the priority of different Spring headers is listed.

.Mapping between Service Bus Headers and Spring Headers
[cols="<,<,<,<", options="header"]
|===
|Service Bus Message Headers and Properties | Spring Message Header Constants | Type | Priority Number (Descending priority)

|ContentType
| org.springframework.messaging.MessageHeaders.CONTENT_TYPE
| String
| N/A

|CorrelationId
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.CORRELATION_ID
|String
| N/A

|**MessageId**
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.MESSAGE_ID
| String
| 1

|**MessageId**
| com.azure.spring.messaging.AzureHeaders.RAW_ID
| String
| 2

|**MessageId**
| org.springframework.messaging.MessageHeaders.ID
| UUID
| 3

|PartitionKey
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.PARTITION_KEY
|String
| N/A

|ReplyTo
| org.springframework.messaging.MessageHeaders.REPLY_CHANNEL
| String
| N/A

|ReplyToSessionId
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.REPLY_TO_SESSION_ID
| String
| N/A

|**ScheduledEnqueueTimeUtc**
| com.azure.spring.messaging.AzureHeaders.SCHEDULED_ENQUEUE_MESSAGE
| Integer
| 1

|**ScheduledEnqueueTimeUtc**
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.SCHEDULED_ENQUEUE_TIME
| Instant
| 2

|SessionID
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.SESSION_ID
| String
| N/A

|TimeToLive
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.TIME_TO_LIVE
|Duration
| N/A

|To
| com.azure.spring.messaging.servicebus.support.ServiceBusMessageHeaders.TO
| String
| N/A
|===


==== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}/servicebus/spring-cloud-azure-starter-integration-servicebus[azure-spring-boot-samples] for more details.

*Example: Manually set the partition key for the message*

This example demonstrates how to manually set the partition key for the message in the application.

_Recommended:_ Use `ServiceBusMessageHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
public class SampleController {
    @PostMapping("/messages")
    public ResponseEntity<String> sendMessage(@RequestParam String message) {
        LOGGER.info("Going to add message {} to Sinks.Many.", message);
        many.emitNext(MessageBuilder.withPayload(message)
                                    .setHeader(ServiceBusMessageHeaders.PARTITION_KEY, "Customize partition key")
                                    .build(), Sinks.EmitFailureHandler.FAIL_FAST);
        return ResponseEntity.ok("Sent!");
    }
}
----

_Not recommended but currently supported:_ `AzureHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
public class SampleController {
    @PostMapping("/messages")
    public ResponseEntity<String> sendMessage(@RequestParam String message) {
        LOGGER.info("Going to add message {} to Sinks.Many.", message);
        many.emitNext(MessageBuilder.withPayload(message)
                                    .setHeader(AzureHeaders.PARTITION_KEY, "Customize partition key")
                                    .build(), Sinks.EmitFailureHandler.FAIL_FAST);
        return ResponseEntity.ok("Sent!");
    }
}
----

NOTE: When both `ServiceBusMessageHeaders.PARTITION_KEY` and `AzureHeaders.PARTITION_KEY` are set in the message headers,
`ServiceBusMessageHeaders.PARTITION_KEY` is preferred.

*Example: Set the session id for the message*

This example demonstrates how to manually set the session id of a message in the application.

[source,java]
----
public class SampleController {
    @PostMapping("/messages")
    public ResponseEntity<String> sendMessage(@RequestParam String message) {
        LOGGER.info("Going to add message {} to Sinks.Many.", message);
        many.emitNext(MessageBuilder.withPayload(message)
                                    .setHeader(ServiceBusMessageHeaders.SESSION_ID, "Customize session id")
                                    .build(), Sinks.EmitFailureHandler.FAIL_FAST);
        return ResponseEntity.ok("Sent!");
    }
}
----

NOTE: When the `ServiceBusMessageHeaders.SESSION_ID` is set in the message headers, and a different `ServiceBusMessageHeaders.PARTITION_KEY` (or `AzureHeaders.PARTITION_KEY`) header is also set,
the value of the session id will eventually be used to overwrite the value of the partition key.

=== Spring Integration with Azure Storage Queue

==== Key concepts
Azure Queue Storage is a service for storing large numbers of messages. You access messages from anywhere in the world via authenticated calls using HTTP or HTTPS. A queue message can be up to 64 KB in size. A queue may contain millions of messages, up to the total capacity limit of a storage account. Queues are commonly used to create a backlog of work to process asynchronously.

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-integration-storage-queue</artifactId>
</dependency>
----

==== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
by changing the prefix from *spring.cloud.azure.storage.queue* to *spring.cloud.azure*.

.Common configurable properties of spring-cloud-azure-starter-integration-storage-queue
[cols="<,<,<", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.storage.queue*.enabled | boolean | Whether an Azure Storage Queue is enabled.
|*spring.cloud.azure.storage.queue*.credential.* | NA | Properties used for getting token credential.

|*spring.cloud.azure.storage.queue*.
credential.clientId | String | Client id to use when performing service principal authentication with Azure.

|*spring.cloud.azure.storage.queue*.
credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.

|*spring.cloud.azure.storage.queue*.
credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.

|*spring.cloud.azure.storage.queue*.
credential.clientCertificatePassword | String | Password of the certificate file.

|*spring.cloud.azure.storage.queue*.
credential.username | String | Username to use when performing username/password authentication with Azure.

|*spring.cloud.azure.storage.queue*.
credential.password | String | Password to use when performing username/password authentication with Azure.

|*spring.cloud.azure.storage.queue*.
credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.

|*spring.cloud.azure.storage.queue*.profile.* | String | Properties related to an Azure subscription.

|*spring.cloud.azure.storage.queue*.
profile.tenantId | String | Tenant id for Azure resources.

|*spring.cloud.azure.storage.queue*.
profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.

|*spring.cloud.azure.storage.queue*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.

|*spring.cloud.azure.storage.queue*.
profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.

|*spring.cloud.azure.storage.queue*.
profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.

|*spring.cloud.azure.storage.queue*.resource.* | String | Metadata defining an Azure resource.

|*spring.cloud.azure.storage.queue*.
resource.resourceGroup | String | Name of the Azure resource group.

|*spring.cloud.azure.storage.queue*.
resource.resourceId | String | ID of the Azure resource group.

|*spring.cloud.azure.storage.queue*.resource.region | String | Name of region.

|*spring.cloud.azure.storage.queue*.
client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.

|*spring.cloud.azure.storage.queue*.retry.* | NA | Retry properties.

|*spring.cloud.azure.storage.queue*.
retry.backoff.* | NA | Backoff properties when a retry fails.

|*spring.cloud.azure.storage.queue*.
retry.backoff.delay | Duration | Amount of time to wait between retry attempts.

|*spring.cloud.azure.storage.queue*.
retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.

|*spring.cloud.azure.storage.queue*.
retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.

|*spring.cloud.azure.storage.queue*.
retry.maxAttempts | Integer | The maximum number of attempts.

|*spring.cloud.azure.storage.queue*.
retry.timeout | Duration | Amount of time to wait until a timeout.

|*spring.cloud.azure.storage.queue*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.storage.queue*.proxy.type | String | Type of the proxy.

|*spring.cloud.azure.storage.queue*.
proxy.hostname | String | The host of the proxy.

|*spring.cloud.azure.storage.queue*.proxy.port | Integer | The port of the proxy.

|*spring.cloud.azure.storage.queue*.
proxy.authenticationType | String | Authentication type used against the proxy.

|*spring.cloud.azure.storage.queue*.
proxy.username | String | Username used to authenticate with the proxy.

|*spring.cloud.azure.storage.queue*.
proxy.password | String | Password used to authenticate with the proxy.
|===

===== Azure Storage Queue Client Configuration Options
Below options are used to configure Azure Storage Queue SDK Client.

.Client configurable properties of spring-cloud-azure-starter-integration-storage-queue
[cols="<,<,<", options="header"]
|===
|Property | Type |Description
|*spring.cloud.azure.storage.queue*.connection-string | String | Storage Queue Namespace connection string value.
|*spring.cloud.azure.storage.queue*.accountName | String | Storage Queue account name.
|*spring.cloud.azure.storage.queue*.accountKey | String | Storage Queue account key.
|*spring.cloud.azure.storage.queue*.endpoint | String | Storage Queue service endpoint.
|*spring.cloud.azure.storage.queue*.sasToken | String | Sas token credential
|*spring.cloud.azure.storage.queue*.serviceVersion | QueueServiceVersion | QueueServiceVersion that is used when making API requests.
|*spring.cloud.azure.storage.queue*.messageEncoding | String | Queue message encoding.
|===

==== Basic Usage
===== Send messages to Azure Storage Queue
Step 1. Fill the credential configuration options.

** For credentials as connection string, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      storage:
        queue:
          connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
----

** For credentials as MSI, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: ${AZURE_CLIENT_ID}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      storage:
        queue:
          namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----

** For credentials as service principal, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      storage:
        queue:
          namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
----


Step 2. Create `DefaultMessageHandler` with the bean of `StorageQueueOperation` to send messages to Storage Queue.
[source,java]
----
class Demo{
    private static final String STORAGE_QUEUE_NAME = "example";
    private static final String OUTPUT_CHANNEL = "output";

    @Bean
    @ServiceActivator(inputChannel = OUTPUT_CHANNEL)
    public MessageHandler messageSender(StorageQueueOperation storageQueueOperation) {
        DefaultMessageHandler handler = new DefaultMessageHandler(STORAGE_QUEUE_NAME, storageQueueOperation);
        handler.setSendCallback(new ListenableFutureCallback<Void>() {
            @Override
            public void onSuccess(Void result) {
                LOGGER.info("Message was sent successfully.");
            }

            @Override
            public void onFailure(Throwable ex) {
                LOGGER.info("There was an error sending the message.");
            }
        });
        return handler;
    }
}
----

Step 3. Create a Message gateway binding with the message handler created in the last stop via a message channel
[source,java]
----
class Demo{
    @Autowired
    StorageQueueOutboundGateway storageQueueOutboundGateway;

    @MessagingGateway(defaultRequestChannel = OUTPUT_CHANNEL)
    public interface StorageQueueOutboundGateway {
        void send(String text);
    }
}
----

Step 4. Send messages using the gateway
[source,java]
----
class Demo{
    public void demo() {
        this.storageQueueOutboundGateway.send(message);
    }
}
----

===== Receive messages from Azure Storage Queue
Step 1. Fill the credential configuration options.

Step 2. Create a bean of message channel as the input channel.
[source,java]
----
class Demo{
    private static final String INPUT_CHANNEL = "input";

    @Bean
    public MessageChannel input() {
        return new DirectChannel();
    }
}
----

Step 3. Create `StorageQueueMessageSource` with the bean of `StorageQueueOperation` to receive messages to Storage Queue.
[source,java]
----
class Demo{
    private static final String STORAGE_QUEUE_NAME = "example";

    @Bean
    @InboundChannelAdapter(channel = INPUT_CHANNEL, poller = @Poller(fixedDelay = "1000"))
    public StorageQueueMessageSource storageQueueMessageSource(StorageQueueOperation storageQueueOperation) {
        storageQueueOperation.setCheckpointMode(CheckpointMode.MANUAL);
        storageQueueOperation.setVisibilityTimeoutInSeconds(10);

        return new StorageQueueMessageSource(STORAGE_QUEUE_NAME, storageQueueOperation);
    }
}
----

Step 4. Create a message receiver binding with StorageQueueMessageSource created in the last step via the message channel we created before.
[source,java]
----
class Demo{
    @ServiceActivator(inputChannel = INPUT_CHANNEL)
    public void messageReceiver(byte[] payload, @Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer) {
        String message = new String(payload);
        LOGGER.info("New message received: '{}'", message);
        checkpointer.success()
            .doOnError(Throwable::printStackTrace)
            .doOnSuccess(t -> LOGGER.info("Message '{}' successfully checkpointed", message))
            .subscribe();
    }
}
----

==== Samples

Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_{project-version}/storage/spring-cloud-azure-starter-integration-storage-queue[azure-spring-boot-samples] for more details.

