== Spring Cloud Stream Support

Spring Cloud Stream is a framework for building highly scalable event-driven microservices connected with shared messaging systems.

The framework provides a flexible programming model built on already established and familiar Spring idioms and best practices, including support for persistent pub/sub semantics, consumer groups, and stateful partitions.

Current binder implementations include:

* spring-cloud-azure-stream-binder-eventhubs
* spring-cloud-azure-stream-binder-servicebus

=== Spring Cloud Stream Binder for Azure Event Hubs

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-eventhubs</artifactId>
</dependency>
----

==== Configuration

The binder provides the following 3 parts of configuration options:

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
of which the prefix is changed from *spring.cloud.azure.eventhubs* to *spring.cloud.azure*.

.Common configurable properties of spring-cloud-azure-stream-binder-eventhubs
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.enabled
| boolean
| Whether an Azure Event Hubs is enabled.

|*spring.cloud.azure.eventhubs*.credential.*
| NA
| Properties used for getting token credential.

|*spring.cloud.azure.eventhubs*.credential.clientId
| String
| Client id to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.credential.clientSecret
| String
| Client secret to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.credential.clientCertificatePath
| String
| Path of a PEM certificate file to use when performing service principal authentication with Azure.

|*spring.cloud.azure.eventhubs*.credential.clientCertificatePassword
| String
| Password of the certificate file.

|*spring.cloud.azure.eventhubs*.credential.username
| String
| Username to use when performing username/password authentication with Azure.

|*spring.cloud.azure.eventhubs*.credential.password
| String
| Password to use when performing username/password authentication with Azure.

|*spring.cloud.azure.eventhubs*.credential.managedIdentityClientId
| String
| The client id to use when using managed identity to authenticate with Azure.

|*spring.cloud.azure.eventhubs*.profile.*
| String
| The properties related to an Azure subscription.

|*spring.cloud.azure.eventhubs*.profile.tenantId
| String
| Tenant id for Azure resources.

|*spring.cloud.azure.eventhubs*.profile.subscriptionId
| String
| Subscription id to use when connecting to Azure resources.

|*spring.cloud.azure.eventhubs*.profile.cloud
| AzureProfileAware.CloudType
| The name of the Azure cloud to connect to.

|*spring.cloud.azure.eventhubs*.profile.environment.*
| NA
| Properties to Azure services, such as endpoints, resource ids, etc.

|*spring.cloud.azure.eventhubs*.profile.environment.activeDirectoryEndpoint
| String
| The Azure Active Directory endpoint to connect to.

|*spring.cloud.azure.eventhubs*.resource.*
| String
| Metadata defining an Azure resource.

|*spring.cloud.azure.eventhubs*.resource.resourceGroup
| String
| Name of the Azure resource group.

|*spring.cloud.azure.eventhubs*.resource.resourceId
| String
| The id of the Azure resource group.

|*spring.cloud.azure.eventhubs*.resource.region
| String
| The name of region.

|*spring.cloud.azure.eventhubs*.client.transportType
| AmqpTransportType
| The Transport type switches available for AMQP protocol.

|*spring.cloud.azure.eventhubs*.retry.*
| NA
| Retry properties.

|*spring.cloud.azure.eventhubs*.retry.backoff.*
| NA
| Backoff properties when a retry fails.

|*spring.cloud.azure.eventhubs*.retry.backoff.delay
| Duration
| Amount of time to wait between retry attempts.

|*spring.cloud.azure.eventhubs*.retry.backoff.maxDelay
| Duration
| The maximum permissible amount of time between retry attempts.

|*spring.cloud.azure.eventhubs*.retry.backoff.multiplier
| Double
| Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.

|*spring.cloud.azure.eventhubs*.retry.maxAttempts
| Integer
| The maximum number of attempts.

|*spring.cloud.azure.eventhubs*.retry.timeout
| Duration
| Amount of time to wait until a timeout.

|*spring.cloud.azure.eventhubs*.proxy.*
| NA
| Common proxy properties.

|*spring.cloud.azure.eventhubs*.proxy.type
| String
| Type of the proxy.

|*spring.cloud.azure.eventhubs*.proxy.hostname
| String
| The host of the proxy.

|*spring.cloud.azure.eventhubs*.proxy.port
| Integer
| The port of the proxy.

|*spring.cloud.azure.eventhubs*.proxy.authenticationType
| String
| Authentication type used against the proxy.

|*spring.cloud.azure.eventhubs*.proxy.username
| String
| Username used to authenticate with the proxy.

|*spring.cloud.azure.eventhubs*.proxy.password
| String
| Password used to authenticate with the proxy.
|===
===== Azure Event Hubs Client Configuration Options

.Client configurable properties of spring-cloud-azure-stream-binder-eventhubs
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.connection-string
| String
| Event Hubs Namespace connection string value.

|*spring.cloud.azure.eventhubs*.namespace
| String
| Event Hubs Namespace value.

|*spring.cloud.azure.eventhubs*.domain-name
| String
| Domain name of an Azure Event Hubs Namespace value.

|*spring.cloud.azure.eventhubs*.event-hub-name
| String
| Name of an Event Hub entity.

|*spring.cloud.azure.eventhubs*.custom-endpoint-address
| String
| Custom Endpoint address.

|*spring.cloud.azure.eventhubs*.is-shared-connection
| Boolean
| Whether to use the same connection for different Event Hub producer / consumer client.

|*spring.cloud.azure.eventhubs*.producer.*
| NA
| Producer configuration options.

|*spring.cloud.azure.eventhubs*.consumer.*
| NA
| Consumer configuration options.

|*spring.cloud.azure.eventhubs*.consumer.consumerGroup
| NA
| Name of the consumer group this consumer is associated with.

|*spring.cloud.azure.eventhubs*.consumer.prefetchCount
| NA
| The number of events the Event Hub consumer will actively receive and queue locally without regard to whether a receiving operation is currently active.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.*
| NA
| Blob checkpoint store configuration options.

|*spring.cloud.azure.eventhubs*.processor.trackLastEnqueuedEventProperties
| Boolean
|Whether the event processor should request information on the last enqueued event on its associated partition, and track that information as events are received.

|*spring.cloud.azure.eventhubs*.processor.initialPartitionEventPosition
| Map
|The map containing the event position to use for each partition if a checkpoint for the partition does not exist in CheckpointStore.

|*spring.cloud.azure.eventhubs*.processor.partitionOwnershipExpirationInterval
| Duration
|The time duration after which the ownership of partition expires if it's not renewed by the owning processor instance.

|*spring.cloud.azure.eventhubs*.processor.batch. maxSize
| Integer
| The maximum number of events in a batch.

|*spring.cloud.azure.eventhubs*.processor.batch. max-wait-time
| Duration | The maximum time duration for one batch of the max size of message.

|*spring.cloud.azure.eventhubs*.processor.loadBalancing.updateInterval
| Duration
| The interval of load balancing strategy updating.

|*spring.cloud.azure.eventhubs*.processor.loadBalancing.strategy
| String
| The strategy used by event processor for load balancing the partition ownership to distribute the event processing work with other processor instances.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.create-container-if-not-exists
|Boolean
|If allowed creating containers if not exists.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.customer-provided-key
| String
| Base64 encoded string of the encryption key.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.encryption-scope
| String
| Encryption scope to encrypt blob contents on the server.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.service-version
| BlobServiceVersion
|The versions of Azure Storage Blob supported by this client library.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.blob-name
| String
| Storage blob name.

|*spring.cloud.azure.eventhubs*.processor.checkpoint-store.container-name
| String
| Storage container name.
|===

Notes:
For configuration of producer, consumer and processors, all the above common and client properties support to be configured individually by changing the origin prefix from `spring.cloud.azure.eventhubs.` to `spring.cloud.azure.eventhubs.producer/consumer/processor`.




===== Azure Event Hubs Binding Configuration Options
Below options are divided into four sections: Consumer Properties, Advanced Consumer
Configurations, Producer PropertiesProducer Properties, and Advanced Producer Configurations.

====== Consumer Properties

.Consumer configurable properties of spring-cloud-azure-stream-binder-eventhubs
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.mode
|CheckpointMode
| Checkpoint mode used when consumer decide how to checkpoint message

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.count
| Integer
|Decides the amount of message for each partition to do one checkpoint.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.interval
| Duration
|Decides the time interval to do one checkpoint

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-size
| Integer
| The maximum number of events in a batch.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-wait-time
| Duration
| The maximum time duration for batch consuming.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.update-interval
| Duration
| The interval time duration for updating.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.strategy
|LoadBalancingStrategy
|The load balancing strategy.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.track-las-enqueued-event-properties
|Boolean
| Whether the event processor should request information on the last enqueued event on its associated partition, and track that information as events are received.

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.partition-ownership-expiration-interval
|Boolean
| The expiration interval time for partition ownership
|===

====== Advanced Consumer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure
Event Hubs
Client Configuration Options`) can be applied for each specific consumer by replacing the prefix
of ''spring.cloud.azure.eventhubs.'' with `'spring.cloud.stream.eventhubs.bindings.<binding-name.consumer.'`.

====== Producer Properties

.Producer configurable properties of spring-cloud-azure-stream-binder-eventhubs
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer.sync
| boolean
|The switch flag for sync of producer

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer.send-timeout
| long
| The timeout value for sending of producer
|===

====== Advanced Producer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure
Event Hubs
Client Configuration Options`) can be applied for each specific producer by replacing the prefix
of 'spring.cloud.azure.eventhubs' with `spring.cloud.stream.eventhubs.bindings.<binding-name>.producer`.



==== Basic Usage

** Fill the configuration options with credential information.

- For credentials as connection string, configure below properties in application.yml:

[source,yaml]
----
    spring:
      cloud:
        azure:
          eventhubs:
            # Fill event hub namespace connection string copied from portal
            connection-string: ${EVENTHUB_NAMESPACE_CONNECTION_STRING}
            # Fill checkpoint storage account name, access key and container
            processor:
              checkpoint-store:
                container-name: ${CHECKPOINT-CONTAINER}
                account-name: ${CHECKPOINT-STORAGE-ACCOUNT}
                account-key: ${CHECKPOINT-ACCESS-KEY}
        stream:
          function:
            definition: consume;supply
          bindings:
            consume-in-0:
              destination: ${EVENTHUB-NAME}
              group: ${CONSUMER-GROUP}
            supply-out-0:
              destination: ${THE-SAME-EVENTHUB-NAME-AS-ABOVE}
----
- For credentials as MSI, configure below properties in application.yml:
[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        msi-enabled: true
        client-id: ${THE_ID_OF_MANAGED_IDENTITY}
        resource-group: ${RESOURCE-GROUP}
        subscription-id: ${SUBSCRIPTION-ID}
      eventhubs:
        namespace: ${EVENTHUB-NAMESPACE}
        processor:
          checkpoint-store:
            container-name: ${CONTAINER-NAME}
            account-name: ${ACCOUNT-NAME}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${EVENTHUB_NAME}
          group: ${CONSUMER_GROUP}
        supply-out-0:
          destination: ${THE_SAME_EVENTHUB_NAME_AS_ABOVE}

      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
----


- For credentials as service principal, configure below properties in application.yml:

[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: ${SERVICE_PRINCIPAL_ID}
        client-secret: ${SERVICE-PRINCIPAL_SECRET}
      profile:
        tenant-id: ${TENANT_ID}
        resource-group: ${RESOURCE_GROUP}
      eventhubs:
        namespace: ${EVENTHUB_NAMESPACE}
        processor:
          checkpoint-store:
            container-name: ${CONTAINER_NAME}
            account-name: ${ACCOUNT_NAME}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${EVENTHUB_NAME}
          group: ${CONSUMER_GROUP}
        supply-out-0:
          destination: ${THE_SAME_EVENTHUB_NAME_AS_ABOVE}

      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
----

** Define supplier and consumer
[source,java]
----
@Bean
public Consumer<Message<String>> consume() {
    return message -> {
        Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
        LOGGER.info("New message received: '{}', partition key: {}, sequence number: {}, offset: {}, enqueued time: {}",
                message.getPayload(),
                message.getHeaders().get(EventHubsHeaders.PARTITION_KEY),
                message.getHeaders().get(EventHubsHeaders.SEQUENCE_NUMBER),
                message.getHeaders().get(EventHubsHeaders.OFFSET),
                message.getHeaders().get(EventHubsHeaders.ENQUEUED_TIME)
        );

        checkpointer.success()
                .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message.getPayload()))
                .doOnError(error -> LOGGER.error("Exception found", error))
                .subscribe();
    };
}

@Bean
public Supplier<Message<String>> supply() {
    return () -> {
        LOGGER.info("Sending message, sequence " + i);
        return MessageBuilder.withPayload("Hello world, " + i++).build();
    };
}
----
==== Samples

Please refer to this https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs to learn how to
use Event Hubs Binder.

=== Spring Cloud Stream Binder for Azure Service Bus

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
</dependency>
----

==== Configuration

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
of which the prefix is changed from *spring.cloud.azure.servicebus* to *spring.cloud.azure*.

.Common configurable properties of spring-cloud-azure-stream-binder-servicebus
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.azure.servicebus*.enabled
| boolean
| Whether an Azure Service Bus is enabled.

|*spring.cloud.azure.servicebus*.credential.*
| NA
| Properties used for getting token credential.
|*spring.cloud.azure.servicebus*.credential.client-id
| String
| Client id to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.credential.client-secret
| String
| Client secret to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.credential.client-certificate-path
| String
| Path of a PEM certificate file to use when performing service principal authentication with Azure.

|*spring.cloud.azure.servicebus*.credential.client-certificate-password
| String | Password of the certificate file.

|*spring.cloud.azure.servicebus*.credential.username
| String
| Username to use when performing username/password authentication with Azure.

|*spring.cloud.azure.servicebus*.credential.password
| String
| Password to use when performing username/password authentication with Azure.

|*spring.cloud.azure.servicebus*.credential.managed-identity-clientId
| String
| Client id to use when using managed identity to authenticate with Azure.

|*spring.cloud.azure.servicebus*.profile.*
| String
| Properties related to an Azure subscription.

|*spring.cloud.azure.servicebus*.profile.tenant-id
| String
| Tenant id for Azure resources.

|*spring.cloud.azure.servicebus*.profile.subscription-Id
| String
| Subscription id to use when connecting to Azure resources.

|*spring.cloud.azure.servicebus*.profile.cloud
| AzureProfileAware.CloudType
| Name of the Azure cloud to connect to.

|*spring.cloud.azure.servicebus*.profile.environment.*
| NA
| Properties to Azure services, such as endpoints, resource ids, etc.

|*spring.cloud.azure.servicebus*.profile.environment.active-directory-endpoint
| String
| The Azure Active Directory endpoint to connect to.

|*spring.cloud.azure.servicebus*.resource.*
| String
| Metadata defining an Azure resource.
|*spring.cloud.azure.servicebus*.resource.resource-group
| String
| Name of the Azure resource group.

|*spring.cloud.azure.servicebus*.resource.resource-id
| String
| Id of the Azure resource group.

|*spring.cloud.azure.servicebus*.resource.region
| String
| Name of region.

|*spring.cloud.azure.servicebus*.client.transport-type
| AmqpTransportType
| Transport type switches available for AMQP protocol.

|*spring.cloud.azure.servicebus*.retry.*
| NA
| Retry properties.

|*spring.cloud.azure.servicebus*.retry.backoff.*
| NA
| Backoff properties when a retry fails.

|*spring.cloud.azure.servicebus*.retry.backoff.delay
| Duration
| Amount of time to wait between retry attempts.

|*spring.cloud.azure.servicebus*.retry.backoff.max-delay
| Duration
| Maximum permissible amount of time between retry attempts.

|*spring.cloud.azure.servicebus*.retry.backoff.multiplier
| Double
| Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.

|*spring.cloud.azure.servicebus*.retry.max-attempts
| Integer
| The maximum number of attempts.

|*spring.cloud.azure.servicebus*.retry.timeout
| Duration
| Amount of time to wait until a timeout.

|*spring.cloud.azure.servicebus*.proxy.*
| NA
| Common proxy properties.

|*spring.cloud.azure.servicebus*.proxy.type
| String
| Type of the proxy.
|*spring.cloud.azure.servicebus*.proxy.hostname
| String
| The host of the proxy.

|*spring.cloud.azure.servicebus*.proxy.port
| Integer
| The port of the proxy.

|*spring.cloud.azure.servicebus*.proxy.authentication-type
| String
| Authentication type used against the proxy.

|*spring.cloud.azure.servicebus*.proxy.username
| String
| Username used to authenticate with the proxy.

|*spring.cloud.azure.servicebus*.proxy.password
| String
| Password used to authenticate with the proxy.
|===

===== Azure Service Bus Client Configuration Options

.Client configurable properties of spring-cloud-azure-stream-binder-servicebus
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.azure.servicebus*.connection-string
| String
| Service Bus Namespace connection string value.

|*spring.cloud.azure.servicebus*.namespace
| String
| Service Bus Namespace value.

|*spring.cloud.azure.servicebus*.domain-name
| String
| Domain name of an Azure Service Bus Namespace value.

|*spring.cloud.azure.servicebus*.entity-name
| String
| Entity name of Azure Service Bus queue or topic.

|*spring.cloud.azure.servicebus*.entity-type
| ServiceBusEntityType
| Entity type of Azure Service Bus queue or topic.

|*spring.cloud.azure.servicebus*.cross-entity-transactions
| Boolean
| Enable cross entity transaction on the connection to Service bus.

|*spring.cloud.azure.servicebus*.producer.*
| see Notes
| Producer configuration options.

|*spring.cloud.azure.servicebus*.consumer.*
| see Notes
| Consumer configuration options.

|*spring.cloud.azure.servicebus*.consumer.sessionEnabled
| Boolean
| Consumer Whether session is enabled.
|*spring.cloud.azure.servicebus*.consumer.autoComplete
| Boolean
| Consumer whether auto complete flag.

|*spring.cloud.azure.servicebus*.consumer.prefetchCount
| Integer
| Consumer prefetch count.

|*spring.cloud.azure.servicebus*.consumer.subQueue
| String
| Consumer sub queue name.

|*spring.cloud.azure.servicebus*.consumer.subscriptionName
| String
| Consumer subscription name.

|*spring.cloud.azure.servicebus*.consumer.maxAutoLockRenewDuration
| Duration
| Consumer max duration for auto lock renew.

|*spring.cloud.azure.servicebus*.consumer.receiveMode
| String
| Consumer receive mode.

|*spring.cloud.azure.servicebus*.processor.*
| see Notes
| Processor configuration option.
|===

Notes:

For configuration of producer, consumer and processors, all the above common and client properties support to be configured individually by changing the origin prefix from `spring.cloud.azure.servicebus.` to `spring.cloud.azure.servicebus.producer/consumer/processor`.

===== Azure Service Bus Binding Configuration Options
Below options are divided into four sections: Consumer Properties, Advanced Consumer
Configurations, Producer PropertiesProducer Properties, and Advanced Producer Configurations.

====== Consumer Properties

.Consumer configurable properties of spring-cloud-azure-stream-binder-servicebus
[cols="<,<,<", options="header"]
|===
|Properties | Type |Description

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.requeue-rejected
|boolean
|If the failed messages are routed to the DLQ.

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.checkpoint-mode
| CheckpointMode
| The checkpoint mode of checkpointing message.

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.max-concurrent-calls
| Integer
| The max number of concurrent calls.

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.max-concurrent-sessions
|Integer
| The max number of concurrent sessions.
|===

====== Advanced Consumer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure Service Bus Client Configuration Options`) can be applied for each specific consumer by replacing the prefix
of ''spring.cloud.azure.servicebus.'' with `'spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.'`.

====== Producer Properties
|===
|Properties | Type |Description

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.producer.sync |boolean | Switch flag
for sync of producer.
|*spring.cloud.stream.servicebus*.bindings.<binding-name>.producer.send-timeout |long | Timeout
value for sending of producer.

|===

====== Advanced Producer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure Service Bus Client Configuration Options`) can be applied for each specific producer by replacing the prefix
of 'spring.cloud.azure.servicebus' with `spring.cloud.stream.servicebus.bindings.<binding-name>
.producer`.

==== Basic Usage
Step 1. Fill the configuration options with credential information.

- For credentials as connection string, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${SERVICEBUS_NAMESPACE_CONNECTION_STRING}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${SERVICEBUS_QUEUE_NAME}
        supply-out-0:
          destination: ${SERVICEBUS_QUEUE_NAME_SAME_AS_ABOVE}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: ${CHECKPOINT_MODE}
          supply-out-0:
            producer:
              entity-type: ${ENTITY_TYPE}
      poller:
        fixed-delay: 1000
        initial-delay: 0

----

- For credentials as service principal, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: ${ CLIENT_ID }
        client-secret: ${ CLIENT_SECRET }
      profile:
        tenant-id: ${ TENANT_ID }
      servicebus:
        namespace: ${SERVICEBUS_NAMESPACE}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${ SERVICEBUS_QUEUE_NAME }
        supply-out-0:
          destination: ${ SERVICEBUS_QUEUE_NAME_SAME_AS_ABOVE }
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: ${CHECKPOINT_MODE}
          supply-out-0:
            producer:
              entity-type: ${ENTITY_TYPE}
      poller:
        fixed-delay: 1000
        initial-delay: 0


----

- For credentials as MSI, configure below properties in application.yml:
[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: ${MANAGED_IDENTITY_CLIENT_ID}
      profile:
        tenant-id: ${TENANT_ID}
      servicebus:
        namespace: ${SERVICEBUS_NAMESPACE}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${ SERVICEBUS_QUEUE_NAME }
        supply-out-0:
          destination: ${ SERVICEBUS_QUEUE_NAME_SAME_AS_ABOVE }
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: ${CHECKPOINT_MODE}
          supply-out-0:
            producer:
              entity-type: ${ENTITY_TYPE}
      poller:
        fixed-delay: 1000
        initial-delay: 0

----

Step 2. Define supplier and consumer
[source,java]
----
@Bean
public Consumer<Message<String>> consume() {
    return message -> {
        Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
        LOGGER.info("New message received: '{}', partition key: {}, sequence number: {}, offset: {}, enqueued time: {}",
                message.getPayload(),
                message.getHeaders().get(EventHubsHeaders.PARTITION_KEY),
                message.getHeaders().get(EventHubsHeaders.SEQUENCE_NUMBER),
                message.getHeaders().get(EventHubsHeaders.OFFSET),
                message.getHeaders().get(EventHubsHeaders.ENQUEUED_TIME)
        );

        checkpointer.success()
                .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message.getPayload()))
                .doOnError(error -> LOGGER.error("Exception found", error))
                .subscribe();
    };
}

@Bean
public Supplier<Message<String>> supply() {
    return () -> {
        LOGGER.info("Sending message, sequence " + i);
        return MessageBuilder.withPayload("Hello world, " + i++).build();
    };
}
----

==== Samples

*Example: Manually set the partition key for the message*

This example demonstrates how to manually set the partition key for the message in the application.

*Approach 1:* Set partition key expression.

This example requires that `spring.cloud.stream.default.producer.partitionKeyExpression` be set `&quot;&#39;partitionKey-&#39; + headers[&lt;message-header-key&gt;]&quot;`.

[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${CONNECTION_STRING}
    stream:
      default:
        producer:
          partitionKeyExpression:  "'partitionKey-' + headers[<message-header-key>]"
----

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader("<message-header-key>", "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----


NOTE: When using `application.yml` to configure the partition key, its priority will be the lowest.
It will take effect only when the `ServiceBusMessageHeaders.SESSION_ID`, `ServiceBusMessageHeaders.PARTITION_KEY`, `AzureHeaders.PARTITION_KEY` are not configured.

*Approach 2:* Manually add the partition Key in the message header by code.


_Recommended:_ Use `ServiceBusMessageHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

_Not recommended but currently supported:_ `AzureHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(AzureHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When both `ServiceBusMessageHeaders.PARTITION_KEY` and `AzureHeaders.PARTITION_KEY` are set in the message headers,
`ServiceBusMessageHeaders.PARTITION_KEY` is preferred.

*Example: Set the session id for the message*

This example demonstrates how to manually set the session id of a message in the application.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.SESSION_ID, "Customize session id")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When the `ServiceBusMessageHeaders.SESSION_ID` is set in the message headers, and a different `ServiceBusMessageHeaders.PARTITION_KEY` (or `AzureHeaders.PARTITION_KEY`) header is also set,
the value of the session id will eventually be used to overwrite the value of the partition key.
Please use this `sample` as a reference to learn more about how to use this binder in your project.
- https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/azure-spring-cloud-stream-binder-servicebus-queue[Service Bus Queue]


### Set Service Bus message headers
The following table illustrates how Spring message headers are mapped to Service Bus message headers and properties.
When create a message, developers can specify the header or property of a Service Bus message by
below constants.

[source,java]
----
@Autowired
private Sinks.Many<Message<String>> many;

@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    many.emitNext(MessageBuilder.withPayload(message)
    .setHeader(SESSION_ID, "group1")
    .build(),
    Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

For some Service Bus headers that can be mapped to multiple Spring header constants, the priority of different Spring headers is listed.
|===
|Service Bus Message Headers and Properties | Spring Message Header Constants | Type | Priority
Number (Descending priority)

|ContentType| org.springframework.messaging.MessageHeaders.CONTENT_TYPE | String | N/A
|CorrelationId | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.CORRELATION_ID |String | N/A
|**MessageId** | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.MESSAGE_ID | String| 1
|**MessageId** | com.azure.spring.messaging.AzureHeaders.RAW_ID | String | 2
|**MessageId** | org.springframework.messaging.MessageHeaders.ID | UUID | 3
|PartitionKey | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.PARTITION_KEY |
String | N/A
|ReplyTo | org.springframework.messaging.MessageHeaders.REPLY_CHANNEL | String | N/A
|ReplyToSessionId | com.azure.spring.servicebus.support.ServiceBusMessageHeaders
.REPLY_TO_SESSION_ID | String | N/A
|**ScheduledEnqueueTimeUtc** | com.azure.spring.messaging.AzureHeaders.SCHEDULED_ENQUEUE_MESSAGE
| Integer | 1
|**ScheduledEnqueueTimeUtc** | com.azure.spring.servicebus.support.ServiceBusMessageHeaders
.SCHEDULED_ENQUEUE_TIME | Instant | 2
|SessionID | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.SESSION_ID | String | N/A
|TimeToLive | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.TIME_TO_LIVE |
Duration | N/A
|To | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.TO | String | N/A
|===



Please refer https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/servicebus/spring-cloud-azure-stream-binder-servicebus to learn how to use ServiceBus Binder.


