== Spring Boot Support

Spring Boot greatly simplifies the Spring Cloud Azure experience. Spring Cloud Azure Starters are a set of convenient dependency descriptors to include in your application. Our starters handle the object instantiation and configuration logic, so you don’t have to. Every starter depends on the Spring Cloud Azure starter to provide critical bits of configuration, like the Azure Cloud environment and authentication information. You can configure these as properties in, for example, a properties file:

[source,properties]
----
spring.cloud.azure.profile.tenant-id=[TENANT_ID]
spring.cloud.azure.profile.cloud=[AZURE]
spring.cloud.azure.credential.client-id=[CLIENT_ID]
----

These properties are optional and, if not specified, Spring Boot will attempt to automatically find them for you. For details on how Spring Boot finds these properties, refer to the documentation.

=== Production Ready Support

Starter for using Spring Boot’s Actuator which provides production ready features to help you monitor and manage your application

Actuator endpoints let you monitor and interact with your application. `Spring Boot Actuator` provides the infrastructure required for actuator endpoints.

This module extends the `Spring Boot Actuator` module and provides the actuating support for Azure services.

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter-actuator</artifactId>
</dependency>
----
