== Spring Data Support

=== Spring Data CosmosDB Support

link:https://azure.microsoft.com/services/cosmos-db/[Azure Cosmos DB] is a globally-distributed database service that allows developers to work with data using a variety of standard APIs, such as SQL, MongoDB, Graph, and Azure Table storage.

Connect to Cosmos DB using Spring Data and CosmosDB libraries.

=== Dependency Setup

[source,xml]
----
<dependency>
   <groupId>com.azure.spring</groupId>
   <artifactId>spring-cloud-azure-starter-data-cosmos</artifactId>
</dependency>
----


=== Configuration

NOTE: If you choose to use a security principal to authenticate and authorize with Azure Active Directory for accessing an Azure resource, please refer to link:index.html#authorize-access-with-azure-active-directory[Authorize access with Azure AD] to make sure the security principal has been granted the sufficient permission to access the Azure resource.

.Configurable properties of spring-cloud-azure-starter-data-cosmos
[cols="2,1,3", options="header"]
|===
|Property | Default | Description

|*spring.cloud.azure.cosmos*.enabled
|true
|Whether Azure Cosmos Service is enabled.

|*spring.cloud.azure.cosmos*.database
|  
|The CosmosDB database id 

|*spring.cloud.azure.cosmos*.endpoint
|  
|Uri to connect CosmosDB 

|*spring.cloud.azure.cosmos*.key
|  
|PrivateKey to connect CosmosDB 

|*spring.cloud.azure.cosmos*.credential.client-certificate-password
|
|Password of the certificate file. 

|*spring.cloud.azure.cosmos*.credential.client-certificate-path
|  
|Path of a PEM certificate file to use when performing service principal authentication with Azure. 

|*spring.cloud.azure.cosmos*.credential.client-id
|  
|Client id to use when performing service principal authentication with Azure. 

|*spring.cloud.azure.cosmos*.credential.client-secret
|  
|Client secret to use when performing service principal authentication with Azure. 

|*spring.cloud.azure.cosmos*.credential.managed-identity-client-id
|  
|Client id to use when using managed identity to authenticate with Azure. 

|*spring.cloud.azure.cosmos*.credential.password
|  
|Password to use when performing username/password authentication with Azure. 

|*spring.cloud.azure.cosmos*.credential.username
|  
|Username to use when performing username/password authentication with Azure. 

|*spring.cloud.azure.cosmos*.populate-query-metrics
|false  
|Populate Diagnostics Strings and Query metrics.

|*spring.cloud.azure.cosmos*.consistency-level
|
| link:https://docs.microsoft.com/azure/cosmos-db/consistency-levels[Consistency levels] in Azure Cosmos DB
|===


=== Key concepts
* Spring Data CrudRepository and ReactiveCrudRepository basic CRUD functionality
  ** save
  ** findAll
  ** findOne by Id
  ** deleteAll
  ** delete by Id
  ** delete entity
* Spring Data link:https://github.com/spring-projects/spring-data-commons/blob/db62390de90c93a78743c97cc2cc9ccd964994a5/src/main/java/org/springframework/data/annotation/Id.java[@Id] annotation.
  There're 2 ways to map a field in domain class to `id` of Azure Cosmos DB document.
  ** annotate a field in domain class with @Id, this field will be mapped to document `id` in Cosmos DB. 
  ** set name of this field to `id`, this field will be mapped to document `id` in Cosmos DB.
    [Note] if both way applied,    
* Custom collection Name.
   By default, collection name will be class name of user domain class. To customize it, add annotation `@Document(collection="myCustomCollectionName")` to your domain class, that's all.
* Supports link:https://docs.microsoft.com/azure/cosmos-db/partitioning-overview[Azure Cosmos DB partition]. To specify a field of your domain class to be partition key field, just annotate it with `@PartitionKey`. When you do CRUD operation, please specify your partition value. For more sample on partition CRUD, please refer to link:https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/integration/AddressRepositoryIT.java[test here]
* Supports link:https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.query-methods.details[Spring Data custom query] find operation.
* Supports link:https://spring.io/projects/spring-data-rest[spring-boot-starter-data-rest].
* Supports List and nested type in domain class.


=== Basic Usage

==== Use private key to access CosmosDB
The simplest way to connect CosmosDB with `spring-cloud-azure-starter-data-cosmos` is primary key, add below properties, and you are good to go.

[source,yaml]
----
spring:
  cloud:
    azure:
      cosmos:
        key: ${AZURE_COSMOS_KEY}
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        database: ${AZURE_COSMOS_DATABASE}
----

==== Define an entity
Define a simple entity as Document in Cosmos DB.
----
@Container(containerName = "mycollection")
public class User {
    @Id
    private String id;
    private String firstName;
    @PartitionKey
    private String lastName;
    private String address;

    public User() {
    }

    public User(String id, String firstName, String lastName, String address) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return String.format("%s %s, %s", firstName, lastName, address);
    }
}
----

`id`` field will be used as document `id`` in Azure Cosmos DB. Or you can annotate any field with `@Id to map it to document `id`.

Annotation `@Container(containerName = "mycollection")` is used to specify the collection name of your document in Azure Cosmos DB.

==== Create repositories
Extends ReactiveCosmosRepository interface, which provides Spring Data repository support.

----
@Repository
public interface UserRepository extends ReactiveCosmosRepository<User, String> {

    Flux<User> findByFirstName(String firstName);
}
----

So far ReactiveCosmosRepository provides basic save, delete and find operations. More operations will be supported later.

==== Create an Application class
Here create an application class with all the components

----
@SpringBootApplication
public class CosmosSampleApplication implements CommandLineRunner {

   private static final Logger LOGGER = LoggerFactory.getLogger(CosmosSampleApplication.class);

	@Autowired
	private UserRepository repository;

	@Autowired
	private CosmosProperties properties;

	public static void main(String[] args) {
		SpringApplication.run(CosmosSampleApplication.class, args);
	}

	public void run(String... var1) {
		final User testUser = new User("testId", "testFirstName",
				"testLastName", "test address line one");

		// Save the User class to Azure Cosmos DB database.
		final Mono<User> saveUserMono = repository.save(testUser);

		final Flux<User> firstNameUserFlux = repository.findByFirstName("testFirstName");

		//  Nothing happens until we subscribe to these Monos.
		//  findById will not return the user as user is not present.
		final Mono<User> findByIdMono = repository.findById(testUser.getId());
		final User findByIdUser = findByIdMono.block();
		Assert.isNull(findByIdUser, "User must be null");

		final User savedUser = saveUserMono.block();
		Assert.state(savedUser != null, "Saved user must not be null");
		Assert.state(savedUser.getFirstName().equals(testUser.getFirstName()),
				"Saved user first name doesn't match");

		firstNameUserFlux.collectList().block();

		final Optional<User> optionalUserResult = repository.findById(testUser.getId()).blockOptional();
		Assert.isTrue(optionalUserResult.isPresent(), "Cannot find user.");

		final User result = optionalUserResult.get();
		Assert.state(result.getFirstName().equals(testUser.getFirstName()),
				"query result firstName doesn't match!");
		Assert.state(result.getLastName().equals(testUser.getLastName()),
				"query result lastName doesn't match!");
		LOGGER.info("findOne in User collection get result: {}", result.toString());

	}

	@PostConstruct
	public void setup() {
		// For this example, remove all of the existing records.
		this.repository.deleteAll().block();
	}
}
----

Autowired UserRepository interface, then can do save, delete and find operations.



=== Next steps
Besides using this Azure Cosmos DB Spring Boot Starter, you can directly use Spring Data for Azure Cosmos DB package for more complex scenarios. Please refer to link:https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos[Spring Data for Azure Cosmos DB] for more details.

=== More Sample
Please refer to link:https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.2/cosmos[azure-spring-boot-samples] for more details.

