== Spring Cloud Stream Support

Spring Cloud Stream is a framework for building highly scalable event-driven microservices connected with shared messaging systems.

The framework provides a flexible programming model built on already established and familiar Spring idioms and best practices, including support for persistent pub/sub semantics, consumer groups, and stateful partitions.

Current binder implementations include:

* spring-cloud-azure-stream-binder-eventhubs
* spring-cloud-azure-stream-binder-servicebus

=== Spring Cloud Stream Binder for Azure Event Hubs

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-eventhubs</artifactId>
</dependency>
----

==== Configuration

The binder provides the following 3 parts of configuration options:

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
of which the prefix is changed from *spring.cloud.azure.eventhubs.* to *spring.cloud.azure.*.
|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.enabled | boolean | Whether an Azure Event Hubs is enabled.
|*spring.cloud.azure.eventhubs*.credential.* | NA | Properties used for getting token credential.
|*spring.cloud.azure.eventhubs*.credential.clientId | String | Client id to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.clientCertificatePassword | String | Password of the certificate file.
|*spring.cloud.azure.eventhubs*.credential.username | String | Username to use when performing username/password authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.password | String | Password to use when performing username/password authentication with Azure.
|*spring.cloud.azure.eventhubs*.credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.
|*spring.cloud.azure.eventhubs*.profile.* | String | Properties related to an Azure subscription.
|*spring.cloud.azure.eventhubs*.profile.tenantId | String | Tenant id for Azure resources.
|*spring.cloud.azure.eventhubs*.profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.
|*spring.cloud.azure.eventhubs*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.
|*spring.cloud.azure.eventhubs*.profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.
|*spring.cloud.azure.eventhubs*.profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.
|*spring.cloud.azure.eventhubs*.resource.* | String | Metadata defining an Azure resource.
|*spring.cloud.azure.eventhubs*.resource.resourceGroup | String | Name of the Azure resource group.
|*spring.cloud.azure.eventhubs*.resource.resourceId | String | Id of the Azure resource group.
|*spring.cloud.azure.eventhubs*.resource.region | String | Name of region.
|*spring.cloud.azure.eventhubs*.client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.
|*spring.cloud.azure.eventhubs*.retry.* | NA | Retry properties.
|*spring.cloud.azure.eventhubs*.retry.backoff.* | NA | Backoff properties when a retry fails.
|*spring.cloud.azure.eventhubs*.retry.backoff.delay | Duration | Amount of time to wait between retry attempts.
|*spring.cloud.azure.eventhubs*.retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.
|*spring.cloud.azure.eventhubs*.retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.
|*spring.cloud.azure.eventhubs*.retry.maxAttempts | Integer | The maximum number of attempts.
|*spring.cloud.azure.eventhubs*.retry.timeout | Duration | Amount of time to wait until a timeout.
|*spring.cloud.azure.eventhubs*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.eventhubs*.proxy.type | String | Type of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.hostname | String | The host of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.port | Integer | The port of the proxy.
|*spring.cloud.azure.eventhubs*.proxy.authenticationType | String | Authentication type used against the proxy.
|*spring.cloud.azure.eventhubs*.proxy.username | String | Username used to authenticate with the proxy.
|*spring.cloud.azure.eventhubs*.proxy.password | String | Password used to authenticate with the proxy.
|===
===== Azure Event Hubs Client Configuration Options
Below options are used to configure Azure Event Hubs SDK Client.

|===
|Properties | Type |Description

|*spring.cloud.azure.eventhubs*.connection-string | String | Event Hubs Namespace connection string value.
|*spring.cloud.azure.eventhubs*.namespace | String | Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.domainName | String | Domain name of an Azure Event Hubs Namespace value.
|*spring.cloud.azure.eventhubs*.eventHubName | String | Name of an Event Hub entity.
|*spring.cloud.azure.eventhubs*.customEndpointAddress | String | Custom Endpoint address.
|*spring.cloud.azure.eventhubs*.isSharedConnection | Boolean | Whether to use the same connection for different Event Hub producer / consumer client.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.* | NA | Blob checkpoint store configuration options.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.createContainerIfNotExists | Boolean | If allowed to create container if not exists.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.customerProvidedKey | String | Base64 encoded string of the encryption key.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.encryptionScope | String | Encryption scope to encrypt blob contents on the server.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.serviceVersion | BlobServiceVersion | The versions of Azure Storage Blob supported by this client library.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.blobName | String | Storage blob name.
|*spring.cloud.azure.eventhubs*.processor.checkpointStore.containerName | String | Storage container name.
|===

===== Azure Event Hubs Binding Configuration Options
Below options are divided into four sections: Consumer Properties, Advanced Consumer
Configurations, Producer PropertiesProducer Properties, and Advanced Producer Configurations.

====== Consumer Properties
|===
|Properties | Type |Description

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.mode |
CheckpointMode | literal string of `RECORD`, `BATCH`, `MANUAL`, `PARTITION_COUNT`, `TIME`
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.count | Integer | count
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.checkpoint.interval | Duration |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-size | Integer |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.batch.max-wait-time | Duration |
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.update-interval
|Duration| interval time for update
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.load-balancing.strategy |
LoadBalancingStrategy |literal value of BALANCED or GREEDY
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>
.consumer.track-las-enqueued-event-properties |Boolean |as it is
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.consumer.partition-ownership-expiration-interval |Boolean | expiration interval time for partition ownership
|===

====== Advanced Consumer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure
Event Hubs
Client Configuration Options`) can be applied for each specific consumer by replacing the prefix
of ''spring.cloud.azure.eventhubs.'' with `'spring.cloud.stream.eventhubs.bindings.<binding-name>
.consumer.'`.

====== Producer Properties
|===
|Properties | Type |Description

|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer
.sync |boolean | switch flag for sync of producer
|*spring.cloud.stream.eventhubs*.bindings.<binding-name>.producer
.send-timeout |long | timeout value for sending of producer

|===

====== Advanced Producer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure
Event Hubs
Client Configuration Options`) can be applied for each specific producer by replacing the prefix
of 'spring.cloud.azure.eventhubs.' with `spring.cloud.stream.eventhubs.bindings.<binding-name>
.producer.`.



==== Basic Usage

** Fill the configuration options with credential information.

- For credentials as connection string, configure below properties in application.yml:

[source,yaml]
----
    spring:
      cloud:
        azure:
          eventhubs:
            # Fill event hub namespace connection string copied from portal
            connection-string: [eventhub-namespace-connection-string]
            # Fill checkpoint storage account name, access key and container
            processor:
              checkpoint-store:
                container-name: [checkpoint-container]
                account-name: [checkpoint-storage-account]
                account-key: [checkpoint-access-key]
        stream:
          function:
            definition: consume;supply
          bindings:
            consume-in-0:
              destination: [eventhub-name]
              group: [consumer-group]
            supply-out-0:
              destination: [the-same-eventhub-name-as-above]
----
- For credentials as MSI, configure below properties in application.yml:
[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        msi-enabled: true
        client-id: [the-id-of-managed-identity]
        resource-group: [resource-group]
        subscription-id: [subscription-id]
      eventhub:
        namespace: [eventhub-namespace]
          processor:
            checkpoint-store:
              container-name: [container-name]
              account-name: [account-name]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [eventhub-name]
          group: [consumer-group]
        supply-out-0:
          destination: [the-same-eventhub-name-as-above]

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
----


- For credentials as service principal, configure below properties in application.yml:

[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: [service-principal-id]
        client-secret: [service-principal-secret]
      profile:
        tenant-id: [tenant-id]
        resource-group: [resource-group]

    #     Uncomment below configurations if you want to enable auto creating resources.
    #
    #      subscription-id: [ subscription-id ]
    #      auto-create-resources: true
    #      environment: Azure
    #      region: [ region ]

      eventhub:
        namespace: [eventhub-namespace]
          processor:
              checkpoint-store:
                container-name: [container-name]
                account-name: [account-name]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [eventhub-name]
          group: [consumer-group]
        supply-out-0:
          destination: [the-same-eventhub-name-as-above]

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
----

** Define supplier and consumer
[source,java]
----
@Bean
public Consumer<List<String>> consume() {
    return list -> list.forEach(event -> LOGGER.info("New event received: '{}'",event));
}

@Bean
public Supplier<Message<String>> supply() {
    return () -> {
        LOGGER.info("Sending message, sequence " + i);
        return MessageBuilder.withPayload("\"Hello world"+ i++ +"\"").build();
    };
}
----
==== Samples

Please refer to this https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud
-azure_4.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs to learn how to
use Event Hubs Binder.

=== Spring Cloud Stream Binder for Azure Service Bus

==== Dependency Setup

[source,xml]
----
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
</dependency>
----

==== Configuration

===== Azure Common Configuration Options
Below properties can also be configured with the default Spring Cloud Azure unified properties,
of which the prefix is changed from *spring.cloud.azure.servicebus.* to *spring.cloud.azure.*.
|===
|Properties | Type |Description

|*spring.cloud.azure.servicebus*.enabled | boolean | Whether an Azure Service Bus is enabled.
|*spring.cloud.azure.servicebus*.credential.* | NA | Properties used for getting token credential.
|*spring.cloud.azure.servicebus*.credential.clientId | String | Client id to use when performing service principal authentication with Azure.
|*spring.cloud.azure.servicebus*.credential.clientSecret | String | Client secret to use when performing service principal authentication with Azure.
|*spring.cloud.azure.servicebus*.credential.clientCertificatePath | String | Path of a PEM certificate file to use when performing service principal authentication with Azure.
|*spring.cloud.azure.servicebus*.credential.clientCertificatePassword | String | Password of the certificate file.
|*spring.cloud.azure.servicebus*.credential.username | String | Username to use when performing username/password authentication with Azure.
|*spring.cloud.azure.servicebus*.credential.password | String | Password to use when performing username/password authentication with Azure.
|*spring.cloud.azure.servicebus*.credential.managedIdentityClientId | String | Client id to use when using managed identity to authenticate with Azure.
|*spring.cloud.azure.servicebus*.profile.* | String | Properties related to an Azure subscription.
|*spring.cloud.azure.servicebus*.profile.tenantId | String | Tenant id for Azure resources.
|*spring.cloud.azure.servicebus*.profile.subscriptionId | String | Subscription id to use when connecting to Azure resources.
|*spring.cloud.azure.servicebus*.profile.cloud | AzureProfileAware.CloudType | Name of the Azure cloud to connect to.
|*spring.cloud.azure.servicebus*.profile.environment.* | NA | Properties to Azure services, such as endpoints, resource ids, etc.
|*spring.cloud.azure.servicebus*.profile.environment.activeDirectoryEndpoint | String | The Azure Active Directory endpoint to connect to.
|*spring.cloud.azure.servicebus*.resource.* | String | Metadata defining an Azure resource.
|*spring.cloud.azure.servicebus*.resource.resourceGroup | String | Name of the Azure resource group.
|*spring.cloud.azure.servicebus*.resource.resourceId | String | Id of the Azure resource group.
|*spring.cloud.azure.servicebus*.resource.region | String | Name of region.
|*spring.cloud.azure.servicebus*.client.transportType | AmqpTransportType | Transport type switches available for AMQP protocol.
|*spring.cloud.azure.servicebus*.retry.* | NA | Retry properties.
|*spring.cloud.azure.servicebus*.retry.backoff.* | NA | Backoff properties when a retry fails.
|*spring.cloud.azure.servicebus*.retry.backoff.delay | Duration | Amount of time to wait between retry attempts.
|*spring.cloud.azure.servicebus*.retry.backoff.maxDelay | Duration | Maximum permissible amount of time between retry attempts.
|*spring.cloud.azure.servicebus*.retry.backoff.multiplier | Double | Multiplier used to calculate the next backoff delay. If positive, then used as a multiplier for generating the next delay for backoff.
|*spring.cloud.azure.servicebus*.retry.maxAttempts | Integer | The maximum number of attempts.
|*spring.cloud.azure.servicebus*.retry.timeout | Duration | Amount of time to wait until a timeout.
|*spring.cloud.azure.servicebus*.proxy.* | NA | Common proxy properties.
|*spring.cloud.azure.servicebus*.proxy.type | String | Type of the proxy.
|*spring.cloud.azure.servicebus*.proxy.hostname | String | The host of the proxy.
|*spring.cloud.azure.servicebus*.proxy.port | Integer | The port of the proxy.
|*spring.cloud.azure.servicebus*.proxy.authenticationType | String | Authentication type used against the proxy.
|*spring.cloud.azure.servicebus*.proxy.username | String | Username used to authenticate with the proxy.
|*spring.cloud.azure.servicebus*.proxy.password | String | Password used to authenticate with the proxy.
|===

===== Azure Service Bus Client Configuration Options
Below options are used to configure Azure Service Bus SDK Client.
|===
|Properties | Type |Description

|*spring.cloud.azure.servicebus*.connection-string | String | Service Bus Namespace connection string value.
|*spring.cloud.azure.servicebus*.namespace | String | Service Bus Namespace value.
|*spring.cloud.azure.servicebus*.domainName | String | Domain name of an Azure Service Bus Namespace value.
|*spring.cloud.azure.servicebus*.entityName | String | Entity name of Azure Service Bus queue or topic.
|*spring.cloud.azure.servicebus*.entityType | ServiceBusEntityType | Entity type of Azure Service Bus queue or topic.
|*spring.cloud.azure.servicebus*.crossEntityTransactions | Boolean | Enable cross entity transaction on the connection to Service bus.
|===

===== Azure Service Bus Binding Configuration Options
Below options are divided into four sections: Consumer Properties, Advanced Consumer
Configurations, Producer PropertiesProducer Properties, and Advanced Producer Configurations.

====== Consumer Properties
|===
|Properties | Type |Description

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.requeueRejected |
boolean | xxx
|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.checkpointMode| CheckpointMode
| xxx
|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.maxConcurrentCalls | Integer |
|*spring.cloud.stream.servicebus*.bindings.<binding-name>.consumer.maxConcurrentSessions | Integer |
|===

====== Advanced Consumer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure Service Bus Client Configuration Options`) can be applied for each specific consumer by replacing the prefix
of ''spring.cloud.azure.servicebus.'' with `'spring.cloud.stream.servicebus.bindings.<binding-name>
.consumer.'`.

====== Producer Properties
|===
|Properties | Type |Description

|*spring.cloud.stream.servicebus*.bindings.<binding-name>.producer
.sync |boolean | switch flag for sync of producer
|*spring.cloud.stream.servicebus*.bindings.<binding-name>.producer
.send-timeout |long | timeout value for sending of producer

|===

====== Advanced Producer Configuration
The configuration in the above first 2 sections(`Azure Common Configuration Options`, `Azure Service Bus Client Configuration Options`) can be applied for each specific producer by replacing the prefix
of 'spring.cloud.azure.servicebus.' with `spring.cloud.stream.servicebus.bindings.<binding-name>
.producer.`.

==== Basic Usage
step 1. Fill the configuration options with credential information.
- For credentials as connection string, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: [servicebus-namespace-connection-string]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [servicebus-queue-name]
        supply-out-0:
          destination: [servicebus-queue-name-same-as-above]
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0

----
- For credentials as service principal, configure below properties in application.yml:
[source,yaml]
----
spring:
  cloud:
    azure:
      credential:
        client-id: [ client-id ]
        client-secret: [ client-secret ]
      profile:
        tenant-id: [ tenant-id ]
      servicebus:
        namespace: [servicebus-namespace]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [ servicebus-queue-name ]
        supply-out-0:
          destination: [ servicebus-queue-name-same-as-above ]
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0


----
- For credentials as MSI, configure below properties in application.yml:
[source, yaml]
----
spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: [managed-identity-client-id]
      profile:
        tenant-id: [tenant-id]
      servicebus:
        namespace: [servicebus-namespace]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [ servicebus-queue-name ]
        supply-out-0:
          destination: [ servicebus-queue-name-same-as-above ]
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0

----

2. consumer and suppliers

==== Samples

*Example: Manually set the partition key for the message*

This example demonstrates how to manually set the partition key for the message in the application.

*Approach 1:* Set partition key expression.

This example requires that `spring.cloud.stream.default.producer.partitionKeyExpression` be set `&quot;&#39;partitionKey-&#39; + headers[&lt;message-header-key&gt;]&quot;`.

[source,yaml]
----
spring:
  cloud:
    azure:
      servicebus:
        connection-string: [servicebus-namespace-connection-string]
    stream:
      default:
        producer:
          partitionKeyExpression:  "'partitionKey-' + headers[<message-header-key>]"
----

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader("<message-header-key>", "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----


NOTE: When using `application.yml` to configure the partition key, its priority will be the lowest.
It will take effect only when the `ServiceBusMessageHeaders.SESSION_ID`, `ServiceBusMessageHeaders.PARTITION_KEY`, `AzureHeaders.PARTITION_KEY` are not configured.

*Approach 2:* Manually add the partition Key in the message header by code.


_Recommended:_ Use `ServiceBusMessageHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

_Not recommended but currently supported:_ `AzureHeaders.PARTITION_KEY` as the key of the header.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(AzureHeaders.PARTITION_KEY, "Customize partirion key")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When both `ServiceBusMessageHeaders.PARTITION_KEY` and `AzureHeaders.PARTITION_KEY` are set in the message headers,
`ServiceBusMessageHeaders.PARTITION_KEY` is preferred.

*Example: Set the session id for the message*

This example demonstrates how to manually set the session id of a message in the application.

[source,java]
----
@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    LOGGER.info("Going to add message {} to Sinks.Many.", message);
    many.emitNext(MessageBuilder.withPayload(message)
                                .setHeader(ServiceBusMessageHeaders.SESSION_ID, "Customize session id")
                                .build(), Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

NOTE: When the `ServiceBusMessageHeaders.SESSION_ID` is set in the message headers, and a different `ServiceBusMessageHeaders.PARTITION_KEY` (or `AzureHeaders.PARTITION_KEY`) header is also set,
the value of the session id will eventually be used to overwrite the value of the partition key.
Please use this `sample` as a reference to learn more about how to use this binder in your project.
- https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/azure-spring-cloud-stream-binder-servicebus-queue[Service Bus Queue]


### Set Service Bus message headers
The following table illustrates how Spring message headers are mapped to Service Bus message headers and properties.
When creat a message, developers can specify the header or property of a Service Bus message by below constants.

[source,java]
----
@Autowired
private Sinks.Many<Message<String>> many;

@PostMapping("/messages")
public ResponseEntity<String> sendMessage(@RequestParam String message) {
    many.emitNext(MessageBuilder.withPayload(message)
    .setHeader(SESSION_ID, "group1")
    .build(),
    Sinks.EmitFailureHandler.FAIL_FAST);
    return ResponseEntity.ok("Sent!");
}
----

For some Service Bus headers that can be mapped to multiple Spring header constants, the priority of different Spring headers is listed.
|===
Service Bus Message Headers and Properties | Spring Message Header Constants | Type | Priority Number (Descending priority)

ContentType | org.springframework.messaging.MessageHeaders.CONTENT_TYPE | String | N/A
CorrelationId | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.CORRELATION_ID | String | N/A
**MessageId** | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.MESSAGE_ID | String | 1
**MessageId** | com.azure.spring.messaging.AzureHeaders.RAW_ID | String | 2
**MessageId** | org.springframework.messaging.MessageHeaders.ID | UUID | 3
PartitionKey | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.PARTITION_KEY | String | N/A
ReplyTo | org.springframework.messaging.MessageHeaders.REPLY_CHANNEL | String | N/A
ReplyToSessionId | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.REPLY_TO_SESSION_ID | String | N/A
**ScheduledEnqueueTimeUtc** | com.azure.spring.messaging.AzureHeaders.SCHEDULED_ENQUEUE_MESSAGE | Integer | 1
**ScheduledEnqueueTimeUtc** | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.SCHEDULED_ENQUEUE_TIME | Instant | 2
SessionID | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.SESSION_ID | String | N/A
TimeToLive | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.TIME_TO_LIVE | Duration | N/A
To | com.azure.spring.servicebus.support.ServiceBusMessageHeaders.TO | String | N/A
|===



Please refer https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/servicebus/spring-cloud-azure-stream-binder-servicebus to learn how to
use ServiceBus Binder.

