== What Is New in 4.0 Since 3.10.x

This page covers changes made in 4.0 since 3.10. With this major release, we aim to bring better security, leaner dependencies, support for production readiness, and more.

TIP: To learn how to migrate to 4.0, please check link:appendix.html#migration-guide-for-4-0[the Appendix page].

The following list summarizes some of the changes that Spring Cloud Azure 4.0 provides:

* A unified development experience, with unified project name, artifact ID, and properties.
* Simplified dependency management using a single `spring-cloud-azure-dependencies` BOM.
* Expanded Azure support on link:https://start.spring.io[Spring Initializr] to cover Kafka, Event Hubs, Azure Cache for Redis, and Azure App Configuration.
* Rearchitected Spring module dependencies to remove excess layers and entanglement.
* Managed Identity support for Azure App Configuration, Event Hubs, Service Bus, Cosmos DB, Key Vault, Storage Blob, and Storage Queue.
* Continued support for authentication methods in the underlying Azure SDK from our Spring libraries, such as SAS token and token credential authentication with Service Bus and Event Hubs.
* link:https://docs.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable&preserve-view=true#defaultazurecredential[Credential chain] is now enabled by default, enabling applications to obtain credentials from application properties, environment variables, managed identity, IDEs, and so on.
* Granular access control at the resource level (such as Service Bus queue) to enable better security governance and adherence to IT policies.
* More options exposed in a Spring-idiomatic way through significantly improved auto-configuration coverage of Azure SDK clients for both synchronous and asynchronous scenarios.
* Added health indicators for Azure App Configuration, Event Hubs, Cosmos DB, Key Vault, Storage Blob, Storage Queue, and Storage File.
* Spring Cloud Sleuth support for all HTTP-based Azure SDKs.