= Spring Cloud Azure Event Hub Integration Code Sample

This code sample demonstrates how to use Spring Integration for Azure Event Hub.

Running this sample will be charged by Azure. You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

== How to run

1.  Create Azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how
to create credential file]
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put credential file under `src/main/resources/`.

3. Create Azure Event Hub Namespace and event hub. Please see https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-create[how to create].

4. Update event hub name in link:src/main/java/example/ReceiveController.java#L31[ReceiveController] and link:src/main/java/example/SendController.java#L34[SendController].

5. Update link:src/main/resources/application.properties[application.properties] file
+
....
# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file]
spring.cloud.azure.resource-group=[resource-group]

spring.cloud.azure.eventhub.namespace=[eventhub-namespace]
spring.cloud.azure.eventhub.checkpoint-storage-account=[checkpoint-storage-account]
....
+

6. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

7.  Send a POST request
+
....
$ curl -X POST http://localhost:8080/messages?message=hello
....

8. Verify in your app's logs that a similar message was posted:
+
....
Message arrived! Payload: hello
Message 'hello' successfully checkpointed
....

9. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid unexpected charges.
