= Azure redis cache spring cloud starter

Maven coordinates, using Spring Cloud Azure BOM:

[source,xml]
----
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-starter-cache</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'com.microsoft.azure', name: 'spring-cloud-azure-starter-cache'
}
----

This starter is based on spring-boot-starter-data-redis. It fetches and auto configures redis properties via Azure Redis
 Cache Management SDK.

=== How to run

1.  Create azure credential file. Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how to create credential file]
+
....
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoding with UTF-8.

2.  Put auth file under `src/main/resources/`

3.  Update `src/main/resources/application.properties` to specify resource group, cache instance name and credential file path:
+
....
spring.cloud.azure.credentialFilePath=[credential-file-path]
spring.cloud.azure.resourceGroup=[resource-group]
spring.cloud.azure.region=[region]

spring.cloud.azure.redis.name=[azure-redis-instance-name]
....
+
All azure resources will be created if missing. Alternatively, you can manually create
https://azure.microsoft.com/en-us/services/cache/[Azure redis cache].

4.  Run the application using the `$ mvn spring-boot:run` command.
5.  Send a GET request to check, where `name` could be any string:
+
....
$ curl -XGET http://localhost:8080/{name}
....
6.  Confirm from Azure Redis Cache console in Azure Portal
+
....
$ keys *
....

=== Examples
link:../../spring-cloud-azure-samples/spring-cloud-azure-cache-sample[Here]
is a sample application that uses this starter.
